// GENERATED by surface_gen — do not edit.
//
// Exhaustive smoke coverage for the generated fluent surface: 93
// classes, 1123 verbs, each invoked once with an argument of its declared
// type. The cases are never EXECUTED — compilation is the assertion, and the
// behaviour of every verb family is pinned per class by
// test/fluent/fluent_behavior_matrix_test.dart.
//
// Regenerate: dart run build_runner build
library;

import 'package:braven_charts/braven_charts_fluent.dart';
import 'package:flutter/widgets.dart'
    show
        Alignment,
        BorderRadius,
        BoxShadow,
        Color,
        Curve,
        EdgeInsets,
        FontWeight,
        Offset,
        StrokeCap,
        TextStyle;
import 'package:flutter_test/flutter_test.dart';

/// Smoke coverage for [AnnotationStyle]'s 6 generated verb(s).
void _smokeAnnotationStyle(
  AnnotationStyle subject,
  TextStyle a0,
  Color a1,
  Color a2,
  BorderRadius a3,
  EdgeInsets a4,
) {
  subject.withTextStyle(a0);
  subject.withBackgroundColor(a1);
  subject.withBorderColor(a2);
  subject.withBorderWidth(1.0);
  subject.withBorderRadius(a3);
  subject.withPadding(a4);
}

/// Smoke coverage for [AutoScrollConfig]'s 9 generated verb(s).
void _smokeAutoScrollConfig(AutoScrollConfig subject) {
  subject.withEnabled(true);
  subject.withMaxVisiblePoints(1);
  subject.withResumeOnNewData(true);
  subject.withPauseOnUserInteraction(true);
  subject.withResumeAfterInteractionDelay(const Duration(milliseconds: 1));
  subject.withAnimateIncomingData(true);
  subject.withIncomingDataAnimationDuration(const Duration(milliseconds: 1));
  subject.withAnimateScroll(true);
  subject.withScrollAnimationDuration(const Duration(milliseconds: 1));
}

/// Smoke coverage for [CandlestickChartSeries]'s 12 generated verb(s).
void _smokeCandlestickChartSeries(
  CandlestickChartSeries subject,
  Color a0,
  Map<String, dynamic> a1,
  List<ChartAnnotation> a2,
  YAxisConfig a3,
  CandlestickChartStyle a4,
  CandlestickAnimationStyle a5,
  CandlestickDensityGrouping a6,
) {
  subject.withId('x');
  subject.withName('x');
  subject.withColor(a0);
  subject.withMetadata(a1);
  subject.withAnnotations(a2);
  subject.withYAxisId('x');
  subject.withYAxisConfig(a3);
  subject.withUnit('x');
  subject.withCandlestickStyle(a4);
  subject.withAnimation(a5);
  subject.withDensityGrouping(a6);
  subject.updateDensityGrouping((current) => current);
}

/// Smoke coverage for [CandlestickDataPoint]'s 19 generated verb(s).
void _smokeCandlestickDataPoint(
  CandlestickDataPoint subject,
  DateTime a0,
  Map<String, dynamic> a1,
  SegmentStyle a2,
  PointStyle a3,
  CandlestickPointStyle a4,
) {
  subject.withX(1.0);
  subject.withMagnitude(1.0);
  subject.clearMagnitude();
  subject.withColorValue(1.0);
  subject.clearColorValue();
  subject.withOpacityValue(1.0);
  subject.clearOpacityValue();
  subject.withCategoryValue('x');
  subject.clearCategoryValue();
  subject.withTimestamp(a0);
  subject.withLabel('x');
  subject.withMetadata(a1);
  subject.withSegmentStyle(a2);
  subject.clearSegmentStyle();
  subject.withPointStyle(a3);
  subject.clearPointStyle();
  subject.withCandlestickStyle(a4);
  subject.clearCandlestickStyle();
  subject.withOhlc(1.0, 1.0, 1.0, 1.0);
}

/// Smoke coverage for [CandlestickDensityGrouping]'s 3 generated verb(s).
void _smokeCandlestickDensityGrouping(CandlestickDensityGrouping subject) {
  subject.withEnabled(true);
  subject.withTargetGroupWidth(1.0);
  subject.withMinimumPointsPerGroup(1);
}

/// Smoke coverage for [CartesianValueSummaryOverlay]'s 2 generated verb(s).
void _smokeCartesianValueSummaryOverlay(
  CartesianValueSummaryOverlay subject,
  ChartOverlayPlacement a0,
) {
  subject.withPlacement(a0);
  subject.updatePlacement((current) => current);
}

/// Smoke coverage for [CartesianValueSummaryAnnotation]'s 4 generated verb(s).
void _smokeCartesianValueSummaryAnnotation(
  CartesianValueSummaryAnnotation subject,
  ChartOverlayPlacement a0,
) {
  subject.withPlacement(a0);
  subject.updatePlacement((current) => current);
  subject.withDraggable(true);
  subject.withClampToPlot(true);
}

/// Smoke coverage for [CartesianValueSummaryAutomaticContent]'s 2 generated verb(s).
void _smokeCartesianValueSummaryAutomaticContent(
  CartesianValueSummaryAutomaticContent subject,
) {
  subject.withIncludeTrends(true);
  subject.withIncludeHiddenSeries(true);
}

/// Smoke coverage for [CartesianValueSummaryConfig]'s 15 generated verb(s).
void _smokeCartesianValueSummaryConfig(
  CartesianValueSummaryConfig subject,
  CartesianValueSummaryPresentation a0,
  CartesianValueSummaryContent a1,
  CartesianValueSummaryContentModel Function(CartesianTrackingSnapshot) a2,
  CartesianValueSummaryStyle a3,
) {
  subject.withEnabled(true);
  subject.withPresentation(a0);
  subject.withOverlayPresentation();
  subject.withAnnotationPresentation();
  subject.updatePresentation((current) => current);
  subject.withValuePolicy(CartesianValueSummaryValuePolicy.values.first);
  subject.withValueMode(CartesianValueSummaryValueMode.values.first);
  subject.withContent(a1);
  subject.withAutomaticContent();
  subject.withBuilderContent(a2);
  subject.updateContent((current) => current);
  subject.withStyle(a3);
  subject.updateStyle((current) => current);
  subject.withShowSeriesAccent(true);
  subject.withAnnounceChanges(true);
}

/// Smoke coverage for [CartesianValueSummaryStyle]'s 42 generated verb(s).
void _smokeCartesianValueSummaryStyle(
  CartesianValueSummaryStyle subject,
  Color a0,
  Color a1,
  BorderRadius a2,
  EdgeInsets a3,
  TextStyle a4,
  TextStyle a5,
  Color a6,
  BoxShadow a7,
) {
  subject.withBackgroundColor(a0);
  subject.withoutBackgroundColor();
  subject.inheritBackgroundColor();
  subject.withBackgroundOpacity(1.0);
  subject.withoutBackgroundOpacity();
  subject.inheritBackgroundOpacity();
  subject.withBorderColor(a1);
  subject.withoutBorderColor();
  subject.inheritBorderColor();
  subject.withBorderWidth(1.0);
  subject.withoutBorderWidth();
  subject.inheritBorderWidth();
  subject.withBorderRadius(a2);
  subject.withoutBorderRadius();
  subject.inheritBorderRadius();
  subject.withPadding(a3);
  subject.withoutPadding();
  subject.inheritPadding();
  subject.withTextStyle(a4);
  subject.withoutTextStyle();
  subject.inheritTextStyle();
  subject.withLabelStyle(a5);
  subject.withoutLabelStyle();
  subject.inheritLabelStyle();
  subject.withAccentColor(a6);
  subject.withoutAccentColor();
  subject.inheritAccentColor();
  subject.withShadow(a7);
  subject.withoutShadow();
  subject.inheritShadow();
  subject.withMinWidth(1.0);
  subject.withoutMinWidth();
  subject.inheritMinWidth();
  subject.withMaxWidth(1.0);
  subject.withoutMaxWidth();
  subject.inheritMaxWidth();
  subject.withRowGap(1.0);
  subject.withoutRowGap();
  subject.inheritRowGap();
  subject.withLabelValueGap(1.0);
  subject.withoutLabelValueGap();
  subject.inheritLabelValueGap();
}

/// Smoke coverage for [CategoryAxisConfig]'s 8 generated verb(s).
void _smokeCategoryAxisConfig(CategoryAxisConfig subject, List<String> a0) {
  subject.withCategories(a0);
  subject.withLabelDensity(CategoryLabelDensity.values.first);
  subject.withLabelOverflow(CategoryLabelOverflow.values.first);
  subject.withMinimumCategoryExtent(1.0);
  subject.withMaximumLabelExtent(1.0);
  subject.withMaxLabelLines(1);
  subject.withLabelRotationDegrees(1.0);
  subject.withAutoViewport(true);
}

/// Smoke coverage for [PointAnnotation]'s 14 generated verb(s).
void _smokePointAnnotation(
  PointAnnotation subject,
  AnnotationStyle a0,
  Offset a1,
  Color a2,
) {
  subject.withId('x');
  subject.withLabel('x');
  subject.withStyle(a0);
  subject.updateStyle((current) => current);
  subject.withAllowDragging(true);
  subject.withAllowEditing(true);
  subject.withZIndex(1);
  subject.withSeriesId('x');
  subject.withDataPointIndex(1);
  subject.withOffset(a1);
  subject.withMarkerShape(MarkerShape.values.first);
  subject.withMarkerSize(1.0);
  subject.withMarkerColor(a2);
  subject.withLabelMargin(1.0);
}

/// Smoke coverage for [RangeAnnotation]'s 16 generated verb(s).
void _smokeRangeAnnotation(
  RangeAnnotation subject,
  AnnotationStyle a0,
  Color a1,
  Color a2,
) {
  subject.withId('x');
  subject.withLabel('x');
  subject.withStyle(a0);
  subject.updateStyle((current) => current);
  subject.withAllowDragging(true);
  subject.withAllowEditing(true);
  subject.withZIndex(1);
  subject.withSnapToValue(true);
  subject.withSnapIncrement(1.0);
  subject.withSnapTolerance(1.0);
  subject.withSeriesId('x');
  subject.withFillColor(a1);
  subject.withBorderColor(a2);
  subject.withLabelPosition(AnnotationLabelPosition.values.first);
  subject.withLabelMargin(1.0);
  subject.withBounds(1.0, 1.0, 1.0, 1.0);
}

/// Smoke coverage for [TextAnnotation]'s 12 generated verb(s).
void _smokeTextAnnotation(
  TextAnnotation subject,
  AnnotationStyle a0,
  Offset a1,
  Color a2,
  Color a3,
) {
  subject.withId('x');
  subject.withLabel('x');
  subject.withStyle(a0);
  subject.updateStyle((current) => current);
  subject.withAllowDragging(true);
  subject.withAllowEditing(true);
  subject.withZIndex(1);
  subject.withText('x');
  subject.withPosition(a1);
  subject.withAnchor(AnnotationAnchor.values.first);
  subject.withBackgroundColor(a2);
  subject.withBorderColor(a3);
}

/// Smoke coverage for [ThresholdAnnotation]'s 16 generated verb(s).
void _smokeThresholdAnnotation(
  ThresholdAnnotation subject,
  AnnotationStyle a0,
  Color a1,
  List<double> a2,
) {
  subject.withId('x');
  subject.withLabel('x');
  subject.withStyle(a0);
  subject.updateStyle((current) => current);
  subject.withAllowDragging(true);
  subject.withAllowEditing(true);
  subject.withZIndex(1);
  subject.withAxis(AnnotationAxis.values.first);
  subject.withValue(1.0);
  subject.withSeriesId('x');
  subject.withLineColor(a1);
  subject.withLineWidth(1.0);
  subject.withDashPattern(a2);
  subject.withLabelPosition(AnnotationLabelPosition.values.first);
  subject.withLabelMargin(1.0);
  subject.withElevation(1.0);
}

/// Smoke coverage for [PinAnnotation]'s 13 generated verb(s).
void _smokePinAnnotation(PinAnnotation subject, AnnotationStyle a0, Color a1) {
  subject.withId('x');
  subject.withLabel('x');
  subject.withStyle(a0);
  subject.updateStyle((current) => current);
  subject.withAllowDragging(true);
  subject.withAllowEditing(true);
  subject.withZIndex(1);
  subject.withX(1.0);
  subject.withY(1.0);
  subject.withMarkerShape(MarkerShape.values.first);
  subject.withMarkerSize(1.0);
  subject.withMarkerColor(a1);
  subject.withLabelMargin(1.0);
}

/// Smoke coverage for [TrendAnnotation]'s 29 generated verb(s).
void _smokeTrendAnnotation(
  TrendAnnotation subject,
  AnnotationStyle a0,
  Color a1,
  Color a2,
  Color a3,
  List<double> a4,
) {
  subject.withId('x');
  subject.withLabel('x');
  subject.withStyle(a0);
  subject.updateStyle((current) => current);
  subject.withAllowDragging(true);
  subject.withAllowEditing(true);
  subject.withZIndex(1);
  subject.withSeriesId('x');
  subject.withDegree(1);
  subject.withLoessSpan(1.0);
  subject.withLoessRobustnessIterations(1);
  subject.withLoessSampleCount(1);
  subject.withShowEquation(true);
  subject.withShowRSquared(true);
  subject.withShowSampleCount(true);
  subject.withShowPearsonCorrelation(true);
  subject.withShowSpearmanCorrelation(true);
  subject.withShowConfidenceBand(true);
  subject.withShowPredictionBand(true);
  subject.withConfidenceLevel(1.0);
  subject.withConfidenceBandColor(a1);
  subject.withPredictionBandColor(a2);
  subject.withConfidenceBandOpacity(1.0);
  subject.withPredictionBandOpacity(1.0);
  subject.withLineColor(a3);
  subject.withLineWidth(1.0);
  subject.withDashPattern(a4);
  subject.withElevation(1.0);
  subject.withTrend(TrendType.values.first, 1);
}

/// Smoke coverage for [ErrorBarAnnotation]'s 11 generated verb(s).
void _smokeErrorBarAnnotation(
  ErrorBarAnnotation subject,
  AnnotationStyle a0,
  List<ErrorBarDatum> a1,
  Color a2,
) {
  subject.withId('x');
  subject.withLabel('x');
  subject.withStyle(a0);
  subject.updateStyle((current) => current);
  subject.withAllowEditing(true);
  subject.withZIndex(1);
  subject.withSeriesId('x');
  subject.withValues(a1);
  subject.withLineColor(a2);
  subject.withLineWidth(1.0);
  subject.withCapSize(1.0);
}

/// Smoke coverage for [ChordAnnotation]'s 21 generated verb(s).
void _smokeChordAnnotation(
  ChordAnnotation subject,
  AnnotationStyle a0,
  Color a1,
  List<double> a2,
  Offset a3,
  AnnotationStyle a4,
  Color a5,
  List<double> a6,
) {
  subject.withId('x');
  subject.withLabel('x');
  subject.withStyle(a0);
  subject.updateStyle((current) => current);
  subject.withAllowDragging(true);
  subject.withAllowEditing(true);
  subject.withZIndex(1);
  subject.withSeriesId('x');
  subject.withLineColor(a1);
  subject.withLineWidth(1.0);
  subject.withDashPattern(a2);
  subject.withElevation(1.0);
  subject.withPerpendicularIndex(1);
  subject.withPerpendicularLabel('x');
  subject.withPerpendicularLabelOffset(a3);
  subject.withPerpendicularLabelStyle(a4);
  subject.withPerpendicularLineColor(a5);
  subject.withPerpendicularLineWidth(1.0);
  subject.withPerpendicularDashPattern(a6);
  subject.withPerpendicularElevation(1.0);
  subject.withEndpoints(1, 1);
}

/// Smoke coverage for [LegendAnnotation]'s 11 generated verb(s).
void _smokeLegendAnnotation(
  LegendAnnotation subject,
  List<ChartSeries> a0,
  List<TrendAnnotation> a1,
  List<ErrorBarAnnotation> a2,
  LegendStyle a3,
  Set<String> a4,
  Offset a5,
) {
  subject.withId('x');
  subject.withLabel('x');
  subject.withZIndex(1);
  subject.withSeries(a0);
  subject.withTrendAnnotations(a1);
  subject.withErrorBarAnnotations(a2);
  subject.withLegendStyle(a3);
  subject.updateLegendStyle((current) => current);
  subject.withHiddenSeriesIds(a4);
  subject.withCustomPosition(a5);
  subject.clearCustomPosition();
}

/// Smoke coverage for [ChartDataPoint]'s 17 generated verb(s).
void _smokeChartDataPoint(
  ChartDataPoint subject,
  DateTime a0,
  Map<String, dynamic> a1,
  SegmentStyle a2,
  PointStyle a3,
) {
  subject.withX(1.0);
  subject.withY(1.0);
  subject.withMagnitude(1.0);
  subject.clearMagnitude();
  subject.withColorValue(1.0);
  subject.clearColorValue();
  subject.withOpacityValue(1.0);
  subject.clearOpacityValue();
  subject.withCategoryValue('x');
  subject.clearCategoryValue();
  subject.withTimestamp(a0);
  subject.withLabel('x');
  subject.withMetadata(a1);
  subject.withSegmentStyle(a2);
  subject.clearSegmentStyle();
  subject.withPointStyle(a3);
  subject.clearPointStyle();
}

/// Smoke coverage for [ChartOverlayPlacement]'s 2 generated verb(s).
void _smokeChartOverlayPlacement(
  ChartOverlayPlacement subject,
  Alignment a0,
  Offset a1,
) {
  subject.withAnchor(a0);
  subject.withOffset(a1);
}

/// Smoke coverage for [LineChartSeries]'s 24 generated verb(s).
void _smokeLineChartSeries(
  LineChartSeries subject,
  List<ChartDataPoint> a0,
  Color a1,
  Map<String, dynamic> a2,
  List<ChartAnnotation> a3,
  YAxisConfig a4,
  Color a5,
  DataPointLabelConfig a6,
  SeriesInlineLabelConfig a7,
  PathAnimationStyle a8,
  List<double> a9,
) {
  subject.withId('x');
  subject.withName('x');
  subject.withPoints(a0);
  subject.withColor(a1);
  subject.withXOrdered(true);
  subject.withMetadata(a2);
  subject.withStyle(SeriesStyle.values.first);
  subject.withAnnotations(a3);
  subject.withYAxisId('x');
  subject.withYAxisConfig(a4);
  subject.withUnit('x');
  subject.withInterpolation(LineInterpolation.values.first);
  subject.withStrokeWidth(1.0);
  subject.withTension(1.0);
  subject.withShowDataPointMarkers(true);
  subject.withDataPointMarkerRadius(1.0);
  subject.withDataPointMarkerStyle(DataPointMarkerStyle.values.first);
  subject.withDataPointMarkerBackground(a5);
  subject.withLineGlow(1.0);
  subject.withDataPointLabels(a6);
  subject.withInlineLabel(a7);
  subject.withPathAnimation(a8);
  subject.updatePathAnimation((current) => current);
  subject.withDashPattern(a9);
}

/// Smoke coverage for [ScatterChartSeries]'s 32 generated verb(s).
void _smokeScatterChartSeries(
  ScatterChartSeries subject,
  List<ChartDataPoint> a0,
  Color a1,
  Map<String, dynamic> a2,
  List<ChartAnnotation> a3,
  YAxisConfig a4,
  ScatterMarkerStyle a5,
  ScatterSizeEncoding a6,
  ScatterColorEncoding a7,
  ScatterOpacityEncoding a8,
  ScatterCategoryEncoding a9,
  ScatterJitterConfig a10,
  ScatterClusterConfig a11,
  ScatterBinConfig a12,
  ScatterDensityConfig a13,
  DataPointLabelConfig a14,
  ScatterInteractionStyle a15,
) {
  subject.withId('x');
  subject.withName('x');
  subject.withPoints(a0);
  subject.withColor(a1);
  subject.withXOrdered(true);
  subject.withMetadata(a2);
  subject.withStyle(SeriesStyle.values.first);
  subject.withAnnotations(a3);
  subject.withYAxisId('x');
  subject.withYAxisConfig(a4);
  subject.withUnit('x');
  subject.withMarkerRadius(1.0);
  subject.withMarkerShape(SeriesMarkerShape.values.first);
  subject.withMarkerStyle(a5);
  subject.clearMarkerStyle();
  subject.withSizeEncoding(a6);
  subject.clearSizeEncoding();
  subject.withColorEncoding(a7);
  subject.clearColorEncoding();
  subject.withOpacityEncoding(a8);
  subject.clearOpacityEncoding();
  subject.withCategoryEncoding(a9);
  subject.clearCategoryEncoding();
  subject.withJitter(a10);
  subject.withRenderMode(ScatterRenderMode.values.first);
  subject.withClusterConfig(a11);
  subject.withBinConfig(a12);
  subject.withDensityConfig(a13);
  subject.withDataPointLabels(a14);
  subject.clearDataPointLabels();
  subject.withInteractionStyle(a15);
  subject.updateInteractionStyle((current) => current);
}

/// Smoke coverage for [AreaChartSeries]'s 30 generated verb(s).
void _smokeAreaChartSeries(
  AreaChartSeries subject,
  List<ChartDataPoint> a0,
  Color a1,
  Map<String, dynamic> a2,
  List<ChartAnnotation> a3,
  YAxisConfig a4,
  AreaGradient a5,
  Color a6,
  DataPointLabelConfig a7,
  SeriesInlineLabelConfig a8,
  Color a9,
  Color a10,
  PathAnimationStyle a11,
  List<double> a12,
) {
  subject.withId('x');
  subject.withName('x');
  subject.withPoints(a0);
  subject.withColor(a1);
  subject.withXOrdered(true);
  subject.withMetadata(a2);
  subject.withStyle(SeriesStyle.values.first);
  subject.withAnnotations(a3);
  subject.withYAxisId('x');
  subject.withYAxisConfig(a4);
  subject.withUnit('x');
  subject.withInterpolation(LineInterpolation.values.first);
  subject.withStrokeWidth(1.0);
  subject.withTension(1.0);
  subject.withFillOpacity(1.0);
  subject.withFillGradient(a5);
  subject.clearFillGradient();
  subject.withShowDataPointMarkers(true);
  subject.withDataPointMarkerRadius(1.0);
  subject.withDataPointMarkerStyle(DataPointMarkerStyle.values.first);
  subject.withDataPointMarkerBackground(a6);
  subject.withLineGlow(1.0);
  subject.withDataPointLabels(a7);
  subject.withInlineLabel(a8);
  subject.withBaselineValue(1.0);
  subject.withAboveBaselineFillColor(a9);
  subject.withBelowBaselineFillColor(a10);
  subject.withPathAnimation(a11);
  subject.updatePathAnimation((current) => current);
  subject.withDashPattern(a12);
}

/// Smoke coverage for [BarChartSeries]'s 40 generated verb(s).
void _smokeBarChartSeries(
  BarChartSeries subject,
  List<ChartDataPoint> a0,
  Color a1,
  Map<String, dynamic> a2,
  List<ChartAnnotation> a3,
  YAxisConfig a4,
  BarDivergingStyle a5,
  List<double?> a6,
  Set<int> a7,
  BarWaterfallStyle a8,
  BarChartStyle a9,
  BarTrackStyle a10,
  BarLollipopStyle a11,
  BarBulletStyle a12,
  List<double?> a13,
  BarTargetMarkerStyle a14,
  List<double?> a15,
  List<double?> a16,
  BarErrorBarStyle a17,
  BarLabelStyle a18,
) {
  subject.withId('x');
  subject.withName('x');
  subject.withPoints(a0);
  subject.withColor(a1);
  subject.withXOrdered(true);
  subject.withMetadata(a2);
  subject.withStyle(SeriesStyle.values.first);
  subject.withAnnotations(a3);
  subject.withYAxisId('x');
  subject.withYAxisConfig(a4);
  subject.withUnit('x');
  subject.withBarGap(1.0);
  subject.withOrientation(BarOrientation.values.first);
  subject.withLayoutMode(BarLayoutMode.values.first);
  subject.withGroupId('x');
  subject.clearGroupId();
  subject.withDivergingRole(BarDivergingRole.values.first);
  subject.withDivergingStyle(a5);
  subject.withOverlayWidthFactor(1.0);
  subject.withOverlayOffsetFactor(1.0);
  subject.withBaselineValue(1.0);
  subject.withRangeStartValues(a6);
  subject.withWaterfallTotalIndices(a7);
  subject.withWaterfallStyle(a8);
  subject.withMinBarLength(1.0);
  subject.withBarStyle(a9);
  subject.withTrackStyle(a10);
  subject.clearTrackStyle();
  subject.withLollipopStyle(a11);
  subject.clearLollipopStyle();
  subject.withBulletStyle(a12);
  subject.clearBulletStyle();
  subject.withTargetValues(a13);
  subject.withTargetMarkerStyle(a14);
  subject.withErrorLowerValues(a15);
  subject.withErrorUpperValues(a16);
  subject.withErrorBarStyle(a17);
  subject.withLabelStyle(a18);
  subject.withBarWidth(1.0, 1.0);
  subject.withWidthBounds(1.0, 1.0);
}

/// Smoke coverage for [ChartTheme]'s 28 generated verb(s).
void _smokeChartTheme(
  ChartTheme subject,
  Color a0,
  GridStyle a1,
  AxisStyle a2,
  SeriesTheme a3,
  InteractionTheme a4,
  TypographyTheme a5,
  AnimationTheme a6,
  AnnotationTheme a7,
  ScrollbarConfig a8,
  LegendStyle a9,
  PieChartTheme a10,
  CandlestickTheme a11,
  CartesianValueSummaryTheme a12,
  Color a13,
) {
  subject.withBackgroundColor(a0);
  subject.withGridStyle(a1);
  subject.updateGridStyle((current) => current);
  subject.withAxisStyle(a2);
  subject.updateAxisStyle((current) => current);
  subject.withSeriesTheme(a3);
  subject.updateSeriesTheme((current) => current);
  subject.withInteractionTheme(a4);
  subject.updateInteractionTheme((current) => current);
  subject.withTypographyTheme(a5);
  subject.updateTypographyTheme((current) => current);
  subject.withAnimationTheme(a6);
  subject.updateAnimationTheme((current) => current);
  subject.withAnnotationTheme(a7);
  subject.updateAnnotationTheme((current) => current);
  subject.withScrollbarConfig(a8);
  subject.updateScrollbarConfig((current) => current);
  subject.withLegendStyle(a9);
  subject.updateLegendStyle((current) => current);
  subject.withPieChartTheme(a10);
  subject.updatePieChartTheme((current) => current);
  subject.withCandlestickTheme(a11);
  subject.updateCandlestickTheme((current) => current);
  subject.withCartesianValueSummaryTheme(a12);
  subject.updateCartesianValueSummaryTheme((current) => current);
  subject.withFocusBorderColor(a13);
  subject.withFocusBorderWidth(1.0);
  subject.withFocusBorderRadius(1.0);
}

/// Smoke coverage for [ConcentricDonutConfig]'s 8 generated verb(s).
void _smokeConcentricDonutConfig(
  ConcentricDonutConfig subject,
  Map<String, double> a0,
  DonutCenterContent a1,
) {
  subject.withInnerRadiusFactor(1.0);
  subject.withOuterRadiusFactor(1.0);
  subject.withRingGap(1.0);
  subject.withOrder(ConcentricRingOrder.values.first);
  subject.withRingWeights(a0);
  subject.withLegendMode(ConcentricDonutLegendMode.values.first);
  subject.withCenterContent(a1);
  subject.updateCenterContent((current) => current);
}

/// Smoke coverage for [DataPointLabelConfig]'s 15 generated verb(s).
void _smokeDataPointLabelConfig(
  DataPointLabelConfig subject,
  Color a0,
  FontWeight a1,
  Color a2,
) {
  subject.withShow(true);
  subject.withPosition(DataPointLabelPosition.values.first);
  subject.withContent(DataPointLabelContent.values.first);
  subject.withOffsetX(1.0);
  subject.withOffsetY(1.0);
  subject.withMarkerGap(1.0);
  subject.withCollisionPolicy(DataPointLabelCollisionPolicy.values.first);
  subject.withCollisionPadding(1.0);
  subject.withPlotEdgeAware(true);
  subject.withLabelColor(a0);
  subject.withFontSize(1.0);
  subject.withFontWeight(a1);
  subject.withShowUnit(true);
  subject.withBackground(a2);
  subject.withBackgroundOpacity(1.0);
}

/// Smoke coverage for [DonutCenterContent]'s 10 generated verb(s).
void _smokeDonutCenterContent(
  DonutCenterContent subject,
  LabelStyle a0,
  LabelStyle a1,
) {
  subject.withVisible(true);
  subject.withLabel('x');
  subject.clearLabel();
  subject.withValueMode(DonutCenterValueMode.values.first);
  subject.withCustomValue('x');
  subject.clearCustomValue();
  subject.withLabelStyle(a0);
  subject.clearLabelStyle();
  subject.withValueStyle(a1);
  subject.clearValueStyle();
}

/// Smoke coverage for [DonutChartStyle]'s 33 generated verb(s).
void _smokeDonutChartStyle(
  DonutChartStyle subject,
  Color a0,
  PieGradientStyle a1,
  PieElevationStyle a2,
  PieElevationStyle a3,
) {
  subject.withInnerRadiusFactor(1.0);
  subject.withSweepAngleDegrees(1.0);
  subject.withStartAngleDegrees(1.0);
  subject.withClockwise(true);
  subject.withRadiusFactor(1.0);
  subject.withSliceGap(1.0);
  subject.withBorderWidth(1.0);
  subject.withBorderColor(a0);
  subject.clearBorderColor();
  subject.withBorderColorMode(PieBorderColorMode.values.first);
  subject.clearBorderColorMode();
  subject.withBorderHueShiftDegrees(1.0);
  subject.clearBorderHueShiftDegrees();
  subject.withBorderSaturationShift(1.0);
  subject.clearBorderSaturationShift();
  subject.withBorderLightnessShift(1.0);
  subject.clearBorderLightnessShift();
  subject.withGradient(a1);
  subject.clearGradient();
  subject.withSelectionExplodeOffset(1.0);
  subject.withOpacity(1.0);
  subject.clearOpacity();
  subject.withCornerRadius(1.0);
  subject.clearCornerRadius();
  subject.withCornerTreatment(PieCornerTreatment.values.first);
  subject.clearCornerTreatment();
  subject.withShadow(a2);
  subject.clearShadow();
  subject.withSelectedElevation(a3);
  subject.clearSelectedElevation();
  subject.withAnimationMode(PieAnimationMode.values.first);
  subject.clearAnimationMode();
  subject.withDataTransitionMode(RadialDataTransitionMode.values.first);
}

/// Smoke coverage for [DonutChartSeries]'s 18 generated verb(s).
void _smokeDonutChartSeries(
  DonutChartSeries subject,
  List<ChartDataPoint> a0,
  Color a1,
  Map<String, dynamic> a2,
  DonutChartStyle a3,
  RadialSelectionStyle a4,
  DonutCenterContent a5,
  PieDataLabelConfig a6,
  PieSliceRadiusConfig a7,
  RadialSliceGroupingConfig a8,
) {
  subject.withId('x');
  subject.withName('x');
  subject.withPoints(a0);
  subject.withColor(a1);
  subject.withMetadata(a2);
  subject.withUnit('x');
  subject.withDonutStyle(a3);
  subject.updateDonutStyle((current) => current);
  subject.withSelectionStyle(a4);
  subject.updateSelectionStyle((current) => current);
  subject.withCenterContent(a5);
  subject.updateCenterContent((current) => current);
  subject.withDataLabels(a6);
  subject.updateDataLabels((current) => current);
  subject.withSliceRadiusConfig(a7);
  subject.clearSliceRadiusConfig();
  subject.withSliceGroupingConfig(a8);
  subject.clearSliceGroupingConfig();
}

/// Smoke coverage for [GridConfig]'s 6 generated verb(s).
void _smokeGridConfig(GridConfig subject, Color a0, Color a1) {
  subject.withHorizontal(true);
  subject.withVertical(true);
  subject.withHorizontalColor(a0);
  subject.withVerticalColor(a1);
  subject.withHorizontalStrokeWidth(1.0);
  subject.withVerticalStrokeWidth(1.0);
}

/// Smoke coverage for [CrosshairStyle]'s 7 generated verb(s).
void _smokeCrosshairStyle(
  CrosshairStyle subject,
  Color a0,
  List<double> a1,
  Color a2,
  Color a3,
) {
  subject.withLineColor(a0);
  subject.withLineWidth(1.0);
  subject.withDashPattern(a1);
  subject.withStrokeCap(StrokeCap.values.first);
  subject.withLabelBackgroundColor(a2);
  subject.withLabelTextColor(a3);
  subject.withLabelPadding(1.0);
}

/// Smoke coverage for [CrosshairConfig]'s 14 generated verb(s).
void _smokeCrosshairConfig(
  CrosshairConfig subject,
  TextStyle a0,
  CrosshairStyle a1,
) {
  subject.withEnabled(true);
  subject.withMode(CrosshairMode.values.first);
  subject.withSnapToDataPoint(true);
  subject.withSnapRadius(1.0);
  subject.withShowCoordinateLabels(true);
  subject.withCoordinateLabelStyle(a0);
  subject.withStyle(a1);
  subject.updateStyle((current) => current);
  subject.withDisplayMode(CrosshairDisplayMode.values.first);
  subject.withTrackingModeThreshold(1);
  subject.withInterpolateValues(true);
  subject.withShowTrackingTooltip(true);
  subject.withShowIntersectionMarkers(true);
  subject.withIntersectionMarkerRadius(1.0);
}

/// Smoke coverage for [TooltipStyle]'s 9 generated verb(s).
void _smokeTooltipStyle(
  TooltipStyle subject,
  Color a0,
  Color a1,
  Color a2,
  Color a3,
) {
  subject.withBackgroundColor(a0);
  subject.withBorderColor(a1);
  subject.withBorderWidth(1.0);
  subject.withBorderRadius(1.0);
  subject.withShadowColor(a2);
  subject.withShadowBlurRadius(1.0);
  subject.withPadding(1.0);
  subject.withTextColor(a3);
  subject.withFontSize(1.0);
}

/// Smoke coverage for [TooltipConfig]'s 9 generated verb(s).
void _smokeTooltipConfig(TooltipConfig subject, TooltipStyle a0) {
  subject.withEnabled(true);
  subject.withTriggerMode(TooltipTriggerMode.values.first);
  subject.withPreferredPosition(TooltipPosition.values.first);
  subject.withShowDelay(const Duration(milliseconds: 1));
  subject.withHideDelay(const Duration(milliseconds: 1));
  subject.withFollowCursor(true);
  subject.withOffsetFromPoint(1.0);
  subject.withStyle(a0);
  subject.updateStyle((current) => current);
}

/// Smoke coverage for [GestureConfig]'s 4 generated verb(s).
void _smokeGestureConfig(GestureConfig subject) {
  subject.withTapTimeout(const Duration(milliseconds: 1));
  subject.withLongPressTimeout(const Duration(milliseconds: 1));
  subject.withPanThreshold(1.0);
  subject.withPinchThreshold(1.0);
}

/// Smoke coverage for [KeyboardConfig]'s 6 generated verb(s).
void _smokeKeyboardConfig(KeyboardConfig subject) {
  subject.withEnabled(true);
  subject.withPanStep(1.0);
  subject.withZoomStep(1.0);
  subject.withEnableArrowKeys(true);
  subject.withEnablePlusMinusKeys(true);
  subject.withEnableHomeEndKeys(true);
}

/// Smoke coverage for [ChartSelectionConfig]'s 5 generated verb(s).
void _smokeChartSelectionConfig(ChartSelectionConfig subject) {
  subject.withMode(ChartSelectionMode.values.first);
  subject.withOperation(ChartSelectionOperation.values.first);
  subject.withDragActivation(ChartSelectionDragActivation.values.first);
  subject.withClearOnBackgroundTap(true);
  subject.withUseModifierKeys(true);
}

/// Smoke coverage for [InteractionConfig]'s 21 generated verb(s).
void _smokeInteractionConfig(
  InteractionConfig subject,
  CrosshairConfig a0,
  TooltipConfig a1,
  GestureConfig a2,
  KeyboardConfig a3,
  ChartSelectionConfig a4,
  CartesianValueSummaryConfig a5,
) {
  subject.withEnabled(true);
  subject.withCrosshair(a0);
  subject.updateCrosshair((current) => current);
  subject.withTooltip(a1);
  subject.updateTooltip((current) => current);
  subject.withGesture(a2);
  subject.updateGesture((current) => current);
  subject.withKeyboard(a3);
  subject.updateKeyboard((current) => current);
  subject.withEnableZoom(true);
  subject.withEnablePan(true);
  subject.withEnableSelection(true);
  subject.withSelection(a4);
  subject.updateSelection((current) => current);
  subject.withValueSummary(a5);
  subject.updateValueSummary((current) => current);
  subject.withShowFocusBorder(true);
  subject.withEnableFocusOnHover(true);
  subject.withShowXScrollbar(true);
  subject.withShowYScrollbar(true);
  subject.withKeyboardZoomPercent(1);
}

/// Smoke coverage for [LegendStyle]'s 16 generated verb(s).
void _smokeLegendStyle(
  LegendStyle subject,
  TextStyle a0,
  Color a1,
  Color a2,
  BorderRadius a3,
  EdgeInsets a4,
  Offset a5,
) {
  subject.withPosition(LegendPosition.values.first);
  subject.withOrientation(LegendOrientation.values.first);
  subject.withTextStyle(a0);
  subject.withBackgroundColor(a1);
  subject.withBorderColor(a2);
  subject.withBorderWidth(1.0);
  subject.withBorderRadius(a3);
  subject.withPadding(a4);
  subject.withItemSpacing(1.0);
  subject.withMarkerSize(1.0);
  subject.withMarkerShape(LegendMarkerShape.values.first);
  subject.withMarkerLineWidth(1.0);
  subject.withMarkerLabelSpacing(1.0);
  subject.withAllowDragging(true);
  subject.withOpacity(1.0);
  subject.withOffset(a5);
}

/// Smoke coverage for [MultiAxisConfig]'s 3 generated verb(s).
void _smokeMultiAxisConfig(
  MultiAxisConfig subject,
  List<YAxisConfig> a0,
  List<SeriesAxisBinding> a1,
) {
  subject.withAxes(a0);
  subject.withBindings(a1);
  subject.withMode(NormalizationMode.values.first);
}

/// Smoke coverage for [PathAnimationTiming]'s 3 generated verb(s).
void _smokePathAnimationTiming(PathAnimationTiming subject) {
  subject.withDelay(const Duration(milliseconds: 1));
  subject.withDuration(const Duration(milliseconds: 1));
  subject.clearDuration();
}

/// Smoke coverage for [PathAnimationStyle]'s 6 generated verb(s).
void _smokePathAnimationStyle(
  PathAnimationStyle subject,
  PathAnimationTiming a0,
  PathAnimationTiming a1,
) {
  subject.withEntranceMode(PathEntranceAnimationMode.values.first);
  subject.withDataUpdateMode(PathDataUpdateAnimationMode.values.first);
  subject.withEntranceTiming(a0);
  subject.updateEntranceTiming((current) => current);
  subject.withDataUpdateTiming(a1);
  subject.updateDataUpdateTiming((current) => current);
}

/// Smoke coverage for [PieGradientStyle]'s 9 generated verb(s).
void _smokePieGradientStyle(PieGradientStyle subject, Color a0, Color a1) {
  subject.withEnabled(true);
  subject.withType(PieGradientType.values.first);
  subject.withStartColor(a0);
  subject.clearStartColor();
  subject.withEndColor(a1);
  subject.clearEndColor();
  subject.withStartLightnessShift(1.0);
  subject.withEndLightnessShift(1.0);
  subject.withAngleDegrees(1.0);
}

/// Smoke coverage for [PieElevationStyle]'s 6 generated verb(s).
void _smokePieElevationStyle(PieElevationStyle subject, Color a0, Offset a1) {
  subject.withColor(a0);
  subject.clearColor();
  subject.withBlurRadius(1.0);
  subject.withSpreadRadius(1.0);
  subject.withOffset(a1);
  subject.withOpacity(1.0);
}

/// Smoke coverage for [PieChartTheme]'s 20 generated verb(s).
void _smokePieChartTheme(
  PieChartTheme subject,
  PieElevationStyle a0,
  PieElevationStyle a1,
  PieGradientStyle a2,
  LabelStyle a3,
  LabelStyle a4,
  LabelStyle a5,
) {
  subject.withOpacity(1.0);
  subject.withCornerRadius(1.0);
  subject.withCornerTreatment(PieCornerTreatment.values.first);
  subject.withShadow(a0);
  subject.updateShadow((current) => current);
  subject.withSelectedElevation(a1);
  subject.updateSelectedElevation((current) => current);
  subject.withBorderColorMode(PieBorderColorMode.values.first);
  subject.withBorderHueShiftDegrees(1.0);
  subject.withBorderSaturationShift(1.0);
  subject.withBorderLightnessShift(1.0);
  subject.withGradient(a2);
  subject.clearGradient();
  subject.withCalloutStyle(a3);
  subject.clearCalloutStyle();
  subject.withCenterLabelStyle(a4);
  subject.clearCenterLabelStyle();
  subject.withCenterValueStyle(a5);
  subject.clearCenterValueStyle();
  subject.withAnimationMode(PieAnimationMode.values.first);
}

/// Smoke coverage for [PieSliceRadiusConfig]'s 5 generated verb(s).
void _smokePieSliceRadiusConfig(PieSliceRadiusConfig subject) {
  subject.withMinimumFactor(1.0);
  subject.withScale(PieSliceRadiusScale.values.first);
  subject.withLabel('x');
  subject.withUnit('x');
  subject.clearUnit();
}

/// Smoke coverage for [PieChartStyle]'s 31 generated verb(s).
void _smokePieChartStyle(
  PieChartStyle subject,
  Color a0,
  PieGradientStyle a1,
  PieElevationStyle a2,
  PieElevationStyle a3,
) {
  subject.withStartAngleDegrees(1.0);
  subject.withClockwise(true);
  subject.withRadiusFactor(1.0);
  subject.withSliceGap(1.0);
  subject.withBorderWidth(1.0);
  subject.withBorderColor(a0);
  subject.clearBorderColor();
  subject.withBorderColorMode(PieBorderColorMode.values.first);
  subject.clearBorderColorMode();
  subject.withBorderHueShiftDegrees(1.0);
  subject.clearBorderHueShiftDegrees();
  subject.withBorderSaturationShift(1.0);
  subject.clearBorderSaturationShift();
  subject.withBorderLightnessShift(1.0);
  subject.clearBorderLightnessShift();
  subject.withGradient(a1);
  subject.clearGradient();
  subject.withSelectionExplodeOffset(1.0);
  subject.withOpacity(1.0);
  subject.clearOpacity();
  subject.withCornerRadius(1.0);
  subject.clearCornerRadius();
  subject.withCornerTreatment(PieCornerTreatment.values.first);
  subject.clearCornerTreatment();
  subject.withShadow(a2);
  subject.clearShadow();
  subject.withSelectedElevation(a3);
  subject.clearSelectedElevation();
  subject.withAnimationMode(PieAnimationMode.values.first);
  subject.clearAnimationMode();
  subject.withDataTransitionMode(RadialDataTransitionMode.values.first);
}

/// Smoke coverage for [PieDataLabelConfig]'s 20 generated verb(s).
void _smokePieDataLabelConfig(
  PieDataLabelConfig subject,
  LabelStyle a0,
  Color a1,
  LabelStyle a2,
) {
  subject.withVisible(true);
  subject.withPosition(PieDataLabelPosition.values.first);
  subject.withContent(PieDataLabelContent.values.first);
  subject.withSecondaryContent(PieDataLabelContent.values.first);
  subject.clearSecondaryContent();
  subject.withSecondaryPosition(PieDataLabelPosition.values.first);
  subject.withSecondaryCalloutStyle(a0);
  subject.clearSecondaryCalloutStyle();
  subject.withMinimumShare(1.0);
  subject.withMinimumSweepDegrees(1.0);
  subject.withPadding(1.0);
  subject.withInsideOffset(1.0);
  subject.withOutsideOffset(1.0);
  subject.withConnectorLength(1.0);
  subject.withConnectorWidth(1.0);
  subject.withConnectorColor(a1);
  subject.clearConnectorColor();
  subject.withCollisionStrategy(PieDataLabelCollisionStrategy.values.first);
  subject.withCalloutStyle(a2);
  subject.clearCalloutStyle();
}

/// Smoke coverage for [PieChartSeries]'s 16 generated verb(s).
void _smokePieChartSeries(
  PieChartSeries subject,
  List<ChartDataPoint> a0,
  Color a1,
  Map<String, dynamic> a2,
  PieChartStyle a3,
  RadialSelectionStyle a4,
  PieDataLabelConfig a5,
  PieSliceRadiusConfig a6,
  RadialSliceGroupingConfig a7,
) {
  subject.withId('x');
  subject.withName('x');
  subject.withPoints(a0);
  subject.withColor(a1);
  subject.withMetadata(a2);
  subject.withUnit('x');
  subject.withPieStyle(a3);
  subject.updatePieStyle((current) => current);
  subject.withSelectionStyle(a4);
  subject.updateSelectionStyle((current) => current);
  subject.withDataLabels(a5);
  subject.updateDataLabels((current) => current);
  subject.withSliceRadiusConfig(a6);
  subject.clearSliceRadiusConfig();
  subject.withSliceGroupingConfig(a7);
  subject.clearSliceGroupingConfig();
}

/// Smoke coverage for [PolarThreshold]'s 7 generated verb(s).
void _smokePolarThreshold(PolarThreshold subject, Color a0, List<double> a1) {
  subject.withValue(1.0);
  subject.withLabel('x');
  subject.clearLabel();
  subject.withColor(a0);
  subject.clearColor();
  subject.withWidth(1.0);
  subject.withDashPattern(a1);
}

/// Smoke coverage for [PolarColumnCompositionConfig]'s 2 generated verb(s).
void _smokePolarColumnCompositionConfig(PolarColumnCompositionConfig subject) {
  subject.withMode(PolarColumnCompositionMode.values.first);
  subject.withGroupInnerPadding(1.0);
}

/// Smoke coverage for [PolarPaneConfig]'s 6 generated verb(s).
void _smokePolarPaneConfig(PolarPaneConfig subject) {
  subject.withStartAngleDegrees(1.0);
  subject.withSweepAngleDegrees(1.0);
  subject.withClockwise(true);
  subject.withInnerRadiusFactor(1.0);
  subject.withOuterRadiusFactor(1.0);
  subject.withClipMarks(true);
}

/// Smoke coverage for [PolarLabelStyle]'s 6 generated verb(s).
void _smokePolarLabelStyle(PolarLabelStyle subject, Color a0, FontWeight a1) {
  subject.withColor(a0);
  subject.clearColor();
  subject.withFontSize(1.0);
  subject.clearFontSize();
  subject.withFontWeight(a1);
  subject.clearFontWeight();
}

/// Smoke coverage for [PolarCategoryAxisConfig]'s 9 generated verb(s).
void _smokePolarCategoryAxisConfig(
  PolarCategoryAxisConfig subject,
  PolarLabelStyle a0,
) {
  subject.withInnerPadding(1.0);
  subject.withOuterPadding(1.0);
  subject.withShowLabels(true);
  subject.withShowGridLines(true);
  subject.withMaximumVisibleLabels(1);
  subject.withMaximumVisibleGridLines(1);
  subject.withLabelOffset(1.0);
  subject.withLabelStyle(a0);
  subject.updateLabelStyle((current) => current);
}

/// Smoke coverage for [PolarNumericAxisConfig]'s 14 generated verb(s).
void _smokePolarNumericAxisConfig(
  PolarNumericAxisConfig subject,
  PolarLabelStyle a0,
) {
  subject.withMinimum(1.0);
  subject.clearMinimum();
  subject.withMaximum(1.0);
  subject.clearMaximum();
  subject.withScaleMode(PolarRadialScaleMode.values.first);
  subject.clearScaleMode();
  subject.withTickCount(1);
  subject.withShowLabels(true);
  subject.withShowGridLines(true);
  subject.withLabelPosition(PolarRadialLabelPosition.values.first);
  subject.withLabelAngleOffsetDegrees(1.0);
  subject.withLabelOffset(1.0);
  subject.withLabelStyle(a0);
  subject.updateLabelStyle((current) => current);
}

/// Smoke coverage for [PolarChartConfig]'s 9 generated verb(s).
void _smokePolarChartConfig(
  PolarChartConfig subject,
  PolarPaneConfig a0,
  PolarCategoryAxisConfig a1,
  PolarNumericAxisConfig a2,
  PolarColumnCompositionConfig a3,
  List<PolarThreshold> a4,
) {
  subject.withPane(a0);
  subject.updatePane((current) => current);
  subject.withAngularAxis(a1);
  subject.updateAngularAxis((current) => current);
  subject.withRadialAxis(a2);
  subject.updateRadialAxis((current) => current);
  subject.withComposition(a3);
  subject.updateComposition((current) => current);
  subject.withThresholds(a4);
}

/// Smoke coverage for [PolarColumnGradientStyle]'s 7 generated verb(s).
void _smokePolarColumnGradientStyle(
  PolarColumnGradientStyle subject,
  Color a0,
  Color a1,
) {
  subject.withEnabled(true);
  subject.withStartColor(a0);
  subject.clearStartColor();
  subject.withEndColor(a1);
  subject.clearEndColor();
  subject.withStartLightnessShift(1.0);
  subject.withEndLightnessShift(1.0);
}

/// Smoke coverage for [PolarColumnShadowStyle]'s 6 generated verb(s).
void _smokePolarColumnShadowStyle(
  PolarColumnShadowStyle subject,
  Color a0,
  Offset a1,
) {
  subject.withColor(a0);
  subject.clearColor();
  subject.withBlurRadius(1.0);
  subject.withSpreadRadius(1.0);
  subject.withOffset(a1);
  subject.withOpacity(1.0);
}

/// Smoke coverage for [PolarColumnIntervalStyle]'s 7 generated verb(s).
void _smokePolarColumnIntervalStyle(
  PolarColumnIntervalStyle subject,
  Color a0,
) {
  subject.withDisplay(PolarColumnIntervalDisplay.values.first);
  subject.withColor(a0);
  subject.clearColor();
  subject.withWidth(1.0);
  subject.withCapLengthFactor(1.0);
  subject.withBandLengthFactor(1.0);
  subject.withOpacity(1.0);
}

/// Smoke coverage for [PolarColumnTargetMarkerStyle]'s 5 generated verb(s).
void _smokePolarColumnTargetMarkerStyle(
  PolarColumnTargetMarkerStyle subject,
  Color a0,
) {
  subject.withColor(a0);
  subject.clearColor();
  subject.withWidth(1.0);
  subject.withLengthFactor(1.0);
  subject.withOpacity(1.0);
}

/// Smoke coverage for [PolarColumnStyle]'s 16 generated verb(s).
void _smokePolarColumnStyle(
  PolarColumnStyle subject,
  Color a0,
  PolarLabelStyle a1,
  PolarColumnGradientStyle a2,
  PolarColumnShadowStyle a3,
) {
  subject.withCornerRadius(1.0);
  subject.withCornerRadiusMode(PolarColumnCornerRadiusMode.values.first);
  subject.withOpacity(1.0);
  subject.withBorderColor(a0);
  subject.clearBorderColor();
  subject.withBorderWidth(1.0);
  subject.withShowDataLabels(true);
  subject.withMaximumVisibleDataLabels(1);
  subject.withDataLabelRadialPosition(1.0);
  subject.withDataLabelStyle(a1);
  subject.updateDataLabelStyle((current) => current);
  subject.withGradient(a2);
  subject.clearGradient();
  subject.withShadow(a3);
  subject.updateShadow((current) => current);
  subject.withAnimationMode(PolarColumnAnimationMode.values.first);
}

/// Smoke coverage for [PolarColumnChartSeries]'s 14 generated verb(s).
void _smokePolarColumnChartSeries(
  PolarColumnChartSeries subject,
  Color a0,
  Map<String, dynamic> a1,
  PolarColumnStyle a2,
  RadialSelectionStyle a3,
  PolarColumnTargetMarkerStyle a4,
  PolarColumnIntervalStyle a5,
) {
  subject.withId('x');
  subject.withName('x');
  subject.withColor(a0);
  subject.withMetadata(a1);
  subject.withUnit('x');
  subject.withPreset(PolarColumnPreset.values.first);
  subject.withPolarStyle(a2);
  subject.updatePolarStyle((current) => current);
  subject.withSelectionStyle(a3);
  subject.updateSelectionStyle((current) => current);
  subject.withTargetMarkerStyle(a4);
  subject.updateTargetMarkerStyle((current) => current);
  subject.withIntervalStyle(a5);
  subject.updateIntervalStyle((current) => current);
}

/// Smoke coverage for [RadialSliceGroupingConfig]'s 7 generated verb(s).
void _smokeRadialSliceGroupingConfig(
  RadialSliceGroupingConfig subject,
  Color a0,
) {
  subject.withMinimumShare(1.0);
  subject.withMinimumSourceCount(1);
  subject.withLabel('x');
  subject.withColor(a0);
  subject.clearColor();
  subject.withRadiusAggregation(RadialSliceRadiusAggregation.values.first);
  subject.clearRadiusAggregation();
}

/// Smoke coverage for [RadialSelectionStyle]'s 4 generated verb(s).
void _smokeRadialSelectionStyle(RadialSelectionStyle subject) {
  subject.withEffect(RadialSelectionEffect.values.first);
  subject.withLiftScale(1.0);
  subject.withLiftOffset(1.0);
  subject.withBackdropBlur(1.0);
}

/// Smoke coverage for [ScatterMarkerStyle]'s 14 generated verb(s).
void _smokeScatterMarkerStyle(ScatterMarkerStyle subject, Color a0, Color a1) {
  subject.withFillColor(a0);
  subject.clearFillColor();
  subject.withStrokeColor(a1);
  subject.clearStrokeColor();
  subject.withStrokeWidth(1.0);
  subject.clearStrokeWidth();
  subject.withOpacity(1.0);
  subject.clearOpacity();
  subject.withWidth(1.0);
  subject.clearWidth();
  subject.withHeight(1.0);
  subject.clearHeight();
  subject.withRotationDegrees(1.0);
  subject.clearRotationDegrees();
}

/// Smoke coverage for [ScatterInteractionStyle]'s 17 generated verb(s).
void _smokeScatterInteractionStyle(
  ScatterInteractionStyle subject,
  Color a0,
  Color a1,
  Color a2,
  Color a3,
) {
  subject.withHoverColor(a0);
  subject.clearHoverColor();
  subject.withHoverScale(1.0);
  subject.withHoverStrokeWidth(1.0);
  subject.withPressedColor(a1);
  subject.withPressedScale(1.0);
  subject.withPressedOpacity(1.0);
  subject.withSelectionColor(a2);
  subject.clearSelectionColor();
  subject.withSelectionScale(1.0);
  subject.withSelectionOpacity(1.0);
  subject.withSelectionStrokeWidth(1.0);
  subject.withFocusColor(a3);
  subject.clearFocusColor();
  subject.withFocusGap(1.0);
  subject.withFocusStrokeWidth(1.0);
  subject.withDimmedOpacity(1.0);
}

/// Smoke coverage for [SegmentStyle]'s 6 generated verb(s).
void _smokeSegmentStyle(SegmentStyle subject, Color a0, List<double> a1) {
  subject.withColor(a0);
  subject.clearColor();
  subject.withStrokeWidth(1.0);
  subject.clearStrokeWidth();
  subject.withDashPattern(a1);
  subject.clearDashPattern();
}

/// Smoke coverage for [PointStyle]'s 8 generated verb(s).
void _smokePointStyle(PointStyle subject, Color a0, ScatterMarkerStyle a1) {
  subject.withColor(a0);
  subject.clearColor();
  subject.withSize(1.0);
  subject.clearSize();
  subject.withScatterMarkerShape(SeriesMarkerShape.values.first);
  subject.clearScatterMarkerShape();
  subject.withScatterMarkerStyle(a1);
  subject.clearScatterMarkerStyle();
}

/// Smoke coverage for [SeriesLabelBackground]'s 5 generated verb(s).
void _smokeSeriesLabelBackground(
  SeriesLabelBackground subject,
  Color a0,
  EdgeInsets a1,
  Color a2,
) {
  subject.withColor(a0);
  subject.withCornerRadius(1.0);
  subject.withPadding(a1);
  subject.withBorderColor(a2);
  subject.withBorderWidth(1.0);
}

/// Smoke coverage for [SeriesInlineLabelConfig]'s 7 generated verb(s).
void _smokeSeriesInlineLabelConfig(
  SeriesInlineLabelConfig subject,
  Color a0,
  FontWeight a1,
  SeriesLabelBackground a2,
) {
  subject.withText('x');
  subject.withPosition(SeriesLabelPosition.values.first);
  subject.withOffsetY(1.0);
  subject.withColor(a0);
  subject.withFontSize(1.0);
  subject.withFontWeight(a1);
  subject.withBackground(a2);
}

/// Smoke coverage for [StreamingConfig]'s 4 generated verb(s).
void _smokeStreamingConfig(StreamingConfig subject) {
  subject.withMaxBufferSize(1);
  subject.withAutoScroll(true);
  subject.withAutoScrollWindowSize(1);
  subject.withResumeAnimationDuration(const Duration(milliseconds: 1));
}

/// Smoke coverage for [XAxisConfig]'s 23 generated verb(s).
void _smokeXAxisConfig(XAxisConfig subject, Color a0, CategoryAxisConfig a1) {
  subject.withColor(a0);
  subject.withLabel('x');
  subject.withUnit('x');
  subject.withRenderMin(1.0);
  subject.withRenderMax(1.0);
  subject.withVisible(true);
  subject.withShowAxisLine(true);
  subject.withShowTicks(true);
  subject.withShowTickLabels(true);
  subject.withShowCrosshairLabel(true);
  subject.withCrosshairLabelPosition(CrosshairLabelPosition.values.first);
  subject.withLabelDisplay(AxisLabelDisplay.values.first);
  subject.withTickLabelPadding(1.0);
  subject.withAxisLabelPadding(1.0);
  subject.withAxisMargin(1.0);
  subject.withTickCount(1);
  subject.withCategoryAxis(a1);
  subject.clearCategoryAxis();
  subject.withShowMinorTicks(true);
  subject.withMinorTickCount(1);
  subject.withMinorTickLength(1.0);
  subject.withRange(1.0, 1.0);
  subject.withHeightBounds(1.0, 1.0);
}

/// Smoke coverage for [YAxisConfig]'s 22 generated verb(s).
void _smokeYAxisConfig(YAxisConfig subject, Color a0) {
  subject.withPosition(YAxisPosition.values.first);
  subject.withColor(a0);
  subject.withLabel('x');
  subject.withUnit('x');
  subject.withRenderMin(1.0);
  subject.withRenderMax(1.0);
  subject.withVisible(true);
  subject.withShowAxisLine(true);
  subject.withShowTicks(true);
  subject.withShowTickLabels(true);
  subject.withShowCrosshairLabel(true);
  subject.withCrosshairLabelPosition(CrosshairLabelPosition.values.first);
  subject.withLabelDisplay(AxisLabelDisplay.values.first);
  subject.withTickLabelPadding(1.0);
  subject.withAxisLabelPadding(1.0);
  subject.withAxisMargin(1.0);
  subject.withTickCount(1);
  subject.withShowMinorTicks(true);
  subject.withMinorTickCount(1);
  subject.withMinorTickLength(1.0);
  subject.withRange(1.0, 1.0);
  subject.withWidthBounds(1.0, 1.0);
}

/// Smoke coverage for [ChartDataTableTheme]'s 15 generated verb(s).
void _smokeChartDataTableTheme(
  ChartDataTableTheme subject,
  Color a0,
  Color a1,
  Color a2,
  Color a3,
  Color a4,
  Color a5,
  TextStyle a6,
  TextStyle a7,
  TextStyle a8,
) {
  subject.withRowHeight(1.0);
  subject.withHeaderHeight(1.0);
  subject.withRowNumberWidth(1.0);
  subject.withXColumnWidth(1.0);
  subject.withSeriesColumnWidth(1.0);
  subject.withCellHorizontalPadding(1.0);
  subject.withHeaderBackgroundColor(a0);
  subject.withEvenRowColor(a1);
  subject.withOddRowColor(a2);
  subject.withDividerColor(a3);
  subject.withFocusedRowColor(a4);
  subject.withSelectedRowColor(a5);
  subject.withHeaderTextStyle(a6);
  subject.withCellTextStyle(a7);
  subject.withRowNumberTextStyle(a8);
}

/// Smoke coverage for [AnimationTheme]'s 6 generated verb(s).
void _smokeAnimationTheme(
  AnimationTheme subject,
  Curve a0,
  Curve a1,
  Curve a2,
) {
  subject.withDataUpdateDuration(const Duration(milliseconds: 1));
  subject.withDataUpdateCurve(a0);
  subject.withThemeChangeDuration(const Duration(milliseconds: 1));
  subject.withThemeChangeCurve(a1);
  subject.withInteractionDuration(const Duration(milliseconds: 1));
  subject.withInteractionCurve(a2);
}

/// Smoke coverage for [AnnotationTheme]'s 10 generated verb(s).
void _smokeAnnotationTheme(
  AnnotationTheme subject,
  PointAnnotationDefaults a0,
  RangeAnnotationDefaults a1,
  TextAnnotationDefaults a2,
  ThresholdAnnotationDefaults a3,
  TrendAnnotationDefaults a4,
) {
  subject.withPointDefaults(a0);
  subject.updatePointDefaults((current) => current);
  subject.withRangeDefaults(a1);
  subject.updateRangeDefaults((current) => current);
  subject.withTextDefaults(a2);
  subject.updateTextDefaults((current) => current);
  subject.withThresholdDefaults(a3);
  subject.updateThresholdDefaults((current) => current);
  subject.withTrendDefaults(a4);
  subject.updateTrendDefaults((current) => current);
}

/// Smoke coverage for [PointAnnotationDefaults]'s 11 generated verb(s).
void _smokePointAnnotationDefaults(
  PointAnnotationDefaults subject,
  Color a0,
  Color a1,
  Color a2,
  Color a3,
  LabelStyle a4,
) {
  subject.withMarkerShape(SeriesMarkerShape.values.first);
  subject.withMarkerSize(1.0);
  subject.withNormalColor(a0);
  subject.withSelectedColor(a1);
  subject.withHoveredColor(a2);
  subject.withDraggingColor(a3);
  subject.withGhostOpacity(1.0);
  subject.withPreviewOpacity(1.0);
  subject.withPreviewScale(1.0);
  subject.withLabelStyle(a4);
  subject.updateLabelStyle((current) => current);
}

/// Smoke coverage for [RangeAnnotationDefaults]'s 11 generated verb(s).
void _smokeRangeAnnotationDefaults(
  RangeAnnotationDefaults subject,
  Color a0,
  Color a1,
  Color a2,
  Color a3,
  Color a4,
  Color a5,
  Color a6,
  Color a7,
  LabelStyle a8,
) {
  subject.withNormalFillColor(a0);
  subject.withSelectedFillColor(a1);
  subject.withHoveredFillColor(a2);
  subject.withDraggingFillColor(a3);
  subject.withNormalBorderColor(a4);
  subject.withSelectedBorderColor(a5);
  subject.withHoveredBorderColor(a6);
  subject.withDraggingBorderColor(a7);
  subject.withBorderWidth(1.0);
  subject.withLabelStyle(a8);
  subject.updateLabelStyle((current) => current);
}

/// Smoke coverage for [TextAnnotationDefaults]'s 6 generated verb(s).
void _smokeTextAnnotationDefaults(
  TextAnnotationDefaults subject,
  TextStyle a0,
  Color a1,
  Color a2,
  EdgeInsets a3,
) {
  subject.withTextStyle(a0);
  subject.withBackgroundColor(a1);
  subject.withBorderColor(a2);
  subject.withBorderWidth(1.0);
  subject.withBorderRadius(1.0);
  subject.withPadding(a3);
}

/// Smoke coverage for [ThresholdAnnotationDefaults]'s 5 generated verb(s).
void _smokeThresholdAnnotationDefaults(
  ThresholdAnnotationDefaults subject,
  Color a0,
  List<double> a1,
  LabelStyle a2,
) {
  subject.withLineColor(a0);
  subject.withLineWidth(1.0);
  subject.withDashPattern(a1);
  subject.withLabelStyle(a2);
  subject.updateLabelStyle((current) => current);
}

/// Smoke coverage for [TrendAnnotationDefaults]'s 7 generated verb(s).
void _smokeTrendAnnotationDefaults(
  TrendAnnotationDefaults subject,
  Color a0,
  List<double> a1,
  Color a2,
  LabelStyle a3,
) {
  subject.withLineColor(a0);
  subject.withLineWidth(1.0);
  subject.withDashPattern(a1);
  subject.withConfidenceBandColor(a2);
  subject.withConfidenceBandOpacity(1.0);
  subject.withLabelStyle(a3);
  subject.updateLabelStyle((current) => current);
}

/// Smoke coverage for [AxisStyle]'s 8 generated verb(s).
void _smokeAxisStyle(
  AxisStyle subject,
  Color a0,
  TextStyle a1,
  TextStyle a2,
  Color a3,
) {
  subject.withLineColor(a0);
  subject.withLineWidth(1.0);
  subject.withLabelStyle(a1);
  subject.withTitleStyle(a2);
  subject.withShowTicks(true);
  subject.withTickLength(1.0);
  subject.withTickColor(a3);
  subject.withTickWidth(1.0);
}

/// Smoke coverage for [CandlestickTheme]'s 11 generated verb(s).
void _smokeCandlestickTheme(
  CandlestickTheme subject,
  Color a0,
  Color a1,
  Color a2,
  Color a3,
  Color a4,
  Color a5,
  Color a6,
  Color a7,
  Color a8,
  Color a9,
  Color a10,
) {
  subject.withRisingBodyFillColor(a0);
  subject.withFallingBodyFillColor(a1);
  subject.withDojiBodyFillColor(a2);
  subject.withRisingBorderColor(a3);
  subject.withFallingBorderColor(a4);
  subject.withDojiBorderColor(a5);
  subject.withRisingWickColor(a6);
  subject.withFallingWickColor(a7);
  subject.withDojiWickColor(a8);
  subject.withSelectionColor(a9);
  subject.withFocusColor(a10);
}

/// Smoke coverage for [CartesianValueSummaryTheme]'s 15 generated verb(s).
void _smokeCartesianValueSummaryTheme(
  CartesianValueSummaryTheme subject,
  Color a0,
  Color a1,
  BorderRadius a2,
  EdgeInsets a3,
  TextStyle a4,
  TextStyle a5,
  TextStyle a6,
  BoxShadow a7,
) {
  subject.withBackground(a0);
  subject.withBackgroundOpacity(1.0);
  subject.withBorder(a1);
  subject.withBorderWidth(1.0);
  subject.withBorderRadius(a2);
  subject.withPadding(a3);
  subject.withTitleStyle(a4);
  subject.withLabelStyle(a5);
  subject.withValueStyle(a6);
  subject.withAccentSize(1.0);
  subject.withShadow(a7);
  subject.withMinWidth(1.0);
  subject.withMaxWidth(1.0);
  subject.withRowGap(1.0);
  subject.withLabelValueGap(1.0);
}

/// Smoke coverage for [GridStyle]'s 5 generated verb(s).
void _smokeGridStyle(
  GridStyle subject,
  Color a0,
  List<double> a1,
  List<double> a2,
  Color a3,
) {
  subject.withMajorColor(a0);
  subject.withMajorWidth(1.0);
  subject.withMajorDashPattern(a1);
  subject.withMinorDashPattern(a2);
  subject.withMinorGrid(true, a3, 1.0);
}

/// Smoke coverage for [InteractionTheme]'s 8 generated verb(s).
void _smokeInteractionTheme(
  InteractionTheme subject,
  Color a0,
  List<double> a1,
  LabelStyle a2,
  LabelStyle a3,
  Color a4,
) {
  subject.withCrosshairColor(a0);
  subject.withCrosshairWidth(1.0);
  subject.withCrosshairDashPattern(a1);
  subject.withCrosshairLabelStyle(a2);
  subject.updateCrosshairLabelStyle((current) => current);
  subject.withTooltipStyle(a3);
  subject.updateTooltipStyle((current) => current);
  subject.withSelectionColor(a4);
}

/// Smoke coverage for [ScrollbarConfig]'s 23 generated verb(s).
void _smokeScrollbarConfig(
  ScrollbarConfig subject,
  Color a0,
  Color a1,
  Color a2,
  Color a3,
  Color a4,
  Color a5,
  Color a6,
  Color a7,
  Color a8,
) {
  subject.withThickness(1.0);
  subject.withMinHandleSize(1.0);
  subject.withTrackColor(a0);
  subject.withHandleColor(a1);
  subject.withHandleHoverColor(a2);
  subject.withEdgeZoneColor(a3);
  subject.withEdgeHoverColor(a4);
  subject.withHandleActiveColor(a5);
  subject.withHandleDisabledColor(a6);
  subject.withBorderRadius(1.0);
  subject.withEdgeGripWidth(1.0);
  subject.withShowGripIndicator(true);
  subject.withGripIndicatorColor(a7);
  subject.withAutoHide(true);
  subject.withAutoHideDelay(const Duration(milliseconds: 1));
  subject.withFadeDuration(const Duration(milliseconds: 1));
  subject.withEnableResizeHandles(true);
  subject.withMinZoomRatio(1.0);
  subject.withMaxZoomRatio(1.0);
  subject.withPadding(1.0);
  subject.withTrackHoverColor(a8);
  subject.withForcedColorsMode(true);
  subject.withPrefersReducedMotion(true);
}

/// Smoke coverage for [SeriesTheme]'s 4 generated verb(s).
void _smokeSeriesTheme(
  SeriesTheme subject,
  List<Color> a0,
  List<double> a1,
  List<double> a2,
  List<SeriesMarkerShape> a3,
) {
  subject.withColors(a0);
  subject.withLineWidths(a1);
  subject.withMarkerSizes(a2);
  subject.withMarkerShapes(a3);
}

/// Smoke coverage for [TypographyTheme]'s 7 generated verb(s).
void _smokeTypographyTheme(TypographyTheme subject) {
  subject.withFontFamily('x');
  subject.withBaseFontSize(1.0);
  subject.withScaleFactorMobile(1.0);
  subject.withScaleFactorTablet(1.0);
  subject.withScaleFactorDesktop(1.0);
  subject.withTitleMultiplier(1.0);
  subject.withLabelMultiplier(1.0);
}

/// Smoke coverage for [LabelStyle]'s 8 generated verb(s).
void _smokeLabelStyle(
  LabelStyle subject,
  TextStyle a0,
  Color a1,
  Color a2,
  EdgeInsets a3,
  Color a4,
) {
  subject.withTextStyle(a0);
  subject.withBackgroundColor(a1);
  subject.withBorderColor(a2);
  subject.withBorderWidth(1.0);
  subject.withBorderRadius(1.0);
  subject.withPadding(a3);
  subject.withShadowColor(a4);
  subject.withShadowBlurRadius(1.0);
}

/// Every generated smoke case, referenced so none of them is dead code.
const List<Function> _cases = <Function>[
  _smokeAnnotationStyle,
  _smokeAutoScrollConfig,
  _smokeCandlestickChartSeries,
  _smokeCandlestickDataPoint,
  _smokeCandlestickDensityGrouping,
  _smokeCartesianValueSummaryOverlay,
  _smokeCartesianValueSummaryAnnotation,
  _smokeCartesianValueSummaryAutomaticContent,
  _smokeCartesianValueSummaryConfig,
  _smokeCartesianValueSummaryStyle,
  _smokeCategoryAxisConfig,
  _smokePointAnnotation,
  _smokeRangeAnnotation,
  _smokeTextAnnotation,
  _smokeThresholdAnnotation,
  _smokePinAnnotation,
  _smokeTrendAnnotation,
  _smokeErrorBarAnnotation,
  _smokeChordAnnotation,
  _smokeLegendAnnotation,
  _smokeChartDataPoint,
  _smokeChartOverlayPlacement,
  _smokeLineChartSeries,
  _smokeScatterChartSeries,
  _smokeAreaChartSeries,
  _smokeBarChartSeries,
  _smokeChartTheme,
  _smokeConcentricDonutConfig,
  _smokeDataPointLabelConfig,
  _smokeDonutCenterContent,
  _smokeDonutChartStyle,
  _smokeDonutChartSeries,
  _smokeGridConfig,
  _smokeCrosshairStyle,
  _smokeCrosshairConfig,
  _smokeTooltipStyle,
  _smokeTooltipConfig,
  _smokeGestureConfig,
  _smokeKeyboardConfig,
  _smokeChartSelectionConfig,
  _smokeInteractionConfig,
  _smokeLegendStyle,
  _smokeMultiAxisConfig,
  _smokePathAnimationTiming,
  _smokePathAnimationStyle,
  _smokePieGradientStyle,
  _smokePieElevationStyle,
  _smokePieChartTheme,
  _smokePieSliceRadiusConfig,
  _smokePieChartStyle,
  _smokePieDataLabelConfig,
  _smokePieChartSeries,
  _smokePolarThreshold,
  _smokePolarColumnCompositionConfig,
  _smokePolarPaneConfig,
  _smokePolarLabelStyle,
  _smokePolarCategoryAxisConfig,
  _smokePolarNumericAxisConfig,
  _smokePolarChartConfig,
  _smokePolarColumnGradientStyle,
  _smokePolarColumnShadowStyle,
  _smokePolarColumnIntervalStyle,
  _smokePolarColumnTargetMarkerStyle,
  _smokePolarColumnStyle,
  _smokePolarColumnChartSeries,
  _smokeRadialSliceGroupingConfig,
  _smokeRadialSelectionStyle,
  _smokeScatterMarkerStyle,
  _smokeScatterInteractionStyle,
  _smokeSegmentStyle,
  _smokePointStyle,
  _smokeSeriesLabelBackground,
  _smokeSeriesInlineLabelConfig,
  _smokeStreamingConfig,
  _smokeXAxisConfig,
  _smokeYAxisConfig,
  _smokeChartDataTableTheme,
  _smokeAnimationTheme,
  _smokeAnnotationTheme,
  _smokePointAnnotationDefaults,
  _smokeRangeAnnotationDefaults,
  _smokeTextAnnotationDefaults,
  _smokeThresholdAnnotationDefaults,
  _smokeTrendAnnotationDefaults,
  _smokeAxisStyle,
  _smokeCandlestickTheme,
  _smokeCartesianValueSummaryTheme,
  _smokeGridStyle,
  _smokeInteractionTheme,
  _smokeScrollbarConfig,
  _smokeSeriesTheme,
  _smokeTypographyTheme,
  _smokeLabelStyle,
];

void main() {
  test('every generated fluent verb type-checks against its owner', () {
    // Reaching this line means the 93 generated cases above compiled.
    expect(_cases, hasLength(93));
  });
}
