import 'package:equatable/equatable.dart';

import 'annotation_config.dart';
import 'chart_style_config.dart';
import 'enums.dart';
import 'series_config.dart';
import 'x_axis_config.dart';
import 'y_axis_config.dart';

/// Root configuration for a complete chart specification.
///
/// Aggregates all chart components including series data, axes,
/// annotations, and styling. This is the top-level model that
/// represents a fully configured chart.
///
/// The [id] field is optional and auto-generated by the tool layer
/// when creating new charts. The [type] and [series] fields are required.
///
/// Uses [EquatableMixin] for value equality comparisons.
///
/// ## Example
///
/// ```dart
/// final chart = ChartConfiguration(
///   type: ChartType.line,
///   title: 'Temperature Over Time',
///   series: [
///     SeriesConfig(
///       id: 'temp',
///       data: [DataPoint(x: 0, y: 20), DataPoint(x: 1, y: 22)],
///     ),
///   ],
///   xAxis: XAxisConfig(label: 'Time', unit: 'hours'),
///   showLegend: true,
///   legendPosition: LegendPosition.bottom,
/// );
/// ```
///
/// ## JSON Serialization
///
/// ```dart
/// final json = chart.toJson();
/// final restored = ChartConfiguration.fromJson(json);
/// ```
class ChartConfiguration with EquatableMixin {
  /// Unique identifier for this chart configuration.
  ///
  /// Optional - auto-generated by the tool layer (CreateChartTool)
  /// using UUID when creating new charts. May be null for new charts
  /// or present for existing charts being updated.
  final String? id;

  /// The type of chart to render.
  final ChartType type;

  /// Title displayed at the top of the chart.
  final String? title;

  /// Subtitle displayed below the title.
  final String? subtitle;

  /// The data series to plot on the chart.
  ///
  /// At least one series is typically required for a meaningful chart.
  final List<SeriesConfig> series;

  /// Configuration for the X-axis.
  final XAxisConfig? xAxis;

  /// Configurations for Y-axes.
  ///
  /// Supports 0-4 Y-axes for multi-axis charts.
  /// Empty list means use default Y-axis behavior.
  final List<YAxisConfig> yAxes;

  /// Annotations to display on the chart.
  ///
  /// Includes reference lines, zones, text labels, and markers.
  final List<AnnotationConfig> annotations;

  /// Visual styling configuration.
  final ChartStyleConfig? style;

  /// Interaction configuration for pan, zoom, crosshair, and tooltip.
  ///
  /// When provided as a Map, supports:
  /// - `pan`: bool - Enable panning (default: true)
  /// - `zoom`: bool - Enable zooming (default: true)
  /// - `crosshair`: bool - Show crosshair on hover (default: true)
  /// - `tooltip`: bool - Show tooltip on hover (default: true)
  /// - `scrollbar`: Map with `enabled` key for scrollbar
  final Map<String, dynamic>? interactions;

  /// Whether to show grid lines on the chart.
  final bool showGrid;

  /// Whether to show the chart legend.
  final bool showLegend;

  /// Position of the legend relative to the chart area.
  final LegendPosition legendPosition;

  /// Whether to use dark theme colors.
  final bool useDarkTheme;

  /// Whether to show a scrollbar for panning.
  final bool showScrollbar;

  /// Normalization mode for multi-series charts.
  final NormalizationModeConfig normalizationMode;

  /// Width of the chart in pixels.
  final double? width;

  /// Height of the chart in pixels.
  final double? height;

  /// Background color of the chart (hex string like '#FFFFFF').
  final String? backgroundColor;

  /// Creates a [ChartConfiguration] with the given parameters.
  ///
  /// [type] and [series] are required. [id] is optional and typically
  /// auto-generated by the tool layer.
  const ChartConfiguration({
    this.id,
    required this.type,
    this.title,
    this.subtitle,
    required this.series,
    this.xAxis,
    this.yAxes = const [],
    this.annotations = const [],
    this.style,
    this.interactions,
    this.showGrid = true,
    this.showLegend = true,
    this.legendPosition = LegendPosition.bottom,
    this.useDarkTheme = false,
    this.showScrollbar = false,
    this.normalizationMode = NormalizationModeConfig.none,
    this.width,
    this.height,
    this.backgroundColor,
  });

  /// Creates a [ChartConfiguration] from a JSON map.
  ///
  /// Parses all nested models including series, axes, annotations, and style.
  /// Enum values are parsed using .byName() with sensible defaults.
  factory ChartConfiguration.fromJson(Map<String, dynamic> json) {
    return ChartConfiguration(
      id: json['id'] as String?,
      type: ChartType.values.byName(json['type'] as String? ?? 'line'),
      title: json['title'] as String?,
      subtitle: json['subtitle'] as String?,
      series: (json['series'] as List<dynamic>?)
              ?.map((e) => SeriesConfig.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      xAxis: json['xAxis'] != null
          ? XAxisConfig.fromJson(json['xAxis'] as Map<String, dynamic>)
          : null,
      yAxes: (json['yAxes'] as List<dynamic>?)
              ?.map((e) => YAxisConfig.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      annotations: (json['annotations'] as List<dynamic>?)
              ?.map((e) => AnnotationConfig.fromJson(e as Map<String, dynamic>))
              .toList() ??
          [],
      style: json['style'] != null
          ? ChartStyleConfig.fromJson(json['style'] as Map<String, dynamic>)
          : null,
      interactions: json['interactions'] as Map<String, dynamic>?,
      showGrid: json['showGrid'] as bool? ?? true,
      showLegend: json['showLegend'] as bool? ?? true,
      legendPosition: LegendPosition.values
          .byName(json['legendPosition'] as String? ?? 'bottom'),
      useDarkTheme: json['useDarkTheme'] as bool? ?? false,
      showScrollbar: json['showScrollbar'] as bool? ?? false,
      normalizationMode: NormalizationModeConfig.values
          .byName(json['normalizationMode'] as String? ?? 'none'),
      width: (json['width'] as num?)?.toDouble(),
      height: (json['height'] as num?)?.toDouble(),
      backgroundColor: json['backgroundColor'] as String?,
    );
  }

  /// Converts this [ChartConfiguration] to a JSON map.
  ///
  /// Includes all properties. Nested models call their .toJson() methods.
  /// Enum values are serialized as their names.
  Map<String, dynamic> toJson() {
    return {
      if (id != null) 'id': id,
      'type': type.name,
      if (title != null) 'title': title,
      if (subtitle != null) 'subtitle': subtitle,
      'series': series.map((e) => e.toJson()).toList(),
      if (xAxis != null) 'xAxis': xAxis!.toJson(),
      'yAxes': yAxes.map((e) => e.toJson()).toList(),
      'annotations': annotations.map((e) => e.toJson()).toList(),
      if (style != null) 'style': style!.toJson(),
      if (interactions != null) 'interactions': interactions,
      'showGrid': showGrid,
      'showLegend': showLegend,
      'legendPosition': legendPosition.name,
      'useDarkTheme': useDarkTheme,
      'showScrollbar': showScrollbar,
      'normalizationMode': normalizationMode.name,
      if (width != null) 'width': width,
      if (height != null) 'height': height,
      if (backgroundColor != null) 'backgroundColor': backgroundColor,
    };
  }

  /// Creates a copy of this [ChartConfiguration] with optionally overridden values.
  ///
  /// If a parameter is not provided, the original value is preserved.
  ChartConfiguration copyWith({
    String? id,
    ChartType? type,
    String? title,
    String? subtitle,
    List<SeriesConfig>? series,
    XAxisConfig? xAxis,
    List<YAxisConfig>? yAxes,
    List<AnnotationConfig>? annotations,
    ChartStyleConfig? style,
    Map<String, dynamic>? interactions,
    bool? showGrid,
    bool? showLegend,
    LegendPosition? legendPosition,
    bool? useDarkTheme,
    bool? showScrollbar,
    NormalizationModeConfig? normalizationMode,
    double? width,
    double? height,
    String? backgroundColor,
  }) {
    return ChartConfiguration(
      id: id ?? this.id,
      type: type ?? this.type,
      title: title ?? this.title,
      subtitle: subtitle ?? this.subtitle,
      series: series ?? this.series,
      xAxis: xAxis ?? this.xAxis,
      yAxes: yAxes ?? this.yAxes,
      annotations: annotations ?? this.annotations,
      style: style ?? this.style,
      interactions: interactions ?? this.interactions,
      showGrid: showGrid ?? this.showGrid,
      showLegend: showLegend ?? this.showLegend,
      legendPosition: legendPosition ?? this.legendPosition,
      useDarkTheme: useDarkTheme ?? this.useDarkTheme,
      showScrollbar: showScrollbar ?? this.showScrollbar,
      normalizationMode: normalizationMode ?? this.normalizationMode,
      width: width ?? this.width,
      height: height ?? this.height,
      backgroundColor: backgroundColor ?? this.backgroundColor,
    );
  }

  @override
  List<Object?> get props => [
        id,
        type,
        title,
        subtitle,
        series,
        xAxis,
        yAxes,
        annotations,
        style,
        interactions,
        showGrid,
        showLegend,
        legendPosition,
        useDarkTheme,
        showScrollbar,
        normalizationMode,
        width,
        height,
        backgroundColor,
      ];

  @override
  String toString() =>
      'ChartConfiguration(id: $id, type: $type, title: $title, series: ${series.length} series)';
}
