include: package:flutter_lints/flutter.yaml

# Additional lint rules for the example app
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
