// Copyright (c) 2025 braven_charts. All rights reserved.
// Streaming Manager - Extracted from ChartRenderBox

import 'dart:ui';

import 'package:flutter/scheduler.dart';

import '../../coordinates/chart_transform.dart';
import '../../elements/series_element.dart';
import '../../models/chart_series.dart';
import '../../streaming/streaming_buffer.dart';
import '../../utils/data_converter.dart';

/// Re-export DataBounds for convenience
export '../../utils/data_converter.dart' show DataBounds;

/// Delegate interface for StreamingManager to interact with ChartRenderBox.
///
/// This abstraction allows StreamingManager to:
/// - Read and modify viewport transforms
/// - Apply pan constraints for pause mode
/// - Trigger repaints
/// - Access series configuration for rendering
abstract interface class StreamingDelegate {
  /// Current viewport transform (may be null during initialization).
  ChartTransform? get transform;
  set transform(ChartTransform? value);

  /// Original data bounds transform (for scrollbar handle sizing).
  ChartTransform? get originalTransform;
  set originalTransform(ChartTransform? value);

  /// Data series for styling lookup during rendering.
  List<ChartSeries> get series;

  /// Update axes from the current transform.
  void updateAxesFromTransform();

  /// Request a repaint.
  void markNeedsPaint();

  /// Invalidate the series cache (data changed).
  void invalidateSeriesCache();

  /// Set pan constraint bounds for pause mode.
  void setPanConstraintBounds(double xMin, double xMax, double yMin, double yMax);

  /// Clear pan constraint bounds when resuming streaming.
  void clearPanConstraintBounds();
}

/// Manages all streaming data state and viewport animations.
///
/// This module encapsulates:
/// - Streaming buffer storage (zero-copy references)
/// - Auto-scroll animation (smooth viewport following)
/// - Viewport expansion animation (grow to show all data)
/// - Pause/resume viewport locking
/// - Direct buffer rendering for performance
///
/// The module uses a delegate pattern to interact with ChartRenderBox,
/// allowing clean separation of concerns while enabling transform updates.
class StreamingManager {
  StreamingManager({
    required StreamingDelegate delegate,
  }) : _delegate = delegate;

  // ==========================================================================
  // Dependencies
  // ==========================================================================

  final StreamingDelegate _delegate;

  // ==========================================================================
  // Streaming State
  // ==========================================================================

  /// Streaming buffer references, keyed by series ID.
  ///
  /// This holds references to StreamingBuffers from LiveStreamController,
  /// separate from the static elements generated by widget.series.
  /// During paint, streaming data is rendered as an additional layer.
  ///
  /// PERFORMANCE: We store buffer references, not copies. This eliminates
  /// O(n) list copying on every frame.
  final Map<String, StreamingBuffer> _streamingBuffers = {};

  /// Cached streaming series elements (legacy, may be removed).
  final Map<String, SeriesElement> _streamingElements = {};

  /// Bounds of all streaming data, used for viewport snapping.
  DataBounds? _streamingBounds;

  // ==========================================================================
  // Viewport State
  // ==========================================================================

  /// Whether the viewport is locked for pause mode.
  ///
  /// When true, auto-scroll is disabled and user can pan through historical data.
  bool _viewportLockedForPause = false;

  /// Target viewport X position for smooth auto-scrolling.
  /// When non-null, the viewport animates toward this target.
  double? _autoScrollTargetXMax;

  /// Target viewport width for auto-scrolling.
  /// When set, maintains consistent zoom level during streaming.
  double? _autoScrollTargetWidth;

  /// Whether an animation frame is already scheduled.
  bool _autoScrollAnimationScheduled = false;

  /// Target Y bounds for viewport expansion animation.
  double? _expansionTargetYMin;
  double? _expansionTargetYMax;

  // ==========================================================================
  // Public Getters
  // ==========================================================================

  /// Whether any streaming buffers exist.
  bool get hasStreamingData => _streamingBuffers.isNotEmpty;

  /// Current streaming bounds (for external access).
  DataBounds? get streamingBounds => _streamingBounds;

  /// Whether viewport is locked for pause mode.
  bool get isViewportLocked => _viewportLockedForPause;

  /// Streaming buffers for painting (read-only access).
  Map<String, StreamingBuffer> get buffers => _streamingBuffers;

  // ==========================================================================
  // Lifecycle
  // ==========================================================================

  /// Disposes of resources when the manager is no longer needed.
  void dispose() {
    // Cancel any pending animations
    _autoScrollAnimationScheduled = false;
    _autoScrollTargetXMax = null;
    _autoScrollTargetWidth = null;
    _expansionTargetYMin = null;
    _expansionTargetYMax = null;

    // Clear all streaming state
    _streamingBuffers.clear();
    _streamingElements.clear();
    _streamingBounds = null;
    _viewportLockedForPause = false;
  }

  // ==========================================================================
  // Streaming Data Management
  // ==========================================================================

  /// Sets streaming data for a specific series.
  ///
  /// Called by LiveStreamController on each frame to update the chart
  /// with new streaming data. This bypasses widget rebuild entirely.
  ///
  /// **Parameters**:
  /// - [seriesId]: ID of the series to update
  /// - [buffer]: Reference to the StreamingBuffer (zero-copy!)
  /// - [expandViewportWhenNotAutoScrolling]: If true, expand viewport to show all data
  /// - [maxVisiblePoints]: Maximum points before switching to sliding window
  ///
  /// **Performance**: O(1) for data storage, O(visible points) for rendering.
  void setStreamingData({
    required String seriesId,
    required StreamingBuffer buffer,
    bool expandViewportWhenNotAutoScrolling = false,
    int maxVisiblePoints = 10000,
  }) {
    // Store buffer reference (zero-copy!)
    _streamingBuffers[seriesId] = buffer;

    // Get bounds from buffer (O(1) typically)
    final bounds = buffer.bounds;
    _streamingBounds = bounds;

    // CRITICAL: Ensure bounds have valid range (dataXMax > dataXMin).
    // When buffer has single point or all points have same X, add epsilon.
    const epsilon = 0.001;
    final xMin = bounds.xMin;
    final xMax = bounds.xMax <= bounds.xMin ? bounds.xMin + epsilon : bounds.xMax;
    final yMin = bounds.yMin;
    final yMax = bounds.yMax <= bounds.yMin ? bounds.yMin + epsilon : bounds.yMax;

    // CRITICAL: Update _originalTransform to include FULL streaming data range.
    // This enables:
    // 1. Correct scrollbar handle sizing (shows proportion of visible vs total data)
    // 2. Correct pan constraints (user can scroll back to see all history)
    final originalTransform = _delegate.originalTransform;
    if (originalTransform != null && buffer.isNotEmpty) {
      final yPadding = (yMax - yMin) * 0.05;

      // DEFENSIVE: If existing transform has invalid bounds, recreate it entirely
      if (originalTransform.dataXMax <= originalTransform.dataXMin || originalTransform.dataYMax <= originalTransform.dataYMin) {
        _delegate.originalTransform = ChartTransform(
          dataXMin: xMin,
          dataXMax: xMax,
          dataYMin: yMin - yPadding,
          dataYMax: yMax + yPadding,
          plotWidth: originalTransform.plotWidth,
          plotHeight: originalTransform.plotHeight,
          invertY: originalTransform.invertY,
        );
      } else {
        // Expand original transform to encompass full streaming data range
        _delegate.originalTransform = originalTransform.copyWith(
          dataXMin: xMin,
          dataXMax: xMax,
          dataYMin: yMin - yPadding,
          dataYMax: yMax + yPadding,
        );
      }
    }

    // Update viewport transform based on auto-scroll mode
    final transform = _delegate.transform;
    if (transform != null && buffer.isNotEmpty) {
      // Check if we're in initial state (default 0-1 bounds from empty series)
      final isInitialState = transform.dataXMin == 0 && transform.dataXMax == 1 && transform.dataYMin == 0 && transform.dataYMax == 1;

      // Calculate Y bounds with padding
      final yPadding = (yMax - yMin) * 0.05;
      final targetYMin = yMin - yPadding;
      final targetYMax = yMax + yPadding;

      // When auto-scroll is OFF, use smooth animation to expand viewport
      if (expandViewportWhenNotAutoScrolling) {
        _handleExpandMode(
          buffer: buffer,
          transform: transform,
          isInitialState: isInitialState,
          xMin: xMin,
          xMax: xMax,
          targetYMin: targetYMin,
          targetYMax: targetYMax,
          maxVisiblePoints: maxVisiblePoints,
        );
      } else {
        // Auto-scroll ON mode: only update on initial setup
        _handleAutoScrollMode(
          transform: transform,
          isInitialState: isInitialState,
          xMin: xMin,
          xMax: xMax,
          targetYMin: targetYMin,
          targetYMax: targetYMax,
        );
      }
    }

    // Request repaint (no layout needed, just paint)
    _delegate.markNeedsPaint();
  }

  /// Handles viewport updates in expand mode (auto-scroll OFF).
  void _handleExpandMode({
    required StreamingBuffer buffer,
    required ChartTransform transform,
    required bool isInitialState,
    required double xMin,
    required double xMax,
    required double targetYMin,
    required double targetYMax,
    required int maxVisiblePoints,
  }) {
    // Check if we've exceeded maxVisiblePoints - switch to sliding window mode
    final exceedsMaxVisible = buffer.length > maxVisiblePoints;

    if (exceedsMaxVisible) {
      // HYBRID MODE: Too many points to expand, switch to sliding window
      final dataRange = xMax - xMin;
      final pointSpacing = buffer.length > 1 ? dataRange / (buffer.length - 1) : 1.0;
      final visibleWidth = pointSpacing * maxVisiblePoints;

      // Smoothly slide viewport forward
      _autoScrollTargetXMax = xMax;
      _autoScrollTargetWidth = visibleWidth;

      // Also update Y targets
      if (targetYMin < (_expansionTargetYMin ?? transform.dataYMin)) {
        _expansionTargetYMin = targetYMin;
      }
      if (targetYMax > (_expansionTargetYMax ?? transform.dataYMax)) {
        _expansionTargetYMax = targetYMax;
      }

      // Start sliding animation
      _scheduleViewportExpansionAnimation();
    } else {
      // EXPAND MODE: Defer viewport updates to animation loop
      final needsXUpdate = xMax > transform.dataXMax;
      final needsYUpdate = targetYMin < transform.dataYMin || targetYMax > transform.dataYMax;

      if (isInitialState) {
        // Initial setup: apply directly
        _delegate.transform = transform.copyWith(
          dataXMin: xMin,
          dataXMax: xMax,
          dataYMin: targetYMin,
          dataYMax: targetYMax,
        );
        _delegate.updateAxesFromTransform();
      } else if (needsXUpdate || needsYUpdate) {
        // DEFERRED UPDATE: Set targets and let animation handle it
        _autoScrollTargetXMax = xMax;
        _autoScrollTargetWidth = null; // null = expand mode (no fixed width)

        if (needsYUpdate) {
          _expansionTargetYMin =
              targetYMin < (_expansionTargetYMin ?? transform.dataYMin) ? targetYMin : (_expansionTargetYMin ?? transform.dataYMin);
          _expansionTargetYMax =
              targetYMax > (_expansionTargetYMax ?? transform.dataYMax) ? targetYMax : (_expansionTargetYMax ?? transform.dataYMax);
        }

        _scheduleViewportExpansionAnimation();
      }
    }
  }

  /// Handles viewport updates in auto-scroll mode (auto-scroll ON).
  void _handleAutoScrollMode({
    required ChartTransform transform,
    required bool isInitialState,
    required double xMin,
    required double xMax,
    required double targetYMin,
    required double targetYMax,
  }) {
    final bool needsInitialXSetup = isInitialState;
    final bool needsYUpdate = isInitialState || targetYMin < transform.dataYMin || targetYMax > transform.dataYMax;

    if (needsInitialXSetup || needsYUpdate) {
      _delegate.transform = transform.copyWith(
        dataXMin: needsInitialXSetup ? xMin : transform.dataXMin,
        dataXMax: needsInitialXSetup ? xMax : transform.dataXMax,
        dataYMin: needsYUpdate ? targetYMin : transform.dataYMin,
        dataYMax: needsYUpdate ? targetYMax : transform.dataYMax,
      );
      _delegate.updateAxesFromTransform();
    }
  }

  /// Schedules viewport expansion animation if not already scheduled.
  void _scheduleViewportExpansionAnimation() {
    if (!_autoScrollAnimationScheduled) {
      _autoScrollAnimationScheduled = true;
      SchedulerBinding.instance.addPostFrameCallback((_) {
        _animateViewportExpansion();
      });
    }
  }

  /// Clears streaming data for a specific series.
  ///
  /// Called by LiveStreamController when clear() is invoked.
  void clearStreamingData(String seriesId) {
    _streamingBuffers.remove(seriesId);
    _streamingElements.remove(seriesId);
    _streamingBounds = null;

    // Reset all animation targets and expansion state
    _autoScrollTargetXMax = null;
    _autoScrollTargetWidth = null;
    _expansionTargetYMin = null;
    _expansionTargetYMax = null;
    _viewportLockedForPause = false;

    // Reset transform to initial state so new streaming mode works correctly
    final transform = _delegate.transform;
    if (transform != null) {
      _delegate.transform = ChartTransform(
        dataXMin: 0,
        dataXMax: 1,
        dataYMin: 0,
        dataYMax: 1,
        plotWidth: transform.plotWidth,
        plotHeight: transform.plotHeight,
        invertY: transform.invertY,
      );
    }

    _delegate.invalidateSeriesCache();
    _delegate.markNeedsPaint();
  }

  // ==========================================================================
  // Viewport Lock (Pause/Resume)
  // ==========================================================================

  /// Locks the viewport for pause mode.
  ///
  /// When locked:
  /// - Auto-scroll is disabled
  /// - Pan constraints use full data bounds
  /// - User can explore historical data
  void lockViewportForPause() {
    if (_viewportLockedForPause) return;

    _viewportLockedForPause = true;

    // Set pan constraints to full streaming data bounds
    if (_streamingBounds != null) {
      final yPadding = (_streamingBounds!.yMax - _streamingBounds!.yMin) * 0.05;

      _delegate.setPanConstraintBounds(
        _streamingBounds!.xMin,
        _streamingBounds!.xMax,
        _streamingBounds!.yMin - yPadding,
        _streamingBounds!.yMax + yPadding,
      );
    }
  }

  /// Unlocks the viewport after pause mode.
  ///
  /// Clears pan constraints and allows auto-scroll to resume.
  void unlockViewportForResume() {
    if (!_viewportLockedForPause) return;

    _viewportLockedForPause = false;
    _delegate.clearPanConstraintBounds();
  }

  // ==========================================================================
  // Auto-Scroll Animation
  // ==========================================================================

  /// Snaps the viewport to show the latest streaming data.
  ///
  /// Called by LiveStreamController when autoScroll is enabled.
  /// Calculates the viewport position to show the latest data with margin.
  /// Uses smooth interpolation to avoid visual stuttering.
  ///
  /// **Parameters**:
  /// - [marginPercent]: Percentage of visible width to keep as margin on right
  /// - [viewportDataPoints]: Number of data points to show in viewport. If null,
  ///   shows all accumulated data (viewport expands as buffer fills).
  void snapViewportToStreamingData({
    double marginPercent = 5.0,
    int? viewportDataPoints,
  }) {
    if (_viewportLockedForPause) return;
    final transform = _delegate.transform;
    if (_streamingBounds == null || transform == null) return;

    final bounds = _streamingBounds!;
    if (bounds.xMin >= bounds.xMax) return;

    // Calculate desired viewport width
    double viewportWidth;

    if (viewportDataPoints != null && viewportDataPoints > 0) {
      // FIXED VIEWPORT MODE: Calculate width to show specific number of points
      final pointCount = _streamingBuffers.values.firstOrNull?.length ?? 0;
      if (pointCount > 1) {
        final dataRange = bounds.xMax - bounds.xMin;
        final avgSpacing = dataRange / (pointCount - 1);
        viewportWidth = avgSpacing * viewportDataPoints;
      } else {
        viewportWidth = viewportDataPoints.toDouble();
      }
    } else {
      // EXPANDING VIEWPORT MODE: Use current transform width or full data range
      viewportWidth = transform.dataXRange;

      if (viewportWidth <= 1 || (transform.dataXMin == 0 && transform.dataXMax == 1)) {
        viewportWidth = bounds.xMax - bounds.xMin;
        if (viewportWidth <= 0) viewportWidth = 100;
      }
    }

    // Calculate margin in data units
    final marginData = viewportWidth * (marginPercent / 100.0);

    // Position viewport so latest data is at (100 - marginPercent)% from left
    final targetDataXMax = bounds.xMax + marginData;

    // Store targets for continuous animation
    _autoScrollTargetXMax = targetDataXMax;
    _autoScrollTargetWidth = viewportWidth;

    // Schedule animation frame if not already running
    if (!_autoScrollAnimationScheduled) {
      _autoScrollAnimationScheduled = true;
      SchedulerBinding.instance.addPostFrameCallback((_) {
        _animateAutoScroll();
      });
    }
  }

  /// Cancels any active auto-scroll animation.
  ///
  /// Called when user starts manual interaction (e.g., scrollbar drag).
  void cancelAutoScroll() {
    _autoScrollTargetXMax = null;
    _autoScrollTargetWidth = null;
    _autoScrollAnimationScheduled = false;
  }

  /// Continuous animation loop for smooth auto-scrolling.
  /// Runs at 60fps and smoothly interpolates toward target position.
  void _animateAutoScroll() {
    _autoScrollAnimationScheduled = false;

    final transform = _delegate.transform;

    // Stop if paused, no target, or disposed
    if (_viewportLockedForPause || _autoScrollTargetXMax == null || transform == null) {
      _autoScrollTargetXMax = null;
      _autoScrollTargetWidth = null;
      return;
    }

    final targetXMax = _autoScrollTargetXMax!;
    final currentXMax = transform.dataXMax;
    final viewportWidth = _autoScrollTargetWidth ?? transform.dataXRange;

    // Calculate delta to target
    final delta = targetXMax - currentXMax;

    // If close enough to target, snap directly and stop
    if (delta.abs() < 0.1) {
      final newXMax = targetXMax;
      final newXMin = newXMax - viewportWidth;

      _delegate.transform = transform.copyWith(
        dataXMin: newXMin,
        dataXMax: newXMax,
      );
      _delegate.updateAxesFromTransform();
      _delegate.markNeedsPaint();

      _autoScrollTargetXMax = null;
      _autoScrollTargetWidth = null;
      return;
    }

    // SMOOTH ANIMATION: Use high lerp factor for responsive but smooth motion
    const double lerpFactor = 0.15;

    // Interpolate toward target
    final newXMax = currentXMax + delta * lerpFactor;
    final newXMin = newXMax - viewportWidth;

    // Update transform
    _delegate.transform = transform.copyWith(
      dataXMin: newXMin,
      dataXMax: newXMax,
    );

    _delegate.updateAxesFromTransform();
    _delegate.markNeedsPaint();

    // Schedule next animation frame (continuous loop)
    _autoScrollAnimationScheduled = true;
    SchedulerBinding.instance.addPostFrameCallback((_) {
      _animateAutoScroll();
    });
  }

  /// Continuous animation loop for smooth viewport expansion (when auto-scroll OFF).
  /// Runs at 60fps and smoothly expands viewport to show all data.
  void _animateViewportExpansion() {
    _autoScrollAnimationScheduled = false;

    final transform = _delegate.transform;

    // Stop if paused, no target, or disposed
    if (_viewportLockedForPause || _autoScrollTargetXMax == null || transform == null) {
      _autoScrollTargetXMax = null;
      _autoScrollTargetWidth = null;
      _expansionTargetYMin = null;
      _expansionTargetYMax = null;
      return;
    }

    final targetXMax = _autoScrollTargetXMax!;
    final currentXMax = transform.dataXMax;
    final currentXMin = transform.dataXMin;

    // Y targets (use current if no target set)
    final targetYMin = _expansionTargetYMin ?? transform.dataYMin;
    final targetYMax = _expansionTargetYMax ?? transform.dataYMax;
    final currentYMin = transform.dataYMin;
    final currentYMax = transform.dataYMax;

    // Calculate target xMin based on whether we have a fixed width (sliding mode)
    final double targetXMin;
    if (_autoScrollTargetWidth != null) {
      targetXMin = targetXMax - _autoScrollTargetWidth!;
    } else {
      targetXMin = currentXMin;
    }

    // Calculate deltas to targets
    final deltaXMax = targetXMax - currentXMax;
    final deltaXMin = targetXMin - currentXMin;
    final deltaYMin = targetYMin - currentYMin;
    final deltaYMax = targetYMax - currentYMax;

    // If close enough to all targets, snap directly and stop
    if (deltaXMax.abs() < 0.1 && deltaXMin.abs() < 0.1 && deltaYMin.abs() < 0.01 && deltaYMax.abs() < 0.01) {
      _delegate.transform = transform.copyWith(
        dataXMin: targetXMin,
        dataXMax: targetXMax,
        dataYMin: targetYMin,
        dataYMax: targetYMax,
      );
      _delegate.updateAxesFromTransform();
      _delegate.markNeedsPaint();

      _autoScrollTargetXMax = null;
      _autoScrollTargetWidth = null;
      _expansionTargetYMin = null;
      _expansionTargetYMax = null;
      return;
    }

    // Smooth interpolation
    const lerpFactor = 0.15;
    final newXMin = currentXMin + deltaXMin * lerpFactor;
    final newXMax = currentXMax + deltaXMax * lerpFactor;
    final newYMin = currentYMin + deltaYMin * lerpFactor;
    final newYMax = currentYMax + deltaYMax * lerpFactor;

    _delegate.transform = transform.copyWith(
      dataXMin: newXMin,
      dataXMax: newXMax,
      dataYMin: newYMin,
      dataYMax: newYMax,
    );
    _delegate.updateAxesFromTransform();
    _delegate.markNeedsPaint();

    // Schedule next animation frame (continuous loop)
    _autoScrollAnimationScheduled = true;
    SchedulerBinding.instance.addPostFrameCallback((_) {
      _animateViewportExpansion();
    });
  }

  // ==========================================================================
  // Rendering
  // ==========================================================================

  /// Paints streaming data directly from buffers.
  ///
  /// This is the high-performance rendering path for streaming data:
  /// - Iterates buffers directly (no list allocation)
  /// - Linear interpolation (O(visible points))
  /// - Binary search to find visible range
  ///
  /// **Parameters**:
  /// - canvas: Canvas to paint on (already translated to plot space)
  /// - size: Size of the plot area
  /// - transform: Current viewport transform
  void paint(Canvas canvas, Size size, ChartTransform transform) {
    if (_streamingBuffers.isEmpty) return;

    for (final entry in _streamingBuffers.entries) {
      final seriesId = entry.key;
      final buffer = entry.value;

      if (buffer.isEmpty) continue;

      // Find matching series config for styling
      ChartSeries? seriesConfig;
      for (final s in _delegate.series) {
        if (s.id == seriesId) {
          seriesConfig = s;
          break;
        }
      }

      if (seriesConfig == null) continue;

      // Paint the streaming data directly
      _paintStreamingBuffer(canvas, buffer, seriesConfig, transform);
    }
  }

  /// Paints streaming data directly from buffer with minimal allocation.
  void _paintStreamingBuffer(
    Canvas canvas,
    StreamingBuffer buffer,
    ChartSeries seriesConfig,
    ChartTransform transform,
  ) {
    if (buffer.isEmpty) return;

    // Get styling from series config
    final color = seriesConfig.color ?? const Color(0xFF2196F3);
    final strokeWidth = (seriesConfig is LineChartSeries) ? seriesConfig.strokeWidth : 2.0;

    final paint = Paint()
      ..color = color.withValues(alpha: 0.7)
      ..style = PaintingStyle.stroke
      ..strokeWidth = strokeWidth
      ..strokeCap = StrokeCap.round
      ..strokeJoin = StrokeJoin.round;

    // Find visible range with percentage-based margin for proper edge rendering
    final xSpan = transform.dataXMax - transform.dataXMin;
    final margin = xSpan * 0.1; // 10% margin ensures lines connect at edges
    final xMin = transform.dataXMin - margin;
    final xMax = transform.dataXMax + margin;

    // Binary search to find first visible point
    int startIdx = 0;
    int endIdx = buffer.length;

    // Find first point with x >= xMin using binary search
    int lo = 0;
    int hi = buffer.length;
    while (lo < hi) {
      final mid = (lo + hi) ~/ 2;
      if (buffer[mid].x < xMin) {
        lo = mid + 1;
      } else {
        hi = mid;
      }
    }
    startIdx = lo > 0 ? lo - 1 : 0; // Include one before for line continuity

    // Find last point with x <= xMax
    lo = startIdx;
    hi = buffer.length;
    while (lo < hi) {
      final mid = (lo + hi) ~/ 2;
      if (buffer[mid].x <= xMax) {
        lo = mid + 1;
      } else {
        hi = mid;
      }
    }
    endIdx = lo < buffer.length ? lo + 1 : buffer.length;

    // Build path for visible points only
    if (startIdx >= endIdx) return;

    final path = Path();
    bool firstPoint = true;

    for (int i = startIdx; i < endIdx; i++) {
      final point = buffer[i];
      final plotPos = transform.dataToPlot(point.x, point.y);

      if (firstPoint) {
        path.moveTo(plotPos.dx, plotPos.dy);
        firstPoint = false;
      } else {
        path.lineTo(plotPos.dx, plotPos.dy);
      }
    }

    canvas.drawPath(path, paint);
  }
}
