import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:glob/glob.dart';

import 'ai_schema_emitter.dart';
import 'emitter.dart';
import 'enforcement.dart';
import 'fluent_emitter.dart';
import 'smoke_emitter.dart';
import 'surface_model.dart';
import 'surface_reader.dart';

/// Reads `@chartSurface` annotations from the braven_charts config surface
/// and emits the generated fluent extensions (and, later, the AI schema
/// mirror).
///
/// Pipeline per source library under `lib/src/**`:
///
/// 1. resolve the library and read every annotated class into a
///    `SurfaceModel` ([AnalyzerSurfaceReader]);
/// 2. resolve the PUBLIC BARREL and hand its export namespace to the emitter,
///    which refuses to generate for a class the barrel does not export
///    (generated files import only the barrel, so such a class would emit an
///    extension full of `undefined_class`);
/// 3. emit the fluent extensions through the [SurfaceEmitter] seam
///    ([SurfaceEmitter.emitLibrary], which formats with dart_style);
/// 4. write the output ONLY when at least one annotated class yields
///    members — un-annotated libraries produce no file.
///
/// The capture-group build extension preserves source subdirectories
/// (`lib/src/models/foo.dart` -> `lib/src/fluent/generated/models/
/// foo_fluent.dart`), which keeps the 1:1 input/output mapping
/// collision-proof for same-named files in different directories. One
/// generated file per SOURCE file; a source file with several annotated
/// classes yields several extensions in that one file.
///
/// Outputs are `build_to: source` and checked in; the root `build.yaml`
/// excludes `lib/src/fluent/generated/**` from inputs, and the guard below
/// keeps the builder inert on its own outputs even without that exclude.
class SurfaceGenBuilder implements Builder {
  const SurfaceGenBuilder();

  @override
  Map<String, List<String>> get buildExtensions => const {
        '^lib/src/{{}}.dart': ['lib/src/fluent/generated/{{}}_fluent.dart'],
      };

  @override
  Future<void> build(BuildStep buildStep) async {
    final inputId = buildStep.inputId;
    if (isGeneratedPath(inputId.path)) return;
    if (!await buildStep.resolver.isLibrary(inputId)) return;

    final library = await buildStep.resolver.libraryFor(inputId);
    final barrel = await barrelLibrary(buildStep);
    final model = await const AnalyzerSurfaceReader().read(
      library,
      reachable: barrel == null ? const [] : reachableClasses([barrel]),
    );
    if (model.classes.isEmpty) return;

    final SurfaceEmitter emitter = FluentEmitter(
      exportedNames: barrel?.exportNamespace.definedNames2.keys.toSet(),
    );
    final source = emitter.emitLibrary(model);
    if (source == null) return;

    final gap = countParamsWithoutClearVerb(model);
    if (gap > 0) {
      log.info(
        'surface_gen: ${inputId.path}: $gap nullable parameter(s) have no '
        'clear verb — this class\'s copyWith cannot unset them; construct a '
        'new instance to reset.',
      );
    }

    await buildStep.writeAsString(buildStep.allowedOutputs.single, source);
  }

}

/// Generates the opt-in fluent barrel from the set of generated files.
///
/// A hand-written barrel does not survive ~40 generated files: a file nobody
/// exports is invisible dead code and nothing guards it. Generating it means
/// the existing CI regenerate-and-diff gate covers barrel drift too.
///
/// Runs in a later build phase than [SurfaceGenBuilder] via
/// `required_inputs: ['_fluent.dart']`, so `findAssets` sees the freshly
/// written extensions.
class FluentBarrelBuilder implements Builder {
  const FluentBarrelBuilder();

  static const String _output = 'braven_charts_fluent.dart';

  @override
  Map<String, List<String>> get buildExtensions => const {
        r'$lib$': [_output],
      };

  @override
  Future<void> build(BuildStep buildStep) async {
    final package = buildStep.inputId.package;
    final assets = await buildStep
        .findAssets(Glob('lib/src/fluent/generated/**_fluent.dart'))
        .toList();
    if (assets.isEmpty) return;

    final exports = [
      for (final asset in assets) asset.path.substring('lib/'.length),
    ]..sort();

    final buffer = StringBuffer()
      ..writeln('/// Opt-in fluent modifier surface for braven_charts.')
      ..writeln('///')
      ..writeln('/// **Beta — work in progress; this API may change before a '
          'stable release.**')
      ..writeln('///')
      ..writeln('/// GENERATED by surface_gen — do not edit. This barrel is '
          'derived from the')
      ..writeln('/// set of generated `*_fluent.dart` files, so a generated '
          'extension can never')
      ..writeln('/// go unexported. Regenerate: dart run build_runner build')
      ..writeln('///')
      ..writeln('/// Exports the full core barrel plus the generated fluent '
          'extensions, so a')
      ..writeln('/// single import unlocks chained modifiers on the config '
          'surface:')
      ..writeln('///')
      ..writeln('/// ```dart')
      ..writeln("/// import 'package:$package/$_output';")
      ..writeln('///')
      ..writeln('/// final crosshair = const CrosshairConfig()')
      ..writeln('///     .withMode(CrosshairMode.vertical)')
      ..writeln('///     .withSnapRadius(24);')
      ..writeln('/// ```')
      ..writeln('///')
      ..writeln('/// Every chain step is an ordinary `copyWith` call '
          'returning an ordinary')
      ..writeln('/// config instance; importing this barrel changes no '
          'behavior of the core')
      ..writeln('/// API. Consumers who don\'t want the extensions keep '
          'importing')
      ..writeln('/// `package:$package/$package.dart` and never see them.')
      ..writeln('///')
      ..writeln('/// {@category Authoring and data}')
      ..writeln('library;')
      ..writeln()
      ..writeln("export '$package.dart';");
    for (final export in exports) {
      buffer.writeln("export '$export';");
    }

    await buildStep.writeAsString(
      buildStep.allowedOutputs.single,
      buffer.toString(),
    );
  }
}

/// Generates `test/fluent/fluent_smoke_generated_test.dart` — exhaustive
/// breadth coverage for the fluent surface.
///
/// Aggregating: the smoke library is ONE file covering every modelled class,
/// so it cannot be produced by the per-source-file [SurfaceGenBuilder]. It
/// re-reads the annotated libraries into a single merged [SurfaceModel] and
/// hands that to [SmokeEmitter] through the same [SurfaceEmitter] seam.
///
/// Candidate inputs are filtered TEXTUALLY on `@chartSurface` /
/// `@ChartSurface` before being resolved: resolving all ~260 libraries of
/// `lib/src/**` to find the ~35 annotated ones would dominate the build.
///
/// Output lives under `test/`, so the CI regenerate-and-diff gate lists that
/// path alongside `lib/src/fluent/generated`.
class SmokeTestBuilder implements Builder {
  const SmokeTestBuilder();

  static const String _output = 'test/fluent/fluent_smoke_generated_test.dart';

  @override
  Map<String, List<String>> get buildExtensions => const {
        r'$package$': [_output],
      };

  @override
  Future<void> build(BuildStep buildStep) async {
    final barrel = await barrelLibrary(buildStep);
    if (barrel == null) return;

    final classes = await readWholeSurface(buildStep, barrel);
    if (classes.isEmpty) return;

    final SurfaceEmitter emitter = SmokeEmitter(
      exportedNames: barrel.exportNamespace.definedNames2.keys.toSet(),
    );
    final source = emitter.emitLibrary(SurfaceModel(classes));
    if (source == null) return;

    await buildStep.writeAsString(buildStep.allowedOutputs.single, source);
  }
}

/// Generates `lib/src/ai/generated/surface_definitions.dart` — the structural
/// JSON-Schema `$defs` for every `@chartSurface` class.
///
/// Aggregating for the same reason [SmokeTestBuilder] is: one `$defs` block
/// spans the whole surface, and `$ref`s only resolve when every referenced
/// class is in the same map. It therefore shares that builder's input
/// pipeline verbatim ([readWholeSurface]) — `$package$` input, a TEXTUAL
/// `@chartSurface` pre-filter so the build does not resolve ~260 libraries to
/// find ~90 annotated ones, and one merged [SurfaceModel].
///
/// The output is ADDITIVE: `chart_tool_schema.dart` keeps its hand-written
/// `createChartTool` / `modifyChartTool` literals and their exact behavior,
/// and exposes this map alongside them as `ChartToolSchema.surfaceDefinitions`.
///
/// The generated file is deliberately Flutter-free (plain `Map<String,
/// Object?>` literals), because `chart_tool_schema.dart` is a leaf library
/// that `tool/dump_pre_convergence_schema.dart` imports from a bare `dart run`.
class SurfaceDefinitionsBuilder implements Builder {
  const SurfaceDefinitionsBuilder();

  static const String _output = 'lib/src/ai/generated/surface_definitions.dart';

  @override
  Map<String, List<String>> get buildExtensions => const {
        r'$package$': [_output],
      };

  @override
  Future<void> build(BuildStep buildStep) async {
    final barrel = await barrelLibrary(buildStep);
    if (barrel == null) return;

    final classes = await readWholeSurface(buildStep, barrel);
    if (classes.isEmpty) return;

    final source = const AiSchemaEmitter().emitLibrary(SurfaceModel(classes));
    if (source == null) return;

    await buildStep.writeAsString(buildStep.allowedOutputs.single, source);
  }
}

/// Directories holding this generator's own checked-in output.
///
/// Never inputs: an aggregating builder that re-read its own output would
/// oscillate, and the per-file builder would emit extensions for generated
/// code.
const List<String> generatedPrefixes = <String>[
  'lib/src/fluent/generated/',
  'lib/src/ai/generated/',
];

/// Whether [path] names checked-in generator output.
bool isGeneratedPath(String path) =>
    generatedPrefixes.any(path.startsWith);

/// The package's public barrel library, or `null` when there is none.
Future<LibraryElement?> barrelLibrary(BuildStep buildStep) async {
  final barrelId = AssetId(
    buildStep.inputId.package,
    'lib/${buildStep.inputId.package}.dart',
  );
  if (!await buildStep.canRead(barrelId)) return null;
  return buildStep.resolver.libraryFor(barrelId);
}

/// Reads every `@chartSurface` class under `lib/src/**` into one flat list.
///
/// Shared by the two aggregating builders so they can never disagree about
/// what "the whole surface" is — a smoke test covering classes the schema
/// omits (or vice versa) would be a drift the drift tests could not see,
/// because both would be generated from different reads.
Future<List<SurfaceClass>> readWholeSurface(
  BuildStep buildStep,
  LibraryElement barrel,
) async {
  final reachable = reachableClasses([barrel]);
  final assets = await buildStep
      .findAssets(Glob('lib/src/**.dart'))
      .where((asset) => !isGeneratedPath(asset.path))
      .toList();
  assets.sort((a, b) => a.path.compareTo(b.path));

  final classes = <SurfaceClass>[];
  for (final asset in assets) {
    final source = await buildStep.readAsString(asset);
    if (!source.contains('@chartSurface') && !source.contains('@ChartSurface')) {
      continue;
    }
    if (!await buildStep.resolver.isLibrary(asset)) continue;
    final library = await buildStep.resolver.libraryFor(asset);
    final model = await const AnalyzerSurfaceReader().read(
      library,
      reachable: reachable,
    );
    classes.addAll(model.classes);
  }
  return classes;
}
