/// Emits the generated fluent modifier extensions from a [SurfaceModel].
///
/// ## Emission rules (snapshot-tested)
///
/// - One `extension <ClassName>Fluent on ClassName` per annotated class that
///   has an instance `copyWith`; classes without `copyWith` (sealed bases)
///   and classes whose every parameter is excluded emit nothing.
/// - Per non-excluded parameter: `ClassName withX(Type value)` lowering to
///   `copyWith(x: value)`. Signature types are the declared types with the
///   trailing `?` stripped — passing `null` through a `??`-style `copyWith`
///   would silently no-op, so the fluent surface only accepts real payloads
///   and clearing gets its own verb where the class supports it.
/// - Nullable parameter with a `clearFlags` entry: additionally
///   `ClassName clearX() => copyWith(<flagName>: true);`.
/// - Tri-state `ChartStyleValue<X>` parameter: three verbs —
///   `withX(X value)` → `ChartStyleValue.value(value)`, `clearX()` →
///   `const ChartStyleValue<X>.none()`, `inheritX()` →
///   `const ChartStyleValue<X>.inherit()` (explicit type args on
///   none/inherit).
/// - `combinedSetters` metadata replaces its member parameters entirely with
///   one setter taking the members positionally with their DECLARED types
///   (nullability preserved); combined setters are emitted after the
///   per-parameter methods.
/// - Sealed variant helpers are NOT emitted yet: no pilot class lists
///   `sealedVariants`, and the owner-parameter linkage the helpers need is
///   pinned down by Task 5's real metadata (CartesianValueSummaryConfig).
/// - Every generated member carries a one-line dartdoc referencing the source
///   property (`[ClassName.param]`).
///
/// ## Generated file shape
///
/// `emitLibrary` produces the whole checked-in file: the standard header
/// (`// GENERATED by surface_gen — do not edit.` + the source library URI),
/// imports, and one extension per emittable class in declaration order.
/// Generated code resolves its types through exactly two imports:
///
/// - `package:braven_charts/braven_charts.dart` (always; the extended class
///   itself comes from the barrel), and
/// - `package:flutter/widgets.dart`, only when an emitted signature
///   references a Flutter/dart:ui type (curated name set below) — keeping
///   files without Flutter types free of `unused_import`.
///
/// No `ignore_for_file` lines: the output is lint-clean under the repo's
/// analysis options.
library;

import 'package:dart_style/dart_style.dart';

import 'emitter.dart';
import 'surface_model.dart';

/// Flutter/dart:ui type names that force the `package:flutter/widgets.dart`
/// import when they appear in an emitted signature. Extend as the annotated
/// fleet grows (Task 5).
const Set<String> _flutterTypeNames = {
  'Alignment',
  'AlignmentGeometry',
  'BorderRadius',
  'BorderRadiusGeometry',
  'BoxShadow',
  'Color',
  'Curve',
  'Duration',
  'EdgeInsets',
  'EdgeInsetsGeometry',
  'FontStyle',
  'FontWeight',
  'Gradient',
  'IconData',
  'Offset',
  'Paint',
  'Radius',
  'Rect',
  'Shadow',
  'Size',
  'StrokeCap',
  'TextAlign',
  'TextStyle',
  'Widget',
};

/// [SurfaceEmitter] producing the fluent modifier extensions.
class FluentEmitter implements SurfaceEmitter {
  const FluentEmitter();

  @override
  String get outputSuffix => '_fluent.dart';

  @override
  String emit(SurfaceClass cls, SurfaceModel model) {
    final source = _emitExtension(cls);
    if (source.isEmpty) return '';
    return _format(source);
  }

  /// Emits the complete generated library for [model] (one source file's
  /// annotated classes), or `null` when no class yields any member.
  String? emitLibrary(SurfaceModel model) {
    final emittable = [
      for (final cls in model.classes)
        if (_emitExtension(cls).isNotEmpty) cls,
    ];
    if (emittable.isEmpty) return null;

    final buffer = StringBuffer()
      ..writeln('// GENERATED by surface_gen — do not edit.')
      ..writeln('//')
      ..writeln('// Fluent modifier extensions generated from the '
          '@chartSurface annotations in')
      ..writeln('// ${emittable.first.libraryUri}.')
      ..writeln('// Regenerate: dart run build_runner build')
      ..writeln()
      ..writeln("import 'package:braven_charts/braven_charts.dart';");
    if (_usesFlutterTypes(emittable)) {
      buffer.writeln("import 'package:flutter/widgets.dart';");
    }
    buffer
      ..writeln()
      ..writeln(emittable.map(_emitExtension).join('\n'));
    return _format(buffer.toString());
  }

  /// Whether any emitted signature of [classes] references a curated
  /// Flutter/dart:ui type.
  bool _usesFlutterTypes(List<SurfaceClass> classes) {
    final identifier = RegExp(r'[A-Za-z_$][A-Za-z0-9_$]*');
    for (final cls in classes) {
      for (final type in _signatureTypes(cls)) {
        for (final match in identifier.allMatches(type)) {
          if (_flutterTypeNames.contains(match.group(0))) return true;
        }
      }
    }
    return false;
  }

  /// Every type string that appears in [cls]'s emitted signatures.
  Iterable<String> _signatureTypes(SurfaceClass cls) sync* {
    final combinedMembers = _combinedMemberNames(cls);
    for (final param in cls.params) {
      if (_isExcluded(param)) continue;
      if (combinedMembers.contains(param.name)) {
        yield param.dartType; // declared type, nullability preserved
      } else if (param.kind == SurfaceParamKind.triState) {
        yield param.triStatePayloadType ?? 'dynamic';
      } else {
        yield _stripNullability(param.dartType);
      }
    }
  }

  String _emitExtension(SurfaceClass cls) {
    if (!cls.hasCopyWith) return '';
    final combinedMembers = _combinedMemberNames(cls);

    final members = <String>[];
    for (final param in cls.params) {
      if (_isExcluded(param)) continue;
      if (combinedMembers.contains(param.name)) continue;
      if (param.kind == SurfaceParamKind.triState) {
        members.addAll(_triStateMethods(cls, param));
      } else {
        members.add(_withMethod(cls, param));
        if (param.clearFlag != null) {
          members.add(_clearFlagMethod(cls, param));
        }
      }
    }
    for (final setter in cls.combinedSetters) {
      members.add(_combinedMethod(cls, setter));
    }
    if (members.isEmpty) return '';

    final buffer = StringBuffer()
      ..writeln('/// Generated fluent modifiers for [${cls.name}].')
      ..writeln('extension ${cls.name}Fluent on ${cls.name} {')
      ..writeln(members.join('\n'))
      ..writeln('}');
    return buffer.toString();
  }

  String _withMethod(SurfaceClass cls, SurfaceParam param) {
    final type = _stripNullability(param.dartType);
    return '''
/// Replaces [${cls.name}.${param.name}] with [value].
${cls.name} with${_cap(param.name)}($type value) => copyWith(${param.name}: value);
''';
  }

  String _clearFlagMethod(SurfaceClass cls, SurfaceParam param) => '''
/// Clears [${cls.name}.${param.name}] to `null`.
${cls.name} clear${_cap(param.name)}() => copyWith(${param.clearFlag}: true);
''';

  List<String> _triStateMethods(SurfaceClass cls, SurfaceParam param) {
    final payload = param.triStatePayloadType ?? 'dynamic';
    final name = param.name;
    final capped = _cap(name);
    return [
      '''
/// Overrides [${cls.name}.$name] with [value].
${cls.name} with$capped($payload value) => copyWith($name: ChartStyleValue.value(value));
''',
      '''
/// Explicitly clears [${cls.name}.$name].
${cls.name} clear$capped() => copyWith($name: const ChartStyleValue<$payload>.none());
''',
      '''
/// Resets [${cls.name}.$name] to theme inheritance.
${cls.name} inherit$capped() => copyWith($name: const ChartStyleValue<$payload>.inherit());
''',
    ];
  }

  String _combinedMethod(SurfaceClass cls, CombinedSetterModel setter) {
    final members = [
      for (final name in setter.paramNames) _paramByName(cls, name),
    ];
    final refs = _joinRefs(cls, setter.paramNames);
    final signature =
        members.map((p) => '${p.dartType} ${p.name}').join(', ');
    final arguments = members.map((p) => '${p.name}: ${p.name}').join(', ');
    return '''
/// Replaces $refs together.
${cls.name} ${setter.name}($signature) => copyWith($arguments);
''';
  }

  SurfaceParam _paramByName(SurfaceClass cls, String name) {
    for (final param in cls.params) {
      if (param.name == name) return param;
    }
    throw StateError(
      'surface_gen: combined setter on ${cls.name} names unknown parameter '
      '`$name`. Known: ${cls.params.map((p) => p.name).join(', ')}',
    );
  }

  /// `[C.a] and [C.b]` for two refs, `[C.a], [C.b], and [C.c]` beyond.
  String _joinRefs(SurfaceClass cls, List<String> names) {
    final refs = [for (final name in names) '[${cls.name}.$name]'];
    if (refs.length <= 1) return refs.join();
    if (refs.length == 2) return '${refs[0]} and ${refs[1]}';
    return '${refs.sublist(0, refs.length - 1).join(', ')}, and ${refs.last}';
  }

  bool _isExcluded(SurfaceParam param) => switch (param.kind) {
        SurfaceParamKind.excludedFunction ||
        SurfaceParamKind.excludedController ||
        SurfaceParamKind.excludedByAnnotation =>
          true,
        _ => false,
      };

  Set<String> _combinedMemberNames(SurfaceClass cls) => {
        for (final setter in cls.combinedSetters) ...setter.paramNames,
      };

  String _stripNullability(String type) =>
      type.endsWith('?') ? type.substring(0, type.length - 1) : type;

  String _cap(String name) =>
      name.isEmpty ? name : name[0].toUpperCase() + name.substring(1);

  String _format(String source) => DartFormatter(
        languageVersion: DartFormatter.latestLanguageVersion,
      ).format(source);
}
