/// Emits the generated fluent modifier extensions from a [SurfaceModel].
///
/// ## Verb vocabulary (owner decision, 2026-07-21)
///
/// Two families of "unset" exist on this surface and `clear` used to mean
/// opposite things in each. They are now distinct verbs:
///
/// | verb          | family                  | lowering |
/// |---------------|-------------------------|----------|
/// | `withX(v)`    | every param             | `copyWith(x: v)` |
/// | `withoutX()`  | tri-state SUPPRESS      | `copyWith(x: const ChartStyleValue<T>.none())` |
/// | `inheritX()`  | tri-state INHERIT       | `copyWith(x: const ChartStyleValue<T>.inherit())` |
/// | `clearX()`    | nullable UNSET          | `copyWith(clearX: true)` |
/// | `updateX(fn)` | non-nullable nested cfg | `copyWith(x: fn(x))` |
///
/// The 91-field nullable family owns the intuitive meaning of `clear`
/// ("back to the default"); tri-state suppression — "render nothing, do not
/// inherit" — is `without`.
///
/// ## Emission rules (snapshot-tested)
///
/// - One `extension <ClassName>Fluent on ClassName` per annotated class that
///   has an instance `copyWith`; classes without `copyWith` (sealed bases)
///   and classes whose every parameter is excluded emit nothing. A class
///   whose `copyWith` is INHERITED and returns the base type fails loudly —
///   a base-typed fluent verb on a subtype is the slicing bug in disguise.
/// - Generic classes re-declare their type parameters:
///   `extension FooFluent<T extends num> on Foo<T>`.
/// - Per non-excluded parameter: `ClassName withX(Type value)` lowering to
///   `copyWith(x: value)`. Signature types are the declared types with the
///   trailing `?` stripped — passing `null` through a `??`-style `copyWith`
///   would silently no-op, so the fluent surface only accepts real payloads
///   and clearing gets its own verb where the class supports it. Nullable
///   parameters whose `copyWith` cannot unset them SAY SO in their dartdoc.
/// - Nullable parameter with a clear flag (derived from `copyWith`, or
///   overridden by metadata): additionally `clearX()`.
/// - Tri-state `ChartStyleValue<X>` parameter: `withX(X value)`,
///   `withoutX()`, `inheritX()`.
/// - Non-nullable nested-config parameter: additionally
///   `updateX(X Function(X current) update)`. Nullable nested configs are
///   skipped in v1 — there is no `current` to hand the callback without
///   inventing a default the owner never chose.
/// - Sealed nested parameter whose type carries `sealedVariants`: one
///   constructor helper per sealed FACTORY, `with<Factory><Param>`, mirroring
///   the factory signature verbatim (defaults included). Nothing is emitted
///   on the sealed base itself.
/// - `combinedSetters` metadata replaces its member parameters entirely with
///   one setter taking the members positionally with NON-NULLABLE types (a
///   nullable combined setter would let `withVisibleRange(null, null)`
///   compile into a silent no-op against `min ?? this.min`).
/// - `presetFactories` get NO fluent surface: Dart factories already chain
///   (`CrosshairConfig.tracking(...).withSnapRadius(12)` works today). They
///   stay in the model for Slice 3's AI schema.
/// - `is`-prefixed booleans drop the prefix: `isXOrdered` → `withXOrdered`.
/// - Every generated member carries a dartdoc referencing the source
///   property (`[ClassName.param]`).
///
/// ## Generated file shape
///
/// `emitLibrary` produces the whole checked-in file: the standard header
/// (`// GENERATED by surface_gen — do not edit.` + the source library URI),
/// imports, and one extension per emittable class in declaration order.
///
/// Imports are DERIVED, never curated. The analyzer records the defining
/// library of every type in `SurfaceParam.typeOrigins`; the emitter maps
/// `dart:ui` and `package:flutter/**` origins onto
/// `package:flutter/widgets.dart` and emits a `show` clause naming exactly
/// the types this file uses. That kills two failure modes the curated
/// allowlist had: a bare `import 'package:flutter/widgets.dart';` made
/// `TooltipTriggerMode` (defined by BOTH braven_charts and
/// `flutter/src/widgets/raw_tooltip.dart`) an `ambiguous_import`, and every
/// name missing from the 26-name list was a build failure fixable only by
/// editing the generator. `dart:core` names need no import at all.
///
/// No `ignore_for_file` lines: the output is lint-clean under the repo's
/// analysis options.
library;

import 'package:dart_style/dart_style.dart';

import 'emitter.dart';
import 'surface_model.dart';

/// The single Flutter import generated code ever needs.
const String _flutterImport = 'package:flutter/widgets.dart';

/// Counts parameters that are nullable but have NO clear verb, because the
/// owning class's `copyWith` cannot unset them.
///
/// Surfaced in the builder's log so the size of the gap stays visible
/// (~70% of nullable parameters across the fleet). The alternative fixes
/// were both rejected: `withX(T? value)` is a silent no-op, and bolting a
/// sentinel `copyWith` onto ~97 classes is a public-API rewrite.
int countParamsWithoutClearVerb(SurfaceModel model) {
  var count = 0;
  for (final cls in model.classes) {
    if (!cls.hasCopyWith) continue;
    for (final param in cls.params) {
      if (_isExcluded(param)) continue;
      if (param.kind == SurfaceParamKind.triState) continue;
      if (param.isNullable && param.clearFlag == null) count++;
    }
  }
  return count;
}

/// [SurfaceEmitter] producing the fluent modifier extensions.
class FluentEmitter implements SurfaceEmitter {
  const FluentEmitter({this.exportedNames});

  /// The public barrel's export namespace, when the caller can supply it.
  ///
  /// Generated files import ONLY `package:braven_charts/braven_charts.dart`,
  /// so annotating a class the barrel does not export produces a file full of
  /// `undefined_class`. When this set is non-null the emitter refuses to
  /// generate for such a class instead. The builder always supplies it; unit
  /// tests may leave it null.
  final Set<String>? exportedNames;

  @override
  String get outputSuffix => '_fluent.dart';

  @override
  String emit(SurfaceClass cls, SurfaceModel model) {
    final source = _emitExtension(cls, model);
    if (source.isEmpty) return '';
    return _format(source);
  }

  @override
  String? emitLibrary(SurfaceModel model) {
    final emittable = [
      for (final cls in model.classes)
        if (_emitExtension(cls, model).isNotEmpty) cls,
    ];
    if (emittable.isEmpty) return null;
    _checkExported(emittable);

    final buffer = StringBuffer()
      ..writeln('// GENERATED by surface_gen — do not edit.')
      ..writeln('//')
      ..writeln('// Fluent modifier extensions generated from the '
          '@chartSurface annotations in')
      ..writeln('// ${emittable.first.libraryUri}.')
      ..writeln('// Regenerate: dart run build_runner build')
      ..writeln()
      ..writeln("import 'package:braven_charts/braven_charts.dart';");
    final flutterNames = _flutterNames(emittable, model);
    if (flutterNames.isNotEmpty) {
      buffer.writeln(
        "import '$_flutterImport' show ${flutterNames.join(', ')};",
      );
    }
    buffer
      ..writeln()
      ..writeln([
        for (final cls in emittable) _emitExtension(cls, model),
      ].join('\n'));
    return _format(buffer.toString());
  }

  /// Named diagnostic: a class the public barrel does not export.
  void _checkExported(List<SurfaceClass> classes) {
    final exported = exportedNames;
    if (exported == null) return;
    for (final cls in classes) {
      if (exported.contains(cls.name)) continue;
      throw StateError(
        'surface_gen: ${cls.name} (${cls.libraryUri}) is annotated '
        '@chartSurface but is not exported from the public barrel. Generated '
        'fluent files import only package:braven_charts/braven_charts.dart, '
        'so the extension would not resolve. Export ${cls.name} from '
        'lib/braven_charts.dart, or drop the annotation.',
      );
    }
  }

  // -------------------------------------------------------------------------
  // Import derivation
  // -------------------------------------------------------------------------

  /// The Flutter/dart:ui type names referenced by [classes]'s signatures.
  List<String> _flutterNames(List<SurfaceClass> classes, SurfaceModel model) {
    final origins = _origins(model);
    final identifier = RegExp(r'[A-Za-z_$][A-Za-z0-9_$]*');
    final names = <String>{};
    for (final cls in classes) {
      for (final type in _signatureTypes(cls, model)) {
        for (final match in identifier.allMatches(type)) {
          final name = match.group(0)!;
          final origin = origins[name];
          if (origin == null) continue;
          if (origin == 'dart:ui' || origin.startsWith('package:flutter/')) {
            names.add(name);
          }
        }
      }
    }
    final sorted = names.toList()..sort();
    return sorted;
  }

  /// Simple type name -> defining library URI, merged over the whole model.
  Map<String, String> _origins(SurfaceModel model) {
    final origins = <String, String>{};
    for (final cls in model.classes) {
      for (final param in cls.params) {
        origins.addAll(param.typeOrigins);
      }
      for (final factory in cls.factories) {
        for (final param in factory.params) {
          origins.addAll(param.typeOrigins);
        }
      }
    }
    return origins;
  }

  /// Every type string that appears in [cls]'s emitted signatures.
  Iterable<String> _signatureTypes(SurfaceClass cls, SurfaceModel model)
      sync* {
    final combinedMembers = _combinedMemberNames(cls);
    for (final param in cls.params) {
      if (_isExcluded(param)) continue;
      if (combinedMembers.contains(param.name)) {
        yield _stripNullability(param.dartType);
        continue;
      }
      if (param.kind == SurfaceParamKind.triState) {
        yield param.triStatePayloadType ?? 'dynamic';
        continue;
      }
      yield _stripNullability(param.dartType);
      final sealed = _sealedOwner(param, model);
      if (sealed == null) continue;
      for (final factory in sealed.factories) {
        for (final factoryParam in factory.params) {
          yield factoryParam.dartType;
        }
      }
    }
  }

  // -------------------------------------------------------------------------
  // Extension body
  // -------------------------------------------------------------------------

  String _emitExtension(SurfaceClass cls, SurfaceModel model) {
    if (!cls.hasCopyWith) return '';
    final self = _selfType(cls);
    _checkCopyWithReturnType(cls, self);

    final combinedMembers = _combinedMemberNames(cls);
    final members = <String>[];
    for (final param in cls.params) {
      if (_isExcluded(param)) continue;
      if (combinedMembers.contains(param.name)) continue;
      if (param.kind == SurfaceParamKind.triState) {
        members.addAll(_triStateMethods(cls, self, param));
        continue;
      }
      members.add(_withMethod(cls, self, param));
      final sealed = _sealedOwner(param, model);
      if (sealed != null) {
        for (final factory in sealed.factories) {
          members.add(_sealedVariantMethod(cls, self, param, sealed, factory));
        }
      }
      if (param.kind == SurfaceParamKind.nestedConfig && !param.isNullable) {
        members.add(_updateMethod(cls, self, param));
      }
      if (param.clearFlag != null) {
        members.add(_clearFlagMethod(cls, self, param));
      }
    }
    for (final setter in cls.combinedSetters) {
      members.add(_combinedMethod(cls, self, setter));
      for (final name in setter.paramNames) {
        final param = _paramByName(cls, name);
        if (_isExcluded(param) || param.clearFlag == null) continue;
        members.add(_clearFlagMethod(cls, self, param));
      }
    }
    if (members.isEmpty) return '';

    final declaration = cls.typeParameters.isEmpty
        ? ''
        : '<${cls.typeParameters.join(', ')}>';
    final buffer = StringBuffer()
      ..writeln('/// Generated fluent modifiers for [${cls.name}].')
      ..writeln('extension ${cls.name}Fluent$declaration on $self {')
      ..writeln(members.join('\n'))
      ..writeln('}');
    return buffer.toString();
  }

  /// `Foo`, or `Foo<T>` for a generic class.
  String _selfType(SurfaceClass cls) {
    if (cls.typeParameters.isEmpty) return cls.name;
    final names = [
      for (final declaration in cls.typeParameters)
        declaration.split(' extends ').first,
    ];
    return '${cls.name}<${names.join(', ')}>';
  }

  /// Named diagnostic: a `copyWith` that cannot return this class.
  void _checkCopyWithReturnType(SurfaceClass cls, String self) {
    final returnType = cls.copyWithReturnType;
    if (returnType == null) return;
    if (returnType == cls.name || returnType == self) return;
    throw StateError(
      'surface_gen: ${cls.name} has no usable copyWith — the one it inherits '
      'copyWith returns $returnType, so every generated verb would hand back '
      'a $returnType and drop ${cls.name}\'s own state. Override copyWith on '
      '${cls.name} with a ${cls.name} return type, or annotate '
      '@ChartSurfaceExempt(reason).',
    );
  }

  String _withMethod(SurfaceClass cls, String self, SurfaceParam param) {
    final type = _stripNullability(param.dartType);
    final gap = param.isNullable && param.clearFlag == null
        ? '///\n'
            "/// No clear verb: this class's copyWith cannot unset\n"
            '/// [${cls.name}.${param.name}]; construct a new instance to '
            'reset it.\n'
        : '';
    return '''
/// Replaces [${cls.name}.${param.name}] with [value].
$gap$self ${_verb('with', param.name)}($type value) => copyWith(${param.name}: value);
''';
  }

  String _updateMethod(SurfaceClass cls, String self, SurfaceParam param) {
    final type = _stripNullability(param.dartType);
    return '''
/// Rebuilds [${cls.name}.${param.name}] from its current value.
///
/// `update` receives the current [$type] and returns the replacement, so
/// nested configuration is edited without re-stating the enclosing config.
$self ${_verb('update', param.name)}($type Function($type current) update) =>
    copyWith(${param.name}: update(${param.name}));
''';
  }

  String _clearFlagMethod(SurfaceClass cls, String self, SurfaceParam param) =>
      '''
/// Clears [${cls.name}.${param.name}] to `null`.
$self ${_verb('clear', param.name)}() => copyWith(${param.clearFlag}: true);
''';

  List<String> _triStateMethods(
    SurfaceClass cls,
    String self,
    SurfaceParam param,
  ) {
    final payload = param.triStatePayloadType ?? 'dynamic';
    final name = param.name;
    return [
      '''
/// Overrides [${cls.name}.$name] with [value].
$self ${_verb('with', name)}($payload value) => copyWith($name: ChartStyleValue.value(value));
''',
      '''
/// Suppresses [${cls.name}.$name] —
/// renders nothing and does not inherit the theme value.
$self ${_verb('without', name)}() => copyWith($name: const ChartStyleValue<$payload>.none());
''',
      '''
/// Resets [${cls.name}.$name] to theme inheritance.
$self ${_verb('inherit', name)}() => copyWith($name: const ChartStyleValue<$payload>.inherit());
''',
    ];
  }

  /// One helper per sealed factory: `with<Factory><Param>`.
  String _sealedVariantMethod(
    SurfaceClass cls,
    String self,
    SurfaceParam param,
    SurfaceClass sealed,
    SurfaceFactoryModel factory,
  ) {
    final positional = [
      for (final p in factory.params)
        if (!p.isNamed) p,
    ];
    final named = [
      for (final p in factory.params)
        if (p.isNamed) p,
    ];
    final signature = <String>[
      for (final p in positional) '${p.dartType} ${p.name}',
      if (named.isNotEmpty)
        '{${[
          for (final p in named)
            '${p.isRequired ? 'required ' : ''}${p.dartType} ${p.name}'
                '${!p.isRequired && p.defaultCode != null ? ' = ${p.defaultCode}' : ''}',
        ].join(', ')}}',
    ].join(', ');
    final arguments = <String>[
      for (final p in positional) p.name,
      for (final p in named) '${p.name}: ${p.name}',
    ].join(', ');
    final verb = 'with${_cap(factory.name)}${_cap(param.name)}';
    return '''
/// Sets [${cls.name}.${param.name}] to `${sealed.name}.${factory.name}(...)`.
///
/// Omitted parameters take their defaults.
$self $verb($signature) =>
    copyWith(${param.name}: ${sealed.name}.${factory.name}($arguments));
''';
  }

  String _combinedMethod(
    SurfaceClass cls,
    String self,
    CombinedSetterModel setter,
  ) {
    final members = [
      for (final name in setter.paramNames) _paramByName(cls, name),
    ];
    final refs = _joinRefs(cls, setter.paramNames);
    final signature = members
        .map((p) => '${_stripNullability(p.dartType)} ${p.name}')
        .join(', ');
    final arguments = members.map((p) => '${p.name}: ${p.name}').join(', ');
    final unclearable = members
        .any((param) => param.isNullable && param.clearFlag == null);
    final gap = unclearable
        ? '///\n'
            "/// No clear verb: this class's copyWith cannot unset them;\n"
            '/// construct a new instance to reset.\n'
        : '';
    return '''
/// Replaces $refs together.
///
/// The parameters are assert-coupled, so they only move as a pair.
$gap$self ${setter.name}($signature) => copyWith($arguments);
''';
  }

  /// The sealed surface class behind [param], when it has variant factories.
  SurfaceClass? _sealedOwner(SurfaceParam param, SurfaceModel model) {
    if (param.kind != SurfaceParamKind.nestedConfig) return null;
    if (param.isNullable) return null;
    final name = _stripNullability(param.dartType);
    final owner = model.tryByName(name);
    if (owner == null) return null;
    if (!owner.isSealed) return null;
    if (owner.sealedVariants.isEmpty || owner.factories.isEmpty) return null;
    return owner;
  }

  SurfaceParam _paramByName(SurfaceClass cls, String name) {
    for (final param in cls.params) {
      if (param.name == name) return param;
    }
    throw StateError(
      'surface_gen: combined setter on ${cls.name} names unknown parameter '
      '`$name`. Known: ${cls.params.map((p) => p.name).join(', ')}',
    );
  }

  /// `[C.a] and [C.b]` for two refs, `[C.a], [C.b], and [C.c]` beyond.
  String _joinRefs(SurfaceClass cls, List<String> names) =>
      _joinList([for (final name in names) '[${cls.name}.$name]']);

  String _joinList(List<String> items) {
    if (items.length <= 1) return items.join();
    if (items.length == 2) return '${items[0]} and ${items[1]}';
    return '${items.sublist(0, items.length - 1).join(', ')}, and '
        '${items.last}';
  }

  Set<String> _combinedMemberNames(SurfaceClass cls) => {
        for (final setter in cls.combinedSetters) ...setter.paramNames,
      };

  String _stripNullability(String type) =>
      type.endsWith('?') ? type.substring(0, type.length - 1) : type;

  /// `withX` from `x`, but `withXOrdered` from `isXOrdered`: an `is` prefix
  /// on a bool reads as noise once the verb supplies the grammar.
  String _verb(String prefix, String name) => '$prefix${_cap(_deIs(name))}';

  String _deIs(String name) {
    if (name.length > 2 &&
        name.startsWith('is') &&
        name[2] == name[2].toUpperCase() &&
        name[2] != name[2].toLowerCase()) {
      return name.substring(2);
    }
    return name;
  }

  String _cap(String name) =>
      name.isEmpty ? name : name[0].toUpperCase() + name.substring(1);

  String _format(String source) => DartFormatter(
        languageVersion: DartFormatter.latestLanguageVersion,
      ).format(source);
}

bool _isExcluded(SurfaceParam param) => switch (param.kind) {
      SurfaceParamKind.excludedFunction ||
      SurfaceParamKind.excludedController ||
      SurfaceParamKind.excludedByAnnotation ||
      SurfaceParamKind.excludedDeprecated ||
      SurfaceParamKind.excludedNoCopyWithParam =>
        true,
      _ => false,
    };
