/// Emits the exhaustive smoke coverage for the generated fluent surface.
///
/// ## What it proves
///
/// Every generated verb of every modelled class is written out once, applied
/// to a value of its owning type and handed an argument of the declared type.
/// COMPILATION is the assertion: if the emitter ever produces a verb whose
/// signature does not type-check against its owner — a stripped nullability
/// that should not have been stripped, a combined setter naming the wrong
/// parameter, a tri-state payload the class does not accept — the smoke
/// library fails to compile and `flutter test` goes red on this one file.
///
/// ## Why the cases are never executed
///
/// The subject is a FUNCTION PARAMETER, not a constructed instance:
///
/// ```dart
/// void _smokePieChartStyle(PieChartStyle subject) {
///   subject.withRadiusFactor(1.0);
/// }
/// ```
///
/// Two problems disappear at once. Constructing 90-odd classes, half of which
/// have required arguments and validating constructors, is not mechanisable —
/// the plan explicitly allowed dropping coverage for those, and this design
/// keeps ALL of them. And executing the calls would fight the constructors'
/// asserts (`SeriesTheme.colors.isNotEmpty`,
/// `TrendAnnotation.confidenceLevel < 1`, ...) with no signal to gain: the
/// *behaviour* of every verb family is already pinned, per class, by
/// `test/fluent/fluent_behavior_matrix_test.dart`. What is NOT covered there
/// is total breadth, and breadth is exactly what a compile-time check gives
/// cheaply.
///
/// The generated functions are collected into a `const` list so nothing is
/// dead code and the count is assertable.
///
/// ## Argument synthesis
///
/// A canonical literal is emitted for the types that have one (`bool`, `int`,
/// `double`, `num`, `String`, `Duration`, and any enum via
/// `Values.values.first`). Every other type — `Color`, `TextStyle`,
/// `EdgeInsets`, nested configs, function types — becomes another parameter of
/// the smoke function, typed exactly as declared. That is strictly stronger
/// than a hand-picked literal would be (it cannot accidentally be an implicit
/// subtype) and it removes the last reason to skip a class.
///
/// Verb NAMES are never re-derived here: `fluentVerb` from
/// `fluent_emitter.dart` is the single definition, so the two emitters cannot
/// drift.
library;

import 'emitter.dart';
import 'fluent_emitter.dart';
import 'surface_model.dart';

/// The single Flutter import generated code ever needs.
const String _flutterImport = 'package:flutter/widgets.dart';

/// Types with a canonical literal. Anything else becomes a typed parameter.
const Map<String, String> _literals = {
  'bool': 'true',
  'int': '1',
  'double': '1.0',
  'num': '1',
  'String': "'x'",
  'Object': "'x'",
  'Duration': 'const Duration(milliseconds: 1)',
};

/// One emitted smoke case.
class SmokeCase {
  const SmokeCase(this.className, this.functionName, this.source, this.verbs);

  /// The class the case covers.
  final String className;

  /// The generated function's name.
  final String functionName;

  /// The formatted function source.
  final String source;

  /// How many verbs the case invokes.
  final int verbs;
}

/// [SurfaceEmitter] producing `test/fluent/fluent_smoke_generated_test.dart`.
class SmokeEmitter implements SurfaceEmitter {
  const SmokeEmitter({this.exportedNames});

  /// The public barrel's export namespace, when the caller can supply it.
  ///
  /// Used to keep a braven_charts type out of the `show` clause of the
  /// Flutter import when both packages define the same simple name.
  final Set<String>? exportedNames;

  @override
  String get outputSuffix => '_smoke_generated_test.dart';

  /// Emits the smoke FUNCTION for one class, or an empty string when the
  /// class contributes no verbs.
  @override
  String emit(SurfaceClass cls, SurfaceModel model) {
    final smokeCase = _case(cls, model);
    return smokeCase?.source ?? '';
  }

  @override
  String? emitLibrary(SurfaceModel model) {
    final cases = <SmokeCase>[
      for (final cls in model.classes)
        if (_case(cls, model) case final SmokeCase smokeCase) smokeCase,
    ];
    if (cases.isEmpty) return null;

    final verbs = cases.fold<int>(0, (sum, item) => sum + item.verbs);
    final buffer = StringBuffer()
      ..writeln('// GENERATED by surface_gen — do not edit.')
      ..writeln('//')
      ..writeln('// Exhaustive smoke coverage for the generated fluent '
          'surface: ${cases.length}')
      ..writeln('// classes, $verbs verbs, each invoked once with an argument '
          'of its declared')
      ..writeln('// type. The cases are never EXECUTED — compilation is the '
          'assertion, and the')
      ..writeln('// behaviour of every verb family is pinned per class by')
      ..writeln('// test/fluent/fluent_behavior_matrix_test.dart.')
      ..writeln('//')
      ..writeln('// Regenerate: dart run build_runner build')
      ..writeln('library;')
      ..writeln()
      ..writeln("import 'package:braven_charts/braven_charts_fluent.dart';");
    final flutterNames = _flutterNames(cases, model);
    if (flutterNames.isNotEmpty) {
      buffer.writeln(
        "import '$_flutterImport' show ${flutterNames.join(', ')};",
      );
    }
    buffer
      ..writeln("import 'package:flutter_test/flutter_test.dart';")
      ..writeln();
    for (final smokeCase in cases) {
      buffer.writeln(smokeCase.source);
    }
    buffer
      ..writeln('/// Every generated smoke case, referenced so none of them '
          'is dead code.')
      ..writeln('const List<Function> _cases = <Function>[')
      ..writeln([for (final item in cases) '  ${item.functionName},'].join('\n'))
      ..writeln('];')
      ..writeln()
      ..writeln('void main() {')
      ..writeln("  test('every generated fluent verb type-checks against its "
          "owner', () {")
      ..writeln('    // Reaching this line means the ${cases.length} generated '
          'cases above compiled.')
      ..writeln('    expect(_cases, hasLength(${cases.length}));')
      ..writeln('  });')
      ..writeln('}');
    return formatGenerated(buffer.toString());
  }

  // -------------------------------------------------------------------------
  // Cases
  // -------------------------------------------------------------------------

  SmokeCase? _case(SurfaceClass cls, SurfaceModel model) {
    if (!cls.hasCopyWith) return null;
    if (cls.typeParameters.isNotEmpty) return null;
    if (cls.copyWithReturnType != null &&
        cls.copyWithReturnType != cls.name) {
      return null;
    }

    final extra = _ParameterPool();
    final statements = <String>[];
    final members = combinedMemberNames(cls);

    for (final param in cls.params) {
      if (isExcludedParam(param)) continue;
      if (members.contains(param.name)) continue;

      if (param.kind == SurfaceParamKind.triState) {
        final payload = param.triStatePayloadType ?? 'Object';
        statements
          ..add('subject.${fluentVerb('with', param.name)}'
              '(${extra.argument(payload, param)});')
          ..add('subject.${fluentVerb('without', param.name)}();')
          ..add('subject.${fluentVerb('inherit', param.name)}();');
        continue;
      }

      statements.add(
        'subject.${fluentVerb('with', param.name)}'
        '(${extra.argument(param.dartType, param)});',
      );

      final sealed = sealedOwnerFor(param, model);
      if (sealed != null) {
        for (final factory in sealed.factories) {
          statements.add(
            _sealedCall(cls, param, sealed, factory, extra),
          );
        }
      }
      if (param.kind == SurfaceParamKind.nestedConfig && !param.isNullable) {
        statements.add(
          'subject.${fluentVerb('update', param.name)}((current) => current);',
        );
      }
      if (param.clearFlag != null) {
        statements.add('subject.${fluentVerb('clear', param.name)}();');
      }
    }

    for (final setter in cls.combinedSetters) {
      final arguments = [
        for (final name in setter.paramNames)
          extra.argument(
            _paramByName(cls, name).dartType,
            _paramByName(cls, name),
          ),
      ];
      statements.add('subject.${setter.name}(${arguments.join(', ')});');
      for (final name in setter.paramNames) {
        final param = _paramByName(cls, name);
        if (isExcludedParam(param) || param.clearFlag == null) continue;
        statements.add('subject.${fluentVerb('clear', param.name)}();');
      }
    }

    if (statements.isEmpty) return null;

    final functionName = '_smoke${cls.name}';
    final signature = [
      '${cls.name} subject',
      ...extra.declarations,
    ].join(', ');
    final source = formatGenerated('''
/// Smoke coverage for [${cls.name}]'s ${statements.length} generated verb(s).
void $functionName($signature) {
${statements.map((statement) => '  $statement').join('\n')}
}
''');
    return SmokeCase(cls.name, functionName, source, statements.length);
  }

  /// `subject.with<Factory><Param>(...)`, passing every positional parameter
  /// and every REQUIRED named one; the rest take their defaults.
  String _sealedCall(
    SurfaceClass cls,
    SurfaceParam param,
    SurfaceClass sealed,
    SurfaceFactoryModel factory,
    _ParameterPool extra,
  ) {
    final arguments = <String>[];
    for (final factoryParam in factory.params) {
      if (!factoryParam.isNamed) {
        arguments.add(extra.argument(factoryParam.dartType, factoryParam));
      } else if (factoryParam.isRequired) {
        arguments.add(
          '${factoryParam.name}: '
          '${extra.argument(factoryParam.dartType, factoryParam)}',
        );
      }
    }
    final verb = 'with${capitalize(factory.name)}${capitalize(param.name)}';
    return 'subject.$verb(${arguments.join(', ')});';
  }

  SurfaceParam _paramByName(SurfaceClass cls, String name) {
    for (final param in cls.params) {
      if (param.name == name) return param;
    }
    throw StateError(
      'surface_gen: smoke emitter: combined setter on ${cls.name} names '
      'unknown parameter `$name`.',
    );
  }

  // -------------------------------------------------------------------------
  // Imports
  // -------------------------------------------------------------------------

  /// The Flutter/dart:ui type names the smoke signatures reference.
  ///
  /// A name the public barrel also exports is left out: braven_charts wins,
  /// and showing both would be an `ambiguous_import`.
  List<String> _flutterNames(List<SmokeCase> cases, SurfaceModel model) {
    final origins = <String, String>{};
    for (final cls in model.classes) {
      for (final param in cls.params) {
        origins.addAll(param.typeOrigins);
      }
      for (final factory in cls.factories) {
        for (final param in factory.params) {
          origins.addAll(param.typeOrigins);
        }
      }
    }
    final identifier = RegExp(r'[A-Za-z_$][A-Za-z0-9_$]*');
    final exported = exportedNames;
    final names = <String>{};
    for (final smokeCase in cases) {
      for (final match in identifier.allMatches(smokeCase.source)) {
        final name = match.group(0)!;
        final origin = origins[name];
        if (origin == null) continue;
        if (origin != 'dart:ui' && !origin.startsWith('package:flutter/')) {
          continue;
        }
        if (exported != null && exported.contains(name)) continue;
        names.add(name);
      }
    }
    final sorted = names.toList()..sort();
    return sorted;
  }
}

/// Allocates the extra smoke-function parameters that stand in for types with
/// no canonical literal.
class _ParameterPool {
  final List<String> declarations = <String>[];

  String argument(String dartType, SurfaceParam param) {
    final type = stripNullability(dartType);
    final literal = _literals[type];
    if (literal != null) return literal;
    if (param.kind == SurfaceParamKind.enumType &&
        param.enumValues.isNotEmpty &&
        type == stripNullability(param.dartType)) {
      return '$type.values.first';
    }
    final name = 'a${declarations.length}';
    declarations.add('$type $name');
    return name;
  }
}
