/// Snapshot tests for [FluentEmitter] — the API design artifact.
///
/// The expected sources below are the generated code we WANT, written first;
/// the emitter must produce them. Comparison is dart_style-normalized on both
/// sides, so token-identical output passes regardless of line-break choices,
/// while doc comments (which the formatter never rewrites) must match exactly.
///
/// The three pilot models mirror what `AnalyzerSurfaceReader` produces for
/// the real annotated classes (`CrosshairConfig`,
/// `CartesianValueSummaryStyle`, `LineChartSeries`); the checked-in files
/// under `lib/src/fluent/generated/` must equal these snapshots.
library;

import 'package:dart_style/dart_style.dart';
import 'package:surface_gen/src/fluent_emitter.dart';
import 'package:surface_gen/src/surface_model.dart';
import 'package:test/test.dart';

final DartFormatter _formatter = DartFormatter(
  languageVersion: DartFormatter.latestLanguageVersion,
);

String _normalize(String source) => _formatter.format(source);

// ===========================================================================
// Pilot 1: CrosshairConfig (lib/src/models/interaction_config.dart)
// ===========================================================================

const SurfaceClass _crosshairConfig = SurfaceClass(
  name: 'CrosshairConfig',
  libraryUri: 'package:braven_charts/src/models/interaction_config.dart',
  isConstConstructible: true,
  hasCopyWith: true,
  presetFactories: ['tracking', 'defaultConfig'],
  params: [
    SurfaceParam(
      name: 'enabled',
      dartType: 'bool',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: 'true',
    ),
    SurfaceParam(
      name: 'mode',
      dartType: 'CrosshairMode',
      kind: SurfaceParamKind.enumType,
      isRequired: false,
      isNullable: false,
      defaultCode: 'CrosshairMode.both',
      enumValues: ['vertical', 'horizontal', 'both', 'none'],
    ),
    SurfaceParam(
      name: 'snapToDataPoint',
      dartType: 'bool',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: 'true',
    ),
    SurfaceParam(
      name: 'snapRadius',
      dartType: 'double',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: '20.0',
    ),
    SurfaceParam(
      name: 'showCoordinateLabels',
      dartType: 'bool',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: 'true',
    ),
    SurfaceParam(
      name: 'coordinateLabelStyle',
      dartType: 'TextStyle?',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: true,
    ),
    SurfaceParam(
      name: 'style',
      dartType: 'CrosshairStyle',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: 'const CrosshairStyle()',
    ),
    SurfaceParam(
      name: 'displayMode',
      dartType: 'CrosshairDisplayMode',
      kind: SurfaceParamKind.enumType,
      isRequired: false,
      isNullable: false,
      defaultCode: 'CrosshairDisplayMode.auto',
      enumValues: ['standard', 'tracking', 'auto'],
    ),
    SurfaceParam(
      name: 'trackingModeThreshold',
      dartType: 'int',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: '250',
    ),
    SurfaceParam(
      name: 'interpolateValues',
      dartType: 'bool',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: 'true',
    ),
    SurfaceParam(
      name: 'showTrackingTooltip',
      dartType: 'bool',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: 'true',
    ),
    SurfaceParam(
      name: 'showIntersectionMarkers',
      dartType: 'bool',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: 'true',
    ),
    SurfaceParam(
      name: 'intersectionMarkerRadius',
      dartType: 'double',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: '4.0',
    ),
  ],
);

const String _expectedInteractionConfigFluent = '''
// GENERATED by surface_gen — do not edit.
//
// Fluent modifier extensions generated from the @chartSurface annotations in
// package:braven_charts/src/models/interaction_config.dart.
// Regenerate: dart run build_runner build

import 'package:braven_charts/braven_charts.dart';
import 'package:flutter/widgets.dart';

/// Generated fluent modifiers for [CrosshairConfig].
extension CrosshairConfigFluent on CrosshairConfig {
  /// Replaces [CrosshairConfig.enabled] with [value].
  CrosshairConfig withEnabled(bool value) => copyWith(enabled: value);

  /// Replaces [CrosshairConfig.mode] with [value].
  CrosshairConfig withMode(CrosshairMode value) => copyWith(mode: value);

  /// Replaces [CrosshairConfig.snapToDataPoint] with [value].
  CrosshairConfig withSnapToDataPoint(bool value) =>
      copyWith(snapToDataPoint: value);

  /// Replaces [CrosshairConfig.snapRadius] with [value].
  CrosshairConfig withSnapRadius(double value) => copyWith(snapRadius: value);

  /// Replaces [CrosshairConfig.showCoordinateLabels] with [value].
  CrosshairConfig withShowCoordinateLabels(bool value) =>
      copyWith(showCoordinateLabels: value);

  /// Replaces [CrosshairConfig.coordinateLabelStyle] with [value].
  CrosshairConfig withCoordinateLabelStyle(TextStyle value) =>
      copyWith(coordinateLabelStyle: value);

  /// Replaces [CrosshairConfig.style] with [value].
  CrosshairConfig withStyle(CrosshairStyle value) => copyWith(style: value);

  /// Replaces [CrosshairConfig.displayMode] with [value].
  CrosshairConfig withDisplayMode(CrosshairDisplayMode value) =>
      copyWith(displayMode: value);

  /// Replaces [CrosshairConfig.trackingModeThreshold] with [value].
  CrosshairConfig withTrackingModeThreshold(int value) =>
      copyWith(trackingModeThreshold: value);

  /// Replaces [CrosshairConfig.interpolateValues] with [value].
  CrosshairConfig withInterpolateValues(bool value) =>
      copyWith(interpolateValues: value);

  /// Replaces [CrosshairConfig.showTrackingTooltip] with [value].
  CrosshairConfig withShowTrackingTooltip(bool value) =>
      copyWith(showTrackingTooltip: value);

  /// Replaces [CrosshairConfig.showIntersectionMarkers] with [value].
  CrosshairConfig withShowIntersectionMarkers(bool value) =>
      copyWith(showIntersectionMarkers: value);

  /// Replaces [CrosshairConfig.intersectionMarkerRadius] with [value].
  CrosshairConfig withIntersectionMarkerRadius(double value) =>
      copyWith(intersectionMarkerRadius: value);
}
''';

// ===========================================================================
// Pilot 2: CartesianValueSummaryStyle
// (lib/src/models/cartesian_value_summary_style.dart)
// ===========================================================================

SurfaceParam _triState(String name, String payload) => SurfaceParam(
      name: name,
      dartType: 'ChartStyleValue<$payload>',
      kind: SurfaceParamKind.triState,
      isRequired: false,
      isNullable: false,
      defaultCode: 'const ChartStyleValue<$payload>.inherit()',
      triStatePayloadType: payload,
    );

final SurfaceClass _cartesianValueSummaryStyle = SurfaceClass(
  name: 'CartesianValueSummaryStyle',
  libraryUri:
      'package:braven_charts/src/models/cartesian_value_summary_style.dart',
  isConstConstructible: true,
  hasCopyWith: true,
  params: [
    _triState('backgroundColor', 'Color'),
    _triState('backgroundOpacity', 'double'),
    _triState('borderColor', 'Color'),
    _triState('borderWidth', 'double'),
    _triState('borderRadius', 'BorderRadius'),
    _triState('padding', 'EdgeInsets'),
    _triState('textStyle', 'TextStyle'),
    _triState('labelStyle', 'TextStyle'),
    _triState('accentColor', 'Color'),
    _triState('shadow', 'BoxShadow'),
    _triState('minWidth', 'double'),
    _triState('maxWidth', 'double'),
    _triState('rowGap', 'double'),
    _triState('labelValueGap', 'double'),
  ],
);

const String _expectedCartesianValueSummaryStyleFluent = '''
// GENERATED by surface_gen — do not edit.
//
// Fluent modifier extensions generated from the @chartSurface annotations in
// package:braven_charts/src/models/cartesian_value_summary_style.dart.
// Regenerate: dart run build_runner build

import 'package:braven_charts/braven_charts.dart';
import 'package:flutter/widgets.dart';

/// Generated fluent modifiers for [CartesianValueSummaryStyle].
extension CartesianValueSummaryStyleFluent on CartesianValueSummaryStyle {
  /// Overrides [CartesianValueSummaryStyle.backgroundColor] with [value].
  CartesianValueSummaryStyle withBackgroundColor(Color value) =>
      copyWith(backgroundColor: ChartStyleValue.value(value));

  /// Explicitly clears [CartesianValueSummaryStyle.backgroundColor].
  CartesianValueSummaryStyle clearBackgroundColor() =>
      copyWith(backgroundColor: const ChartStyleValue<Color>.none());

  /// Resets [CartesianValueSummaryStyle.backgroundColor] to theme inheritance.
  CartesianValueSummaryStyle inheritBackgroundColor() =>
      copyWith(backgroundColor: const ChartStyleValue<Color>.inherit());

  /// Overrides [CartesianValueSummaryStyle.backgroundOpacity] with [value].
  CartesianValueSummaryStyle withBackgroundOpacity(double value) =>
      copyWith(backgroundOpacity: ChartStyleValue.value(value));

  /// Explicitly clears [CartesianValueSummaryStyle.backgroundOpacity].
  CartesianValueSummaryStyle clearBackgroundOpacity() =>
      copyWith(backgroundOpacity: const ChartStyleValue<double>.none());

  /// Resets [CartesianValueSummaryStyle.backgroundOpacity] to theme inheritance.
  CartesianValueSummaryStyle inheritBackgroundOpacity() =>
      copyWith(backgroundOpacity: const ChartStyleValue<double>.inherit());

  /// Overrides [CartesianValueSummaryStyle.borderColor] with [value].
  CartesianValueSummaryStyle withBorderColor(Color value) =>
      copyWith(borderColor: ChartStyleValue.value(value));

  /// Explicitly clears [CartesianValueSummaryStyle.borderColor].
  CartesianValueSummaryStyle clearBorderColor() =>
      copyWith(borderColor: const ChartStyleValue<Color>.none());

  /// Resets [CartesianValueSummaryStyle.borderColor] to theme inheritance.
  CartesianValueSummaryStyle inheritBorderColor() =>
      copyWith(borderColor: const ChartStyleValue<Color>.inherit());

  /// Overrides [CartesianValueSummaryStyle.borderWidth] with [value].
  CartesianValueSummaryStyle withBorderWidth(double value) =>
      copyWith(borderWidth: ChartStyleValue.value(value));

  /// Explicitly clears [CartesianValueSummaryStyle.borderWidth].
  CartesianValueSummaryStyle clearBorderWidth() =>
      copyWith(borderWidth: const ChartStyleValue<double>.none());

  /// Resets [CartesianValueSummaryStyle.borderWidth] to theme inheritance.
  CartesianValueSummaryStyle inheritBorderWidth() =>
      copyWith(borderWidth: const ChartStyleValue<double>.inherit());

  /// Overrides [CartesianValueSummaryStyle.borderRadius] with [value].
  CartesianValueSummaryStyle withBorderRadius(BorderRadius value) =>
      copyWith(borderRadius: ChartStyleValue.value(value));

  /// Explicitly clears [CartesianValueSummaryStyle.borderRadius].
  CartesianValueSummaryStyle clearBorderRadius() =>
      copyWith(borderRadius: const ChartStyleValue<BorderRadius>.none());

  /// Resets [CartesianValueSummaryStyle.borderRadius] to theme inheritance.
  CartesianValueSummaryStyle inheritBorderRadius() =>
      copyWith(borderRadius: const ChartStyleValue<BorderRadius>.inherit());

  /// Overrides [CartesianValueSummaryStyle.padding] with [value].
  CartesianValueSummaryStyle withPadding(EdgeInsets value) =>
      copyWith(padding: ChartStyleValue.value(value));

  /// Explicitly clears [CartesianValueSummaryStyle.padding].
  CartesianValueSummaryStyle clearPadding() =>
      copyWith(padding: const ChartStyleValue<EdgeInsets>.none());

  /// Resets [CartesianValueSummaryStyle.padding] to theme inheritance.
  CartesianValueSummaryStyle inheritPadding() =>
      copyWith(padding: const ChartStyleValue<EdgeInsets>.inherit());

  /// Overrides [CartesianValueSummaryStyle.textStyle] with [value].
  CartesianValueSummaryStyle withTextStyle(TextStyle value) =>
      copyWith(textStyle: ChartStyleValue.value(value));

  /// Explicitly clears [CartesianValueSummaryStyle.textStyle].
  CartesianValueSummaryStyle clearTextStyle() =>
      copyWith(textStyle: const ChartStyleValue<TextStyle>.none());

  /// Resets [CartesianValueSummaryStyle.textStyle] to theme inheritance.
  CartesianValueSummaryStyle inheritTextStyle() =>
      copyWith(textStyle: const ChartStyleValue<TextStyle>.inherit());

  /// Overrides [CartesianValueSummaryStyle.labelStyle] with [value].
  CartesianValueSummaryStyle withLabelStyle(TextStyle value) =>
      copyWith(labelStyle: ChartStyleValue.value(value));

  /// Explicitly clears [CartesianValueSummaryStyle.labelStyle].
  CartesianValueSummaryStyle clearLabelStyle() =>
      copyWith(labelStyle: const ChartStyleValue<TextStyle>.none());

  /// Resets [CartesianValueSummaryStyle.labelStyle] to theme inheritance.
  CartesianValueSummaryStyle inheritLabelStyle() =>
      copyWith(labelStyle: const ChartStyleValue<TextStyle>.inherit());

  /// Overrides [CartesianValueSummaryStyle.accentColor] with [value].
  CartesianValueSummaryStyle withAccentColor(Color value) =>
      copyWith(accentColor: ChartStyleValue.value(value));

  /// Explicitly clears [CartesianValueSummaryStyle.accentColor].
  CartesianValueSummaryStyle clearAccentColor() =>
      copyWith(accentColor: const ChartStyleValue<Color>.none());

  /// Resets [CartesianValueSummaryStyle.accentColor] to theme inheritance.
  CartesianValueSummaryStyle inheritAccentColor() =>
      copyWith(accentColor: const ChartStyleValue<Color>.inherit());

  /// Overrides [CartesianValueSummaryStyle.shadow] with [value].
  CartesianValueSummaryStyle withShadow(BoxShadow value) =>
      copyWith(shadow: ChartStyleValue.value(value));

  /// Explicitly clears [CartesianValueSummaryStyle.shadow].
  CartesianValueSummaryStyle clearShadow() =>
      copyWith(shadow: const ChartStyleValue<BoxShadow>.none());

  /// Resets [CartesianValueSummaryStyle.shadow] to theme inheritance.
  CartesianValueSummaryStyle inheritShadow() =>
      copyWith(shadow: const ChartStyleValue<BoxShadow>.inherit());

  /// Overrides [CartesianValueSummaryStyle.minWidth] with [value].
  CartesianValueSummaryStyle withMinWidth(double value) =>
      copyWith(minWidth: ChartStyleValue.value(value));

  /// Explicitly clears [CartesianValueSummaryStyle.minWidth].
  CartesianValueSummaryStyle clearMinWidth() =>
      copyWith(minWidth: const ChartStyleValue<double>.none());

  /// Resets [CartesianValueSummaryStyle.minWidth] to theme inheritance.
  CartesianValueSummaryStyle inheritMinWidth() =>
      copyWith(minWidth: const ChartStyleValue<double>.inherit());

  /// Overrides [CartesianValueSummaryStyle.maxWidth] with [value].
  CartesianValueSummaryStyle withMaxWidth(double value) =>
      copyWith(maxWidth: ChartStyleValue.value(value));

  /// Explicitly clears [CartesianValueSummaryStyle.maxWidth].
  CartesianValueSummaryStyle clearMaxWidth() =>
      copyWith(maxWidth: const ChartStyleValue<double>.none());

  /// Resets [CartesianValueSummaryStyle.maxWidth] to theme inheritance.
  CartesianValueSummaryStyle inheritMaxWidth() =>
      copyWith(maxWidth: const ChartStyleValue<double>.inherit());

  /// Overrides [CartesianValueSummaryStyle.rowGap] with [value].
  CartesianValueSummaryStyle withRowGap(double value) =>
      copyWith(rowGap: ChartStyleValue.value(value));

  /// Explicitly clears [CartesianValueSummaryStyle.rowGap].
  CartesianValueSummaryStyle clearRowGap() =>
      copyWith(rowGap: const ChartStyleValue<double>.none());

  /// Resets [CartesianValueSummaryStyle.rowGap] to theme inheritance.
  CartesianValueSummaryStyle inheritRowGap() =>
      copyWith(rowGap: const ChartStyleValue<double>.inherit());

  /// Overrides [CartesianValueSummaryStyle.labelValueGap] with [value].
  CartesianValueSummaryStyle withLabelValueGap(double value) =>
      copyWith(labelValueGap: ChartStyleValue.value(value));

  /// Explicitly clears [CartesianValueSummaryStyle.labelValueGap].
  CartesianValueSummaryStyle clearLabelValueGap() =>
      copyWith(labelValueGap: const ChartStyleValue<double>.none());

  /// Resets [CartesianValueSummaryStyle.labelValueGap] to theme inheritance.
  CartesianValueSummaryStyle inheritLabelValueGap() =>
      copyWith(labelValueGap: const ChartStyleValue<double>.inherit());
}
''';

// ===========================================================================
// Pilot 3: LineChartSeries (lib/src/models/chart_series.dart)
// ===========================================================================

const SurfaceClass _lineChartSeries = SurfaceClass(
  name: 'LineChartSeries',
  libraryUri: 'package:braven_charts/src/models/chart_series.dart',
  isConstConstructible: true,
  hasCopyWith: true,
  params: [
    SurfaceParam(
      name: 'id',
      dartType: 'String',
      kind: SurfaceParamKind.value,
      isRequired: true,
      isNullable: false,
    ),
    SurfaceParam(
      name: 'name',
      dartType: 'String?',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: true,
    ),
    SurfaceParam(
      name: 'points',
      dartType: 'List<ChartDataPoint>',
      kind: SurfaceParamKind.listValue,
      isRequired: true,
      isNullable: false,
    ),
    SurfaceParam(
      name: 'color',
      dartType: 'Color?',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: true,
    ),
    SurfaceParam(
      name: 'isXOrdered',
      dartType: 'bool',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: 'false',
    ),
    SurfaceParam(
      name: 'metadata',
      dartType: 'Map<String, dynamic>?',
      kind: SurfaceParamKind.mapValue,
      isRequired: false,
      isNullable: true,
    ),
    SurfaceParam(
      name: 'style',
      dartType: 'SeriesStyle?',
      kind: SurfaceParamKind.enumType,
      isRequired: false,
      isNullable: true,
      enumValues: [
        'line',
        'bar',
        'scatter',
        'area',
        'pie',
        'donut',
        'candlestick',
        'polarColumn',
      ],
    ),
    SurfaceParam(
      name: 'annotations',
      dartType: 'List<ChartAnnotation>',
      kind: SurfaceParamKind.listValue,
      isRequired: false,
      isNullable: false,
    ),
    SurfaceParam(
      name: 'yAxisId',
      dartType: 'String?',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: true,
    ),
    SurfaceParam(
      name: 'yAxisConfig',
      dartType: 'YAxisConfig?',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: true,
    ),
    SurfaceParam(
      name: 'unit',
      dartType: 'String?',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: true,
    ),
    SurfaceParam(
      name: 'interpolation',
      dartType: 'LineInterpolation',
      kind: SurfaceParamKind.enumType,
      isRequired: false,
      isNullable: false,
      defaultCode: 'LineInterpolation.linear',
      enumValues: ['linear', 'bezier', 'stepped', 'monotone'],
    ),
    SurfaceParam(
      name: 'strokeWidth',
      dartType: 'double',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: '2.0',
    ),
    SurfaceParam(
      name: 'tension',
      dartType: 'double',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: '0.25',
    ),
    SurfaceParam(
      name: 'showDataPointMarkers',
      dartType: 'bool',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: 'false',
    ),
    SurfaceParam(
      name: 'dataPointMarkerRadius',
      dartType: 'double',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: '3.0',
    ),
    SurfaceParam(
      name: 'dataPointMarkerStyle',
      dartType: 'DataPointMarkerStyle',
      kind: SurfaceParamKind.enumType,
      isRequired: false,
      isNullable: false,
      defaultCode: 'DataPointMarkerStyle.filled',
      enumValues: ['filled', 'hollow'],
    ),
    SurfaceParam(
      name: 'dataPointMarkerBackground',
      dartType: 'Color',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: 'Colors.white',
    ),
    SurfaceParam(
      name: 'lineGlow',
      dartType: 'double',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: '0.0',
    ),
    SurfaceParam(
      name: 'dataPointLabels',
      dartType: 'DataPointLabelConfig?',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: true,
    ),
    SurfaceParam(
      name: 'inlineLabel',
      dartType: 'SeriesInlineLabelConfig?',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: true,
    ),
    SurfaceParam(
      name: 'pathAnimation',
      dartType: 'PathAnimationStyle',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: false,
      defaultCode: 'const PathAnimationStyle()',
    ),
    SurfaceParam(
      name: 'dashPattern',
      dartType: 'List<double>',
      kind: SurfaceParamKind.listValue,
      isRequired: false,
      isNullable: false,
      defaultCode: 'const []',
    ),
  ],
);

const String _expectedChartSeriesFluent = '''
// GENERATED by surface_gen — do not edit.
//
// Fluent modifier extensions generated from the @chartSurface annotations in
// package:braven_charts/src/models/chart_series.dart.
// Regenerate: dart run build_runner build

import 'package:braven_charts/braven_charts.dart';
import 'package:flutter/widgets.dart';

/// Generated fluent modifiers for [LineChartSeries].
extension LineChartSeriesFluent on LineChartSeries {
  /// Replaces [LineChartSeries.id] with [value].
  LineChartSeries withId(String value) => copyWith(id: value);

  /// Replaces [LineChartSeries.name] with [value].
  LineChartSeries withName(String value) => copyWith(name: value);

  /// Replaces [LineChartSeries.points] with [value].
  LineChartSeries withPoints(List<ChartDataPoint> value) =>
      copyWith(points: value);

  /// Replaces [LineChartSeries.color] with [value].
  LineChartSeries withColor(Color value) => copyWith(color: value);

  /// Replaces [LineChartSeries.isXOrdered] with [value].
  LineChartSeries withIsXOrdered(bool value) => copyWith(isXOrdered: value);

  /// Replaces [LineChartSeries.metadata] with [value].
  LineChartSeries withMetadata(Map<String, dynamic> value) =>
      copyWith(metadata: value);

  /// Replaces [LineChartSeries.style] with [value].
  LineChartSeries withStyle(SeriesStyle value) => copyWith(style: value);

  /// Replaces [LineChartSeries.annotations] with [value].
  LineChartSeries withAnnotations(List<ChartAnnotation> value) =>
      copyWith(annotations: value);

  /// Replaces [LineChartSeries.yAxisId] with [value].
  LineChartSeries withYAxisId(String value) => copyWith(yAxisId: value);

  /// Replaces [LineChartSeries.yAxisConfig] with [value].
  LineChartSeries withYAxisConfig(YAxisConfig value) =>
      copyWith(yAxisConfig: value);

  /// Replaces [LineChartSeries.unit] with [value].
  LineChartSeries withUnit(String value) => copyWith(unit: value);

  /// Replaces [LineChartSeries.interpolation] with [value].
  LineChartSeries withInterpolation(LineInterpolation value) =>
      copyWith(interpolation: value);

  /// Replaces [LineChartSeries.strokeWidth] with [value].
  LineChartSeries withStrokeWidth(double value) => copyWith(strokeWidth: value);

  /// Replaces [LineChartSeries.tension] with [value].
  LineChartSeries withTension(double value) => copyWith(tension: value);

  /// Replaces [LineChartSeries.showDataPointMarkers] with [value].
  LineChartSeries withShowDataPointMarkers(bool value) =>
      copyWith(showDataPointMarkers: value);

  /// Replaces [LineChartSeries.dataPointMarkerRadius] with [value].
  LineChartSeries withDataPointMarkerRadius(double value) =>
      copyWith(dataPointMarkerRadius: value);

  /// Replaces [LineChartSeries.dataPointMarkerStyle] with [value].
  LineChartSeries withDataPointMarkerStyle(DataPointMarkerStyle value) =>
      copyWith(dataPointMarkerStyle: value);

  /// Replaces [LineChartSeries.dataPointMarkerBackground] with [value].
  LineChartSeries withDataPointMarkerBackground(Color value) =>
      copyWith(dataPointMarkerBackground: value);

  /// Replaces [LineChartSeries.lineGlow] with [value].
  LineChartSeries withLineGlow(double value) => copyWith(lineGlow: value);

  /// Replaces [LineChartSeries.dataPointLabels] with [value].
  LineChartSeries withDataPointLabels(DataPointLabelConfig value) =>
      copyWith(dataPointLabels: value);

  /// Replaces [LineChartSeries.inlineLabel] with [value].
  LineChartSeries withInlineLabel(SeriesInlineLabelConfig value) =>
      copyWith(inlineLabel: value);

  /// Replaces [LineChartSeries.pathAnimation] with [value].
  LineChartSeries withPathAnimation(PathAnimationStyle value) =>
      copyWith(pathAnimation: value);

  /// Replaces [LineChartSeries.dashPattern] with [value].
  LineChartSeries withDashPattern(List<double> value) =>
      copyWith(dashPattern: value);
}
''';

// ===========================================================================
// Synthetic classes covering rules the pilots do not exercise
// ===========================================================================

/// Combined setters replace their member params entirely.
const SurfaceClass _axisWithCombined = SurfaceClass(
  name: 'FixtureAxisConfig',
  libraryUri: 'package:braven_charts/src/models/fixture_axis_config.dart',
  isConstConstructible: true,
  hasCopyWith: true,
  combinedSetters: [
    CombinedSetterModel('withVisibleRange', ['min', 'max']),
  ],
  params: [
    SurfaceParam(
      name: 'label',
      dartType: 'String?',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: true,
    ),
    SurfaceParam(
      name: 'min',
      dartType: 'double?',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: true,
    ),
    SurfaceParam(
      name: 'max',
      dartType: 'double?',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: true,
    ),
  ],
);

const String _expectedAxisWithCombined = '''
/// Generated fluent modifiers for [FixtureAxisConfig].
extension FixtureAxisConfigFluent on FixtureAxisConfig {
  /// Replaces [FixtureAxisConfig.label] with [value].
  FixtureAxisConfig withLabel(String value) => copyWith(label: value);

  /// Replaces [FixtureAxisConfig.min] and [FixtureAxisConfig.max] together.
  FixtureAxisConfig withVisibleRange(double? min, double? max) =>
      copyWith(min: min, max: max);
}
''';

/// Nullable param with a clearFlag gets an additional clear verb.
const SurfaceClass _seriesWithClearFlag = SurfaceClass(
  name: 'FixtureScatterSeries',
  libraryUri: 'package:braven_charts/src/models/fixture_scatter_series.dart',
  isConstConstructible: true,
  hasCopyWith: true,
  params: [
    SurfaceParam(
      name: 'markerStyle',
      dartType: 'FixtureMarkerStyle?',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: true,
      clearFlag: 'clearMarkerStyle',
    ),
  ],
);

const String _expectedSeriesWithClearFlag = '''
/// Generated fluent modifiers for [FixtureScatterSeries].
extension FixtureScatterSeriesFluent on FixtureScatterSeries {
  /// Replaces [FixtureScatterSeries.markerStyle] with [value].
  FixtureScatterSeries withMarkerStyle(FixtureMarkerStyle value) =>
      copyWith(markerStyle: value);

  /// Clears [FixtureScatterSeries.markerStyle] to `null`.
  FixtureScatterSeries clearMarkerStyle() => copyWith(clearMarkerStyle: true);
}
''';

/// Excluded params (function, controller, annotation) emit no methods.
const SurfaceClass _configWithExclusions = SurfaceClass(
  name: 'FixtureCallbackConfig',
  libraryUri: 'package:braven_charts/src/models/fixture_callback_config.dart',
  isConstConstructible: true,
  hasCopyWith: true,
  params: [
    SurfaceParam(
      name: 'label',
      dartType: 'String?',
      kind: SurfaceParamKind.value,
      isRequired: false,
      isNullable: true,
    ),
    SurfaceParam(
      name: 'onTap',
      dartType: 'void Function()?',
      kind: SurfaceParamKind.excludedFunction,
      isRequired: false,
      isNullable: true,
    ),
    SurfaceParam(
      name: 'controller',
      dartType: 'FixturePanController?',
      kind: SurfaceParamKind.excludedController,
      isRequired: false,
      isNullable: true,
    ),
    SurfaceParam(
      name: 'debugTag',
      dartType: 'String?',
      kind: SurfaceParamKind.excludedByAnnotation,
      isRequired: false,
      isNullable: true,
    ),
  ],
);

const String _expectedConfigWithExclusions = '''
/// Generated fluent modifiers for [FixtureCallbackConfig].
extension FixtureCallbackConfigFluent on FixtureCallbackConfig {
  /// Replaces [FixtureCallbackConfig.label] with [value].
  FixtureCallbackConfig withLabel(String value) => copyWith(label: value);
}
''';

/// A class with only excluded params yields no extension at all.
const SurfaceClass _allExcluded = SurfaceClass(
  name: 'FixtureCallbacksOnly',
  libraryUri: 'package:braven_charts/src/models/fixture_callbacks_only.dart',
  isConstConstructible: true,
  hasCopyWith: true,
  params: [
    SurfaceParam(
      name: 'onTap',
      dartType: 'void Function()?',
      kind: SurfaceParamKind.excludedFunction,
      isRequired: false,
      isNullable: true,
    ),
  ],
);

/// A class without copyWith cannot get fluent modifiers.
const SurfaceClass _noCopyWith = SurfaceClass(
  name: 'FixturePresentation',
  libraryUri: 'package:braven_charts/src/models/fixture_presentation.dart',
  isConstConstructible: true,
  hasCopyWith: false,
  isSealed: true,
  params: [],
);

/// Two annotated classes in one source library share one generated file.
const SurfaceModel _multiClassModel = SurfaceModel([
  _configWithExclusions,
  _seriesWithClearFlag,
]);

const String _expectedMultiClassFile = '''
// GENERATED by surface_gen — do not edit.
//
// Fluent modifier extensions generated from the @chartSurface annotations in
// package:braven_charts/src/models/fixture_callback_config.dart.
// Regenerate: dart run build_runner build

import 'package:braven_charts/braven_charts.dart';

/// Generated fluent modifiers for [FixtureCallbackConfig].
extension FixtureCallbackConfigFluent on FixtureCallbackConfig {
  /// Replaces [FixtureCallbackConfig.label] with [value].
  FixtureCallbackConfig withLabel(String value) => copyWith(label: value);
}

/// Generated fluent modifiers for [FixtureScatterSeries].
extension FixtureScatterSeriesFluent on FixtureScatterSeries {
  /// Replaces [FixtureScatterSeries.markerStyle] with [value].
  FixtureScatterSeries withMarkerStyle(FixtureMarkerStyle value) =>
      copyWith(markerStyle: value);

  /// Clears [FixtureScatterSeries.markerStyle] to `null`.
  FixtureScatterSeries clearMarkerStyle() => copyWith(clearMarkerStyle: true);
}
''';

void main() {
  const emitter = FluentEmitter();

  test('outputSuffix is _fluent.dart', () {
    expect(emitter.outputSuffix, '_fluent.dart');
  });

  group('pilot library snapshots (dart_style-normalized)', () {
    test('CrosshairConfig -> interaction_config_fluent.dart', () {
      final actual =
          emitter.emitLibrary(const SurfaceModel([_crosshairConfig]));
      expect(actual, _normalize(_expectedInteractionConfigFluent));
    });

    test(
        'CartesianValueSummaryStyle -> '
        'cartesian_value_summary_style_fluent.dart', () {
      final actual =
          emitter.emitLibrary(SurfaceModel([_cartesianValueSummaryStyle]));
      expect(actual, _normalize(_expectedCartesianValueSummaryStyleFluent));
    });

    test('LineChartSeries -> chart_series_fluent.dart', () {
      final actual =
          emitter.emitLibrary(const SurfaceModel([_lineChartSeries]));
      expect(actual, _normalize(_expectedChartSeriesFluent));
    });
  });

  group('emission rules', () {
    test('combined setters replace their member params entirely', () {
      final actual = emitter.emit(
        _axisWithCombined,
        const SurfaceModel([_axisWithCombined]),
      );
      expect(actual, _normalize(_expectedAxisWithCombined));
      expect(actual, isNot(contains('withMin(')));
      expect(actual, isNot(contains('withMax(')));
    });

    test('nullable param with clearFlag gains a clear verb', () {
      final actual = emitter.emit(
        _seriesWithClearFlag,
        const SurfaceModel([_seriesWithClearFlag]),
      );
      expect(actual, _normalize(_expectedSeriesWithClearFlag));
    });

    test('function, controller, and annotation exclusions emit nothing', () {
      final actual = emitter.emit(
        _configWithExclusions,
        const SurfaceModel([_configWithExclusions]),
      );
      expect(actual, _normalize(_expectedConfigWithExclusions));
      expect(actual, isNot(contains('onTap')));
      expect(actual, isNot(contains('controller')));
      expect(actual, isNot(contains('debugTag')));
    });

    test('a class with only excluded params emits an empty string', () {
      expect(
        emitter.emit(_allExcluded, const SurfaceModel([_allExcluded])),
        isEmpty,
      );
    });

    test('a class without copyWith emits an empty string', () {
      expect(
        emitter.emit(_noCopyWith, const SurfaceModel([_noCopyWith])),
        isEmpty,
      );
    });

    test('emitLibrary returns null when nothing is emittable', () {
      expect(emitter.emitLibrary(const SurfaceModel([_noCopyWith])), isNull);
      expect(emitter.emitLibrary(const SurfaceModel([_allExcluded])), isNull);
      expect(emitter.emitLibrary(const SurfaceModel([])), isNull);
    });

    test('multiple annotated classes share one generated library', () {
      final actual = emitter.emitLibrary(_multiClassModel);
      expect(actual, _normalize(_expectedMultiClassFile));
    });

    test(
        'flutter import is omitted when no signature references a '
        'Flutter type', () {
      final actual =
          emitter.emitLibrary(const SurfaceModel([_axisWithCombined]));
      expect(actual, isNot(contains('package:flutter/')));
      expect(actual, contains("import 'package:braven_charts/braven_charts.dart';"));
    });

    test('combined setter with unknown param names fails loudly', () {
      const broken = SurfaceClass(
        name: 'FixtureBroken',
        libraryUri: 'package:braven_charts/src/models/fixture_broken.dart',
        isConstConstructible: true,
        hasCopyWith: true,
        combinedSetters: [
          CombinedSetterModel('withVisibleRange', ['min', 'nope']),
        ],
        params: [
          SurfaceParam(
            name: 'min',
            dartType: 'double?',
            kind: SurfaceParamKind.value,
            isRequired: false,
            isNullable: true,
          ),
        ],
      );
      expect(
        () => emitter.emit(broken, const SurfaceModel([broken])),
        throwsStateError,
      );
    });
  });
}
