/// Opt-in fluent modifier surface for braven_charts.
///
/// Exports the full core barrel plus the generated fluent extensions, so a
/// single import unlocks chained modifiers on the config surface:
///
/// ```dart
/// import 'package:braven_charts/braven_charts_fluent.dart';
///
/// final crosshair = const CrosshairConfig()
///     .withMode(CrosshairMode.vertical)
///     .withSnapRadius(24);
/// ```
///
/// Every chain step is an ordinary `copyWith` call returning an ordinary
/// config instance; importing this barrel changes no behavior of the core
/// API. Consumers who don't want the extensions keep importing
/// `package:braven_charts/braven_charts.dart` and never see them.
///
/// The exported `*_fluent.dart` files are GENERATED by `tool/surface_gen`
/// from the `@chartSurface` annotations; regenerate with
/// `dart run build_runner build`.
library;

export 'braven_charts.dart';
export 'src/fluent/generated/models/cartesian_value_summary_style_fluent.dart';
export 'src/fluent/generated/models/chart_series_fluent.dart';
export 'src/fluent/generated/models/interaction_config_fluent.dart';
