/// Opt-in fluent modifier surface for braven_charts.
///
/// GENERATED by surface_gen — do not edit. This barrel is derived from the
/// set of generated `*_fluent.dart` files, so a generated extension can never
/// go unexported. Regenerate: dart run build_runner build
///
/// Exports the full core barrel plus the generated fluent extensions, so a
/// single import unlocks chained modifiers on the config surface:
///
/// ```dart
/// import 'package:braven_charts/braven_charts_fluent.dart';
///
/// final crosshair = const CrosshairConfig()
///     .withMode(CrosshairMode.vertical)
///     .withSnapRadius(24);
/// ```
///
/// Every chain step is an ordinary `copyWith` call returning an ordinary
/// config instance; importing this barrel changes no behavior of the core
/// API. Consumers who don't want the extensions keep importing
/// `package:braven_charts/braven_charts.dart` and never see them.
library;

export 'braven_charts.dart';
export 'src/fluent/generated/models/annotation_style_fluent.dart';
export 'src/fluent/generated/models/auto_scroll_config_fluent.dart';
export 'src/fluent/generated/models/bar_chart_style_fluent.dart';
export 'src/fluent/generated/models/candlestick_chart_series_fluent.dart';
export 'src/fluent/generated/models/candlestick_chart_style_fluent.dart';
export 'src/fluent/generated/models/candlestick_data_point_fluent.dart';
export 'src/fluent/generated/models/candlestick_density_grouping_fluent.dart';
export 'src/fluent/generated/models/cartesian_value_summary_config_fluent.dart';
export 'src/fluent/generated/models/cartesian_value_summary_style_fluent.dart';
export 'src/fluent/generated/models/category_axis_config_fluent.dart';
export 'src/fluent/generated/models/chart_annotation_fluent.dart';
export 'src/fluent/generated/models/chart_data_point_fluent.dart';
export 'src/fluent/generated/models/chart_overlay_placement_fluent.dart';
export 'src/fluent/generated/models/chart_series_fluent.dart';
export 'src/fluent/generated/models/chart_theme_fluent.dart';
export 'src/fluent/generated/models/concentric_donut_config_fluent.dart';
export 'src/fluent/generated/models/data_point_label_config_fluent.dart';
export 'src/fluent/generated/models/donut_chart_config_fluent.dart';
export 'src/fluent/generated/models/donut_chart_series_fluent.dart';
export 'src/fluent/generated/models/grid_config_fluent.dart';
export 'src/fluent/generated/models/interaction_config_fluent.dart';
export 'src/fluent/generated/models/legend_style_fluent.dart';
export 'src/fluent/generated/models/multi_axis_config_fluent.dart';
export 'src/fluent/generated/models/path_animation_style_fluent.dart';
export 'src/fluent/generated/models/pie_chart_config_fluent.dart';
export 'src/fluent/generated/models/pie_chart_series_fluent.dart';
export 'src/fluent/generated/models/polar_chart_config_fluent.dart';
export 'src/fluent/generated/models/polar_column_chart_series_fluent.dart';
export 'src/fluent/generated/models/radial_category_series_fluent.dart';
export 'src/fluent/generated/models/radial_selection_style_fluent.dart';
export 'src/fluent/generated/models/range_area_chart_series_fluent.dart';
export 'src/fluent/generated/models/range_area_data_point_fluent.dart';
export 'src/fluent/generated/models/range_area_style_fluent.dart';
export 'src/fluent/generated/models/scatter_marker_style_fluent.dart';
export 'src/fluent/generated/models/scatter_render_config_fluent.dart';
export 'src/fluent/generated/models/segment_style_fluent.dart';
export 'src/fluent/generated/models/series_inline_label_config_fluent.dart';
export 'src/fluent/generated/models/streaming_config_fluent.dart';
export 'src/fluent/generated/models/x_axis_config_fluent.dart';
export 'src/fluent/generated/models/y_axis_config_fluent.dart';
export 'src/fluent/generated/table/chart_data_table_theme_fluent.dart';
export 'src/fluent/generated/theming/components/animation_theme_fluent.dart';
export 'src/fluent/generated/theming/components/annotation_theme_fluent.dart';
export 'src/fluent/generated/theming/components/axis_style_fluent.dart';
export 'src/fluent/generated/theming/components/candlestick_theme_fluent.dart';
export 'src/fluent/generated/theming/components/cartesian_value_summary_theme_fluent.dart';
export 'src/fluent/generated/theming/components/grid_style_fluent.dart';
export 'src/fluent/generated/theming/components/interaction_theme_fluent.dart';
export 'src/fluent/generated/theming/components/range_area_theme_fluent.dart';
export 'src/fluent/generated/theming/components/scrollbar_config_fluent.dart';
export 'src/fluent/generated/theming/components/series_theme_fluent.dart';
export 'src/fluent/generated/theming/components/typography_theme_fluent.dart';
export 'src/fluent/generated/theming/styles/label_style_fluent.dart';
