// Copyright 2025 Braven Charts
// SPDX-License-Identifier: MIT

import 'dart:math' as math;
import 'dart:ui'
    show Canvas, Color, Offset, Paint, PaintingStyle, Rect, TextDirection;

import 'package:flutter/painting.dart'
    show FontWeight, TextPainter, TextSpan, TextStyle;

import '../axis/log_ticks.dart';
import '../axis/time_ticks.dart';
import '../models/axis_scale_type.dart';
import '../models/chart_series.dart';
import '../models/category_axis_config.dart';
import '../models/data_range.dart';
import '../models/x_axis_config.dart';
import '../models/x_axis_position.dart';

/// Paints the X-axis with tick marks and labels.
///
/// This painter handles the visual rendering of the horizontal X-axis.
/// It displays tick marks and labels, using the configuration provided
/// via [XAxisConfig].
///
/// Example:
/// ```dart
/// final painter = XAxisPainter(
///   config: xAxisConfig,
///   axisBounds: DataRange(min: 0.0, max: 100.0),
///   labelStyle: TextStyle(fontSize: 12),
/// );
/// painter.paint(canvas, chartArea, plotArea);
/// ```
class XAxisPainter {
  /// Creates an X-axis painter.
  ///
  /// [config] is the X-axis configuration.
  /// [axisBounds] is the data range for the X-axis.
  /// [labelStyle] is the text style for tick labels.
  /// [series] is optional list of data series for color resolution.
  /// [tickValues] are optional precomputed tick positions (e.g., from Axis).
  XAxisPainter({
    required this.config,
    required this.axisBounds,
    required this.labelStyle,
    this.series,
    this.tickValues,
    this.textDirection = TextDirection.ltr,
  });

  /// X-axis configuration.
  final XAxisConfig config;

  /// Data range for the X-axis.
  final DataRange axisBounds;

  /// Text style for tick labels.
  final TextStyle labelStyle;

  /// Optional list of data series for color resolution.
  final List<ChartSeries>? series;

  /// Optional precomputed tick positions for the X-axis.
  final List<double>? tickValues;

  /// Reading direction inherited from the chart's [Directionality].
  final TextDirection textDirection;

  /// Resolves numeric or categorical ticks for the current viewport.
  ///
  /// Categorical ticks always land on integer category centers. In automatic
  /// density mode they are thinned against the available screen extent, then
  /// naturally expand again as the user zooms into fewer categories. Numeric
  /// and categorical labels then share one exact, rotation-aware collision
  /// pass.
  List<double> resolveTickValues(double pixelExtent) {
    final candidates = _candidateTickValues();
    if (candidates.length <= 2 ||
        !config.shouldShowTickLabels ||
        config.effectiveTickLabelCollisionPolicy ==
            XAxisTickLabelCollisionPolicy.showAll ||
        !pixelExtent.isFinite ||
        pixelExtent <= 0) {
      return candidates;
    }

    final densityCandidates = _applyCategoryDensity(candidates, pixelExtent);
    if (densityCandidates.length <= 2) return densityCandidates;
    return _thinOverlappingTickLabels(densityCandidates, pixelExtent);
  }

  List<double> _candidateTickValues() {
    // A log or time axis generates its tick values directly (decades / calendar
    // boundaries) and must win before the category branch and before any legacy
    // linear ticks supplied via [tickValues]. (Linear behavior below is
    // unchanged.)
    if (config.scaleType == AxisScaleType.log ||
        config.scaleType == AxisScaleType.time) {
      return generateTicks(axisBounds);
    }
    final categoryAxis = config.categoryAxis;
    if (categoryAxis == null || categoryAxis.categories.isEmpty) {
      // The render box also supplies ticks generated by the legacy Axis
      // object. A requested count on the modern XAxisConfig must take
      // precedence over that legacy/default tick budget.
      if (config.tickCount != null) {
        return generateTicks(axisBounds);
      }
      return tickValues ?? generateTicks(axisBounds);
    }

    final renderMin = config.renderMin ?? axisBounds.min;
    final renderMax = config.renderMax ?? axisBounds.max;
    final first = math.max(0, math.max(axisBounds.min, renderMin).ceil());
    final last = math.min(
      categoryAxis.categories.length - 1,
      math.min(axisBounds.max, renderMax).floor(),
    );
    if (last < first) return const [];

    return [for (var index = first; index <= last; index++) index.toDouble()];
  }

  List<double> _applyCategoryDensity(
    List<double> candidates,
    double pixelExtent,
  ) {
    final categoryAxis = config.categoryAxis;
    if (categoryAxis == null || candidates.length <= 2) return candidates;
    final visibleCount = candidates.length;
    final labelCapacity = math.max(
      1,
      (pixelExtent / categoryAxis.minimumCategoryExtent).floor(),
    );
    if (visibleCount <= labelCapacity) return candidates;

    final stride = (visibleCount / labelCapacity).ceil();
    final result = <double>[
      for (var index = 0; index < candidates.length; index += stride)
        candidates[index],
    ];
    final last = candidates.last;
    if (result.last != last &&
        candidates.length - 1 - candidates.indexOf(result.last) >=
            math.max(1, stride / 2)) {
      result.add(last);
    }
    return result;
  }

  List<double> _thinOverlappingTickLabels(
    List<double> candidates,
    double pixelExtent,
  ) {
    final maximumWidth = _categoryLabelWidth(candidates, pixelExtent);
    final bounds = <({double left, double right})>[
      for (final value in candidates)
        _tickLabelHorizontalBounds(
          value,
          pixelExtent: pixelExtent,
          maximumWidth: maximumWidth,
        ),
    ];
    final padding = config.tickLabelCollisionPadding;
    for (var stride = 1; stride < candidates.length; stride++) {
      final indices = <int>[
        for (var index = 0; index < candidates.length; index += stride) index,
      ];
      if (indices.last != candidates.length - 1) {
        indices.add(candidates.length - 1);
      }

      var overlaps = false;
      for (var index = 1; index < indices.length; index++) {
        if (bounds[indices[index]].left <
            bounds[indices[index - 1]].right + padding) {
          overlaps = true;
          break;
        }
      }
      if (!overlaps) {
        return [for (final index in indices) candidates[index]];
      }
    }

    return [candidates.first, candidates.last];
  }

  ({double left, double right}) _tickLabelHorizontalBounds(
    double value, {
    required double pixelExtent,
    required double maximumWidth,
  }) {
    final ratio = tickRatio(value);
    final center = ratio * pixelExtent;
    final painter = layoutTickLabel(value, maximumWidth: maximumWidth);
    final width = _rotatedLabelWidth(painter);
    return (left: center - width / 2, right: center + width / 2);
  }

  /// Lays out one tick label using categorical wrapping and truncation rules.
  TextPainter layoutTickLabel(double value, {double? maximumWidth}) {
    final categoryAxis = config.categoryAxis;
    final categorical = categoryAxis != null && config.isCategorical;
    final painter = TextPainter(
      text: TextSpan(
        text: formatTickLabel(value),
        style: labelStyle.copyWith(color: resolveAxisColor()),
      ),
      textDirection: textDirection,
      maxLines: categorical
          ? (categoryAxis.labelOverflow == CategoryLabelOverflow.ellipsis
                ? 1
                : categoryAxis.maxLabelLines)
          : 1,
      ellipsis:
          categorical &&
              categoryAxis.labelOverflow == CategoryLabelOverflow.ellipsis
          ? '…'
          : null,
    );
    final width = categorical
        ? math.max(
            1.0,
            math.min(
              categoryAxis.maximumLabelExtent,
              maximumWidth ?? categoryAxis.maximumLabelExtent,
            ),
          )
        : double.infinity;
    painter.layout(maxWidth: width);
    return painter;
  }

  /// Required outward extent for the current plot width.
  ///
  /// [includeAxisTitle] is false for the top half of a mirrored axis because
  /// the shared title is painted only below the plot.
  double measureRequiredHeight(
    double plotWidth, {
    bool includeAxisTitle = true,
  }) {
    if (!config.visible) return 0;
    const tickLength = 6.0;
    final ticks = resolveTickValues(plotWidth);
    final labelWidth = _categoryLabelWidth(ticks, plotWidth);
    var tickLabelExtent = 0.0;
    if (config.shouldShowTickLabels) {
      for (final tick in ticks) {
        final painter = layoutTickLabel(tick, maximumWidth: labelWidth);
        tickLabelExtent = math.max(
          tickLabelExtent,
          _rotatedLabelHeight(painter),
        );
      }
    }
    final tickExtent = config.showTicks ? tickLength : 0.0;
    final labelExtent = config.shouldShowTickLabels
        ? config.tickLabelPadding + tickLabelExtent
        : 0.0;
    final titleExtent =
        includeAxisTitle &&
            config.shouldShowAxisLabel &&
            (config.label?.isNotEmpty ?? false)
        ? config.axisLabelPadding + (labelStyle.fontSize ?? 12) * 1.25
        : 0.0;
    return (tickExtent + labelExtent + titleExtent + config.axisMargin).clamp(
      config.minHeight,
      config.maxHeight,
    );
  }

  /// Paints the X-axis on the canvas.
  ///
  /// [canvas] is the canvas to draw on.
  /// [chartArea] is the total chart area.
  /// [plotArea] is the data rendering area (axis aligns to this).
  void paint(Canvas canvas, Rect chartArea, Rect plotArea) {
    // Early return if not visible
    if (!config.visible) {
      return;
    }

    final axisColor = resolveAxisColor();
    final paint = Paint()
      ..color = axisColor
      ..strokeWidth = 1.0
      ..style = PaintingStyle.stroke;

    final ticks = resolveTickValues(plotArea.width);
    final categoryLabelWidth = _categoryLabelWidth(ticks, plotArea.width);
    final positions = switch (config.position) {
      XAxisPosition.bottom => const [XAxisPosition.bottom],
      XAxisPosition.top => const [XAxisPosition.top],
      XAxisPosition.both => const [XAxisPosition.top, XAxisPosition.bottom],
    };

    for (final position in positions) {
      _paintAxisAt(
        canvas: canvas,
        chartArea: chartArea,
        plotArea: plotArea,
        position: position,
        paintAxisTitle:
            config.position != XAxisPosition.both ||
            position == XAxisPosition.bottom,
        axisColor: axisColor,
        paint: paint,
        ticks: ticks,
        categoryLabelWidth: categoryLabelWidth,
      );
    }
  }

  void _paintAxisAt({
    required Canvas canvas,
    required Rect chartArea,
    required Rect plotArea,
    required XAxisPosition position,
    required bool paintAxisTitle,
    required Color axisColor,
    required Paint paint,
    required List<double> ticks,
    required double categoryLabelWidth,
  }) {
    final isTop = position == XAxisPosition.top;
    final axisY = isTop ? plotArea.top : plotArea.bottom;
    final outwardDirection = isTop ? -1.0 : 1.0;
    final tickExtent = config.showTicks ? 6.0 : 0.0;

    // Draw the axis line on the configured plot edge.
    if (config.showAxisLine) {
      canvas.drawLine(
        Offset(plotArea.left, axisY),
        Offset(plotArea.right, axisY),
        paint,
      );
    }

    var maximumTickLabelHeight = 0.0;

    // Save canvas state and clip to the full axis margin on either edge.
    canvas.save();
    canvas.clipRect(
      Rect.fromLTRB(
        plotArea.left,
        chartArea.top,
        plotArea.right,
        chartArea.bottom,
      ),
    );

    final effectiveRenderMin = config.renderMin ?? axisBounds.min;
    final effectiveRenderMax = config.renderMax ?? axisBounds.max;

    for (final tickValue in ticks) {
      if (tickValue < effectiveRenderMin || tickValue > effectiveRenderMax) {
        continue;
      }
      // Calculate X position for this tick
      final ratio = tickRatio(tickValue);
      final x = plotArea.left + ratio * plotArea.width;

      // Draw tick mark
      if (config.showTicks) {
        const tickLength = 6.0;
        canvas.drawLine(
          Offset(x, axisY),
          Offset(x, axisY + outwardDirection * tickLength),
          paint,
        );
      }

      // Draw tick label (only if labelDisplay is not none)
      if (config.shouldShowTickLabels) {
        final textPainter = layoutTickLabel(
          tickValue,
          maximumWidth: categoryLabelWidth,
        );
        maximumTickLabelHeight = math.max(
          maximumTickLabelHeight,
          _rotatedLabelHeight(textPainter),
        );

        _paintTickLabel(
          canvas: canvas,
          painter: textPainter,
          centerX: x,
          nearEdgeY:
              axisY + outwardDirection * (tickExtent + config.tickLabelPadding),
          isTop: isTop,
        );
      }
    }

    // Minor ticks — shorter unlabelled marks between major ticks
    if (config.showMinorTicks &&
        config.minorTickCount > 0 &&
        ticks.length >= 2) {
      for (int i = 0; i < ticks.length - 1; i++) {
        final a = ticks[i];
        final b = ticks[i + 1];
        for (int j = 1; j <= config.minorTickCount; j++) {
          final v = a + (b - a) * j / (config.minorTickCount + 1);
          final ratio = tickRatio(v);
          final x = plotArea.left + ratio * plotArea.width;
          if (x >= plotArea.left &&
              x <= plotArea.right &&
              v >= effectiveRenderMin &&
              v <= effectiveRenderMax) {
            canvas.drawLine(
              Offset(x, axisY),
              Offset(x, axisY + outwardDirection * config.minorTickLength),
              paint,
            );
          }
        }
      }
    }

    // Restore canvas state after drawing ticks/labels
    canvas.restore();

    // Draw axis label if configured
    if (paintAxisTitle && config.shouldShowAxisLabel && config.label != null) {
      final axisLabelText =
          config.shouldAppendUnitToLabel && config.unit != null
          ? '${config.label} (${config.unit})'
          : config.label!;

      final axisLabelPainter = TextPainter(
        text: TextSpan(
          text: axisLabelText,
          style: labelStyle.copyWith(
            color: axisColor,
            fontWeight: FontWeight.bold,
          ),
        ),
        textDirection: textDirection,
      )..layout();

      final tickLabelExtent = config.shouldShowTickLabels
          ? config.tickLabelPadding + maximumTickLabelHeight
          : 0.0;
      final outwardExtent =
          tickExtent + tickLabelExtent + config.axisLabelPadding;
      final axisLabelY = isTop
          ? axisY - outwardExtent - axisLabelPainter.height
          : axisY + outwardExtent;

      // Use canvas save/restore to ensure axis label doesn't affect other rendering
      canvas.save();
      axisLabelPainter.paint(
        canvas,
        Offset(
          plotArea.left + (plotArea.width - axisLabelPainter.width) / 2,
          axisLabelY,
        ),
      );
      canvas.restore();
    }
  }

  /// The `[0, 1]` position of a tick [value] along this axis.
  ///
  /// The [AxisScaleType.linear] arm is the original expression verbatim
  /// (`axisBounds.span == 0 ? 0.0 : (value - axisBounds.min) / axisBounds.span`)
  /// shared by all tick/label placement sites; the [AxisScaleType.log] arm uses
  /// [logFraction], the same mapping [ChartTransform] applies to the marks, so
  /// ticks and marks stay registered.
  double tickRatio(double value) {
    if (config.scaleType == AxisScaleType.log) {
      return logFraction(value, axisBounds.min, axisBounds.max, config.logBase);
    }
    return axisBounds.span == 0
        ? 0.0
        : (value - axisBounds.min) / axisBounds.span;
  }

  /// Generates tick values for the axis.
  ///
  /// [bounds] is the data range for tick generation.
  /// [maxTicks] is the optional maximum number of ticks to generate.
  ///
  /// Returns a list of tick values within the bounds.
  ///
  /// Configured domain and render-window bounds constrain the visible bounds.
  /// If `config.tickCount` is set, it overrides maxTicks.
  List<double> generateTicks(DataRange bounds, {int? maxTicks}) {
    // Log axes emit decade values; the linear nice-number path below is
    // unchanged.
    if (config.scaleType == AxisScaleType.log) {
      return decadeTicks(bounds.min, bounds.max, base: config.logBase);
    }

    // Time axes land on real calendar boundaries; positions stay linear
    // (epoch-millis map linearly through ChartTransform's linear arm).
    if (config.scaleType == AxisScaleType.time) {
      return dateTicks(bounds.min, bounds.max);
    }

    // Use config.tickCount if provided, otherwise use maxTicks parameter
    maxTicks = config.tickCount ?? maxTicks ?? 10;

    // Generate against the currently visible interval. The configured domain
    // and render window constrain that interval, but must not replace it:
    // doing so calculates density for off-screen values and leaves a zoomed or
    // render-windowed X-axis much sparser than an equivalent Y-axis.
    final effectiveMin = math.max(
      bounds.min,
      math.max(
        config.min ?? double.negativeInfinity,
        config.renderMin ?? double.negativeInfinity,
      ),
    );
    final effectiveMax = math.min(
      bounds.max,
      math.min(
        config.max ?? double.infinity,
        config.renderMax ?? double.infinity,
      ),
    );
    if (effectiveMin > effectiveMax) return const [];
    final effectiveBounds = DataRange(min: effectiveMin, max: effectiveMax);

    if (effectiveBounds.span == 0) {
      return [effectiveBounds.min];
    }

    final range = effectiveBounds.span;
    final roughStep = range / (maxTicks - 1);
    // Choose one uniform readable interval that does not exceed the requested
    // budget. Index-thinning a denser sequence creates visibly irregular
    // intervals (and can produce duplicate formatted labels).
    final nicedStep = _niceNum(roughStep, round: false);

    final niceMin = (effectiveBounds.min / nicedStep).floor() * nicedStep;
    final niceMax = (effectiveBounds.max / nicedStep).ceil() * nicedStep;

    final ticks = <double>[];
    for (var tick = niceMin; tick <= niceMax; tick += nicedStep) {
      if (tick >= effectiveBounds.min && tick <= effectiveBounds.max) {
        ticks.add(_roundToDecimals(tick, 10));
      }
    }

    if (ticks.isEmpty) {
      ticks.add(effectiveBounds.min);
      if (effectiveBounds.min != effectiveBounds.max) {
        ticks.add(effectiveBounds.max);
      }
    }

    return ticks;
  }

  /// Formats a tick value for display.
  ///
  /// [value] is the tick value to format.
  ///
  /// Returns a formatted string representation of the value.
  String formatTickLabel(double value) {
    final categoryLabel = config.categoryLabelFor(value);
    if (categoryLabel != null) return categoryLabel;

    // Try custom formatter first
    if (config.labelFormatter != null) {
      try {
        return config.labelFormatter!(value);
      } catch (_) {
        // Fall through to default formatting
      }
    }

    // Log axes label their decades plainly (the value itself, e.g. "1000"),
    // before the numeric-default block. An explicit formatter above still wins.
    if (config.scaleType == AxisScaleType.log) {
      return _formatLogValue(value);
    }

    // Time axes label ticks with a calendar-nice date string chosen by the
    // span's interval (year→"2026", month→"Feb 2026", …), before the
    // numeric-default block. An explicit labelFormatter above still wins.
    if (config.scaleType == AxisScaleType.time) {
      return dateLabel(
        value,
        intervalFor(axisBounds.min, axisBounds.max),
      );
    }

    // Default formatting
    String formatted;
    if (value == value.roundToDouble()) {
      formatted = value.toInt().toString();
    } else if (value.abs() < 1) {
      formatted = value.toStringAsFixed(2);
    } else if (value.abs() < 100) {
      final rounded = _roundToDecimals(value, 1);
      formatted = rounded == rounded.roundToDouble()
          ? rounded.toInt().toString()
          : rounded.toStringAsFixed(1);
    } else {
      formatted = value.round().toString();
    }

    // Append unit if configured
    if (config.shouldShowTickUnit &&
        config.unit != null &&
        config.unit!.isNotEmpty) {
      formatted = '$formatted ${config.unit}';
    }

    return formatted;
  }

  double _categoryLabelWidth(List<double> ticks, double plotWidth) {
    final categoryAxis = config.categoryAxis;
    if (categoryAxis == null || ticks.isEmpty || axisBounds.span <= 0) {
      return double.infinity;
    }
    var minimumGap = double.infinity;
    for (var index = 1; index < ticks.length; index++) {
      minimumGap = math.min(minimumGap, ticks[index] - ticks[index - 1]);
    }
    if (!minimumGap.isFinite) minimumGap = 1;
    final available = plotWidth / axisBounds.span * minimumGap - 8;
    return math.min(categoryAxis.maximumLabelExtent, math.max(24, available));
  }

  double _rotatedLabelHeight(TextPainter painter) {
    final degrees = config.effectiveTickLabelRotationDegrees;
    if (degrees == 0) return painter.height;
    final radians = degrees.abs() * math.pi / 180;
    return painter.width * math.sin(radians) +
        painter.height * math.cos(radians);
  }

  double _rotatedLabelWidth(TextPainter painter) {
    final degrees = config.effectiveTickLabelRotationDegrees;
    if (degrees == 0) return painter.width;
    final radians = degrees.abs() * math.pi / 180;
    return painter.width * math.cos(radians) +
        painter.height * math.sin(radians);
  }

  void _paintTickLabel({
    required Canvas canvas,
    required TextPainter painter,
    required double centerX,
    required double nearEdgeY,
    required bool isTop,
  }) {
    final degrees = config.effectiveTickLabelRotationDegrees;
    final centerY = isTop
        ? nearEdgeY - _rotatedLabelHeight(painter) / 2
        : nearEdgeY + _rotatedLabelHeight(painter) / 2;
    canvas.save();
    canvas.translate(centerX, centerY);
    canvas.rotate(degrees * math.pi / 180);
    painter.paint(canvas, Offset(-painter.width / 2, -painter.height / 2));
    canvas.restore();
  }

  /// Resolves the color to use for the axis.
  ///
  /// Returns `config.color` if provided, otherwise returns a default axis color.
  Color resolveAxisColor() {
    // Priority 1: Explicit config color
    if (config.color != null) {
      return config.color!;
    }

    // Priority 2: First series color
    if (series != null && series!.isNotEmpty && series![0].color != null) {
      return series![0].color!;
    }

    // Priority 3: Default
    return const Color(0xFF333333);
  }

  /// Returns a "nice" number that is approximately equal to range.
  ///
  /// A "nice" number uses a compact set of readable decimal subdivisions.
  /// If [round] is true, rounds to nearest nice number; otherwise rounds up.
  double _niceNum(double range, {bool round = true}) {
    final exponent = math.log(range) / math.ln10;
    final fraction = range / math.pow(10, exponent.floor());

    double niceFraction;
    if (round) {
      if (fraction < 1.5) {
        niceFraction = 1;
      } else if (fraction < 3) {
        niceFraction = 2;
      } else if (fraction < 7) {
        niceFraction = 5;
      } else {
        niceFraction = 10;
      }
    } else {
      if (fraction <= 1) {
        niceFraction = 1;
      } else if (fraction <= 1.25) {
        niceFraction = 1.25;
      } else if (fraction <= 2) {
        niceFraction = 2;
      } else if (fraction <= 2.5) {
        niceFraction = 2.5;
      } else if (fraction <= 4) {
        niceFraction = 4;
      } else if (fraction <= 5) {
        niceFraction = 5;
      } else if (fraction <= 7.5) {
        niceFraction = 7.5;
      } else {
        niceFraction = 10;
      }
    }

    return niceFraction * math.pow(10, exponent.floor());
  }

  /// Rounds a value to the specified number of decimal places.
  double _roundToDecimals(double value, int decimals) {
    final factor = math.pow(10, decimals);
    return (value * factor).round() / factor;
  }

  /// Formats a log-axis decade value plainly (the value itself): whole decades
  /// render as integers (`1000`), fractional decades keep their minimal decimal
  /// form (`0.1`). Mirrored by the Y painter and the Y width-measure path.
  String _formatLogValue(double value) {
    if (value == value.roundToDouble()) {
      return value.toInt().toString();
    }
    return value.toString();
  }
}
